### ISSUE TITLE
Use on windows? 

### ISSUE THREAD

**Issue by yngwi** [yetone/avante.nvim#102]
Is there a way to use this on windows 11? When the plugin is activated I get an error message that says that windows nt isnt supported, even though the plugin seems to work afterwards.

**Comment by aarnphm** [comment]
what does the actual log say?

**Comment by aarnphm** [comment]
For windows you can remove the `build` args in lazy for now. I don't have a window machine on hand so I'm not entirely sure if tiktoken_lib can be built on windows.

Additionally, we would also have to update path regex for windows https://github.com/yetone/avante.nvim/blob/75ed191f43d61a9c8afefd2136d24f4cf1b08279/lua/tiktoken_lib.lua#L15

**Comment by yuchanns** [comment]
I can help to test if it can build on tiktoken later tonight :).

**Comment by pidgeon777** [comment]
I'm also a Windows user and experiencing the same problem with the Makefile. So, you're suggesting not to run the make at startup? It would be great to use tiktoken on Windows, too.

**Comment by pidgeon777** [comment]
There are some tiktoken references here:

https://github.com/CopilotC-Nvim/CopilotChat.nvim?tab=readme-ov-file#prerequisites

**Comment by yuchanns** [comment]
See #128  and For Windows users, change the build command to the following:

```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  build = "powershell -ExecutionPolicy Bypass -File Build-LuaTiktoken.ps1",
  -- rest of the config
}
```

**Comment by pidgeon777** [comment]
It builded successfully! I'm using:

```lua
build = vim.fn.has("win32") == 1 and "powershell -ExecutionPolicy Bypass -File Build-LuaTiktoken.ps1" or "make",
```

**Comment by yngwi** [comment]
Thank you. I couldn't try it yet but will do so next week.
