### ISSUE TITLE
Full controll over parsing response data

### ISSUE THREAD

**Issue by yuchanns** [yetone/avante.nvim#105]
When users use a custom vendor provider, they have minimal control over parsing the response, which can only be touched on by implementing `parse_response_data`.

In avante, response data will be processed by `parse_and_call` at first, assuming that all of the streaming chunks have the standard structure that can be matched sequentially with the keywords `event` and `data`. While things are not always true. In AWS bedrock, the streaming response is constructed in such format:
```
event{"bytes":"eyJ0eXBlIjoibWVzc2FnZV9zdGFydCIsIm1lc3NhZ2UiOnsiaWQiOiJtc2dfYmRya18wMU1CVmVzdXAzMWdFNTdHZWpZZzNjb3QiLCJ0eXBlIjoibWVzc2FnZSIsInJvbGUiOiJhc3Npc3RhbnQiLCJtb2RlbCI6ImNsYXVkZS0zLTUtc29ubmV0LTIwMjQwNjIwIiwiY29udGVudCI6W10sInN0b3BfcmVhc29uIjpudWxsLCJzdG9wX3NlcXVlbmNlIjpudWxsLCJ1c2FnZSI6eyJpbnB1dF90b2tlbnMiOjI0NzgsIm91dHB1dF90b2tlbnMiOjJ9fX0=","p":"abcdefghijklm"}
```
As you can see, the real response is encoded as base64 and placed in bytes, which is stopped by:
https://github.com/yetone/avante.nvim/blob/2d87dff33bd4cd47d19056562ac9c9ee06d76cb8/lua/avante/llm.lua#L553

Can we have a full control?

cc @aarnphm

**Comment by aarnphm** [comment]
oh wow they don't follow sse

**Comment by aarnphm** [comment]
The problem with this is there is no way to set the current_event_state correctly, if users can have custom on_callback like this. I'm not sure how to approach this.

**Comment by yuchanns** [comment]
We still need `parse_and_call`. Perhaps we could have a `data_match` function that allows users to customize their data matching.

**Comment by aarnphm** [comment]
or we can just expose the whole parse_and_call for users to modify the events themselves.

**Comment by aarnphm** [comment]
See wiki and #114
