### ISSUE TITLE
Provide Lua API to bind keymap

### ISSUE THREAD

**Issue by mistricky** [yetone/avante.nvim#107]
It would be great if Avante.nvim provide some Lua API to set keybinding like:
```lua
local avante = require("avante")

avante.ask()
avante.edit()
avante.refresh()
-- ...
```

The keybinding Lua API can help accomplish flexible tasks, such as refresh Avante in a script or something

**Comment by aarnphm** [comment]
avante currently already have `require('avante').toggle()` and `require('avante').refresh()` as API.

**Comment by mistricky** [comment]
Hey @aarnphm, thx for reply, can we separate Lua side and Vim side? Like https://github.com/mistricky/codesnap.nvim/blob/main/plugin/codesnap.lua do:
- In plugin folder, bind command using Lua API from `init.lua`
- In lua/init.lua, just export serials Lua function like `ask`, `edit`, `refresh` etc.

If we do, users can easily use these functions through:
```lua
local avante = require("avante")

avante.ask()
avante.edit()
avante.refresh()
-- ...
```

and we also have commands provided (bind by `plugin/avante.lua`)

**Comment by aarnphm** [comment]
We already have the command to binded with this, as `AvanteAsk`, `AvanteRefresh`, and `AvanteEdit`.

**Comment by aarnphm** [comment]
I'm pretty sure most of your asking has already been implemented.

both lua API are available, and all vim cmd are prefixed with `Avante` (AvanteAsk, AvanteRefresh)

Will close as not planned.

**Comment by KevinNitroG** [comment]
@aarnphm can we have the option to let users define themselves the keymap? Currently, some keymaps don't have descriptions, and others have descriptions whose format is inconsistent with users' styles.

![image](https://github.com/user-attachments/assets/697768dc-346b-42dc-8495-ac57d9e63258)

---

I have tried setup with Lazy

```lua
return {
  ...
  keys = {
    {
      "<leader>ac",
      desc = "Avante | Chat",
    },
    {
      "<leader>ar",
      desc = "Avante | Refresh",
    },
    {
      "<leader>aE",
      desc = "Avante | Edit",
    },
  },
  opts = {
    mappings = {
      ask = "<leader>ac",
      edit = "<leader>aE",
      refresh = "<leader>ar",
    },
  }
  ...
}
```

However, the config will overwrite the defined keymap descriptions.

---

Also, it would be nice if users could have Lua API to toggle debug and hint.

**Comment by aarnphm** [comment]
@yetone should we not set the mapping by default?

then we include the keymaps in the readme.md via docs?

Or we can also do https://github.com/nvim-neorocks/nvim-best-practices#white_check_mark-do-2?
