### ISSUE TITLE
Warn: tiktoken_core is not found!!!!

### ISSUE THREAD

**Issue by kohane27** [yetone/avante.nvim#108]
Hello, hope you're doing well.

`lua/plugins/avante.lua`:

```lua
return {
  enabled = true,
  "yetone/avante.nvim",
  event = "VeryLazy",
  build = "make",
  dependencies = {
    "nvim-tree/nvim-web-devicons",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    {
      "grapp-dev/nui-components.nvim",
      dependencies = { "MunifTanjim/nui.nvim" },
    },
    {
      "MeanderingProgrammer/render-markdown.nvim",
      opts = { file_types = { "Avante" } },
      ft = { "Avante" },
    },
  }
}
```

When I open a file I get the error message "Warn: tiktoken_core is not found!!!!".

However I see `tiktoken_core.so` in `~/.local/share/nvim/lazy/avante.nvim/build/`.

The line `local dirname = string.sub(debug.getinfo(1).source, 2, #"/tiktoken_lib.lua" * -1)` returns the following:

```
/home/username/.local/share/nvim/lazy/avante.nvim/lua/../build/?.so
```

It seems to be correct?

Is there any way I can help debug this issue?

System:

OS: Arch Linux (x86_64)
Kernel: Linux 6.10.5-arch1-1

nvim --version

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123

Thank you!

**Comment by yuchanns** [comment]
try:
```
file ~/.local/share/nvim/lazy/avante.nvim/build/tiktoken_core.so
```
and check if it is aarch64?

**Comment by kohane27** [comment]
```bash
➜ file ~/.local/share/nvim/lazy/avante.nvim/build/tiktoken_core.so
/home/username/.local/share/nvim/lazy/avante.nvim/build/tiktoken_core.so: ASCII text, with no line terminators
```

**Comment by yuchanns** [comment]
Emm, looks like it is not a real shared object. Do you have Rust installed in your host?

With Rust toolchain, try:
```lua
{
  "yetone/avante.nvim",
  build = "make BUILD_FROM_SOURCE=true luajit",
  ...
}
```

**Comment by kohane27** [comment]
`build = "make BUILD_FROM_SOURCE=true luajit"` works! Thank you!

Btw:

```
➜ rustc --version
rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Arch Linux rust 1:1.80.1-1)

~
➜ cargo version
cargo 1.80.1 (376290515 2024-07-16)
```

```bash
cd ~/.local/share/nvim/lazy/avante.nvim/
make
```

The output is still not a real shared object :thinking:

**Comment by mortbauer** [comment]
Same for me here on Arch

**Comment by mortbauer** [comment]
I think i solved the warning by installing luajit-tiktoken-bin on arch, however I still don't get any repsonse, just writes "Generating response" but never ever sometimes come back.

**Comment by kohane27** [comment]
@mortbauer Getting no response seems to be a separated issue. Maybe open a new issue? I closed this one for now. Thank you!:)

**Comment by aarnphm** [comment]
@mortbauer sorry for the ping but can you open a ticket for support on arch?

**Comment by mortbauer** [comment]
Actually it is working now, just had to install `luajit-tiktoken-bin` from aur, the other issue was that in the shell I tried it I somehow had not properly exported the `ANTHROPIC_API_KEY` didn't really get an error though, but now it is working fine!
