### ISSUE TITLE
can not config deepseek api

### ISSUE THREAD

**Issue by zhaopengme** [yetone/avante.nvim#109]
![image](https://github.com/user-attachments/assets/f3bddcbb-c458-445e-8051-4d1e9aecbb1f)

the window for configuring ANTHROPIC_API_KEY is always displayed,hwo can i switch to anthoer service?
I have configured the DEEPSEEK_API_KEY.

**Comment by carlesoctav** [comment]
setup the provider in the opts table.

```lua
return {
  "yetone/avante.nvim",
  event = "VeryLazy",
  build = "make lua51",
  opts = {
    provider = "deepseek"
  },
  dependencies = {
    "nvim-tree/nvim-web-devicons",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    {
      "grapp-dev/nui-components.nvim",
      dependencies = {
        "MunifTanjim/nui.nvim"
      }
    },
    --- The below is optional, make sure to setup it properly if you have lazy=true
    {
      'MeanderingProgrammer/render-markdown.nvim',
      opts = {
        file_types = { "markdown", "Avante" },
      },
      ft = { "markdown", "Avante" },
    },
  },
}
```

**Comment by zeroaddresss** [comment]
> setup the provider in the opts table.
> 
> ```lua
> return {
>   "yetone/avante.nvim",
>   event = "VeryLazy",
>   build = "make lua51",
>   opts = {
>     provider = "deepseek"
>   },
>   dependencies = {
>     "nvim-tree/nvim-web-devicons",
>     "stevearc/dressing.nvim",
>     "nvim-lua/plenary.nvim",
>     {
>       "grapp-dev/nui-components.nvim",
>       dependencies = {
>         "MunifTanjim/nui.nvim"
>       }
>     },
>     --- The below is optional, make sure to setup it properly if you have lazy=true
>     {
>       'MeanderingProgrammer/render-markdown.nvim',
>       opts = {
>         file_types = { "markdown", "Avante" },
>       },
>       ft = { "markdown", "Avante" },
>     },
>   },
> }
> ```

aren't you supposed to specify `endpoint` and `model` as well?
