### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by mortbauer** [yetone/avante.nvim#110]
I have `nvim-tree/nvim-web-devicons` and the nerdfont for my font installed but I still only see something like this for most icons:
![image](https://github.com/user-attachments/assets/8461f0da-f660-45e4-a13d-95f759f4408c)
I actually checked for `0x1f4bb`, which should be a laptop icon, but seems not to be supported by https://www.nerdfonts.com.

**Comment by yetone** [comment]
‌‌‌‌‌Ah, these two are both emojis. Let me change them to devicons.
