### ISSUE TITLE
Provide a top/bottom layout or a floating layout

### ISSUE THREAD

**Issue by zhou13** [yetone/avante.nvim#123]
In my normal setup, I use two or more terminal side by side so the sidebar is too wide to fit my screen space. Is it possible to provide a top/bottom split layout or a float-window layout (like telescope)?

**Comment by owenconti** [comment]
A floating window like in the `jackMort/ChatGPT.nvim` plugin would be great!

**Comment by rishadbaniya** [comment]
it would be great to have this feature, especially when one has vertical monitor..the bottom one helps a lot
and floating(well it's always helpful)

**Comment by tang-hi** [comment]
Hi, I create a PR to add the bottom layout. Any suggestion is welcome!
#420

**Comment by yetone** [comment]
The latest version already supports layout = 'horizontal'.

**Comment by yetone** [comment]
Just refactored and now use `windows.position = "top" | "bottom" | "left" | "right"` for the sidebar position: https://github.com/yetone/avante.nvim/pull/436
