### ISSUE TITLE
Neovim broken if the plugin is not installed by lazy.nvim

### ISSUE THREAD

**Issue by jiz4oh** [yetone/avante.nvim#127]
![image](https://github.com/user-attachments/assets/cb3d5434-a873-4838-b139-78d6beedb1e1)

Hi guys, I installed this plugin by [vim-plug](https://github.com/junegunn/vim-plug), could you considering add the compatibility with other plugin managers except [lazy.nvim](https://github.com/folke/lazy.nvim)

**Comment by aarnphm** [comment]
Not for now.

**Comment by jiz4oh** [comment]
so sad, can't wait to experience this plugin.

**Comment by aarnphm** [comment]
#256
