### ISSUE TITLE
[Feature request] proxy support for curl?

### ISSUE THREAD

**Issue by kohane27** [yetone/avante.nvim#134]
Hello there. Hope you're doing well. Thank you for creating this plugin that rivals Cursor!

## Description

I'm using [proton-privoxy](https://github.com/walterl/proton-privoxy) to use a proxy to access llm's API.

Currently I use a fork of yours: `llm.lua`:

```lua
  active_job = curl.post(spec.url, {
    headers = spec.headers,
    proxy = "http://127.0.0.1:8888",
    body = vim.json.encode(spec.body),
  }
```

`proxy = "http://127.0.0.1:8888"` is enough to make it work. But I'm not sure how to best integrate into the codebase. Thank you again!

**Comment by aarnphm** [comment]
You can set in the config 

```lua
proxy = nil, -- [protocol://]host[:port] Use this proxy
allow_insecure = false, -- Allow insecure server connections
```

**Comment by kohane27** [comment]
Thank you so much! I tried and it works!

One thing is that I don't need `allow_insecure` to make it work:

```lua
    claude = {
      endpoint = "https://api.anthropic.com",
      model = "claude-3-5-sonnet-20240620",
      proxy = "http://127.0.0.1:8888",
      -- allow_insecure = false,
    },
```

Regardless, thank you again!
