### ISSUE TITLE
features: ollama support 

### ISSUE THREAD

**Issue by SlayVict** [yetone/avante.nvim#135]
It would be great if it would be possible to use local llms with ollama and not only claude/openai models.

**Comment by makyfj** [comment]
You can, view the wiki: https://github.com/yetone/avante.nvim/wiki scroll to the bottom of the page

**Comment by theesfeld** [comment]
```
openai = {
  endpoint = "http://127.0.0.1:3000",
  model = "code-gemma",
  temperature = 0,
  max_tokens = 4096,
  ["local"] = true,
},
```

llama uses the same calls as the openai api, so this part of the installation instructions should work with ollama, lm-studio, ... any local llm engine that follows the openai api.

**Comment by jackplus-xyz** [comment]
Hi, after I made the following changes:

```lua
    opts = {
      provider = "openai",
      openai = {
        endpoint = "http://127.0.0.1:11434",
        model = "codegemma",
        temperature = 0,
        max_tokens = 4096,
        ["local"] = true,
      },
    },
```

I still get prompted to enter the API key when I started NeoVim, and getting errors: `Failed to setup openai. Avante won't work as expected`

I've tried: change the

**Comment by aarnphm** [comment]
the endpoint has to be `endpoint/v1` (avante will append `/chat/completions` to it)

**Comment by aarnphm** [comment]
can you try with #286?

**Comment by 0xWaleed** [comment]
> can you try with #286?

now gives an error when I send message in chat, instead of prompting when opening nvim 
![image](https://github.com/user-attachments/assets/36d21f87-5631-4a7f-ae0a-306d72f36684)

**Comment by aarnphm** [comment]
aight I will add a case for local llm to test this thoroughly, but #295 should address this

**Comment by aarnphm** [comment]
aight I will add a case for local llm to test this thoroughly, but #295 should address this
