### ISSUE TITLE
Overloaded?

### ISSUE THREAD

**Issue by theesfeld** [yetone/avante.nvim#144]
Getting this error a lot with the latest version:

```
🚨 Error: {
  error = {
    details = vim.NIL,
    message = "Overloaded",
    type = "overloaded_error"
  },
  type = "error"
}
```

**Comment by yetone** [comment]
‌‌‌‌‌‌‌Your request has exceeded the Anthropic API limit.

**Comment by liujoey** [comment]
How? I get this error for the very first request in a day.

**Comment by happylinks** [comment]
@yetone I'm hitting this regulary as well, would it be an idea to add exponentional backoff?
<img width="295" alt="image" src="https://github.com/user-attachments/assets/50ddc1a0-faeb-457c-9dc4-a464cb9a1a45">

**Comment by liujoey** [comment]
Hitting it the very first request of the day, this is definitely not a limit thing, either the Claude server has issues, or the plugin has issues.

**Comment by jcarlos7121** [comment]
Also seeing this.

The API limits of Anthropic look ok, and the question response doesn't request that many tokens, this is really weird.

**Comment by dzdidi** [comment]
Same here with the first request of the day

**Comment by dzdidi** [comment]
@yetone any updates?

**Comment by aaronmcadam** [comment]
Both Anthropic (https://status.anthropic.com/) and OpenAI (https://status.openai.com/) are currently having issues.
