### ISSUE TITLE
can not paste to input box of avante

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#150]

**Comment by atlas-comstock** [comment]
previously , it could; now it's broken after using new UI.

**Comment by atlas-comstock** [comment]
after uninstalling `nui-components`, it works

**Comment by atlas-comstock** [comment]
It happens on pasting long text

**Comment by theesfeld** [comment]
yes anything longer than one line just vanishes

**Comment by montagao** [comment]
seeing this too @yetone
