### ISSUE TITLE
Stuck on "Generating response..." with Copilot

### ISSUE THREAD

**Issue by sethfowler** [yetone/avante.nvim#157]
This plugin looks great! I'm excited to try it out.

Unfortunately, I'm not having much luck using it with Copilot. Asking any question results in "Generating response...", and that's as far as I get; no response is generated. I'm using `copilot.lua` with no problem, so Copilot is set up correctly as far as I know.

I'd love to provide more information if it would help debug the issue; is there a log being produced somewhere that I could share?

**Comment by yetone** [comment]
Are you using the latest version, and have you set your provider to copilot? I couldn't reproduce it on my end.

**Comment by aarnphm** [comment]
neither can i

**Comment by aarnphm** [comment]
hi there, can you try again on main? I have reduced the generated tokens for copilot so it should work on longer context for now.

**Comment by sethfowler** [comment]
So I tried out `CopilotChat.nvim`, and it gave me an error message that explained the underlying issue: the company I work for has disabled copilot chat. I didn't realize suggestions and chat could be enabled or disabled independently! This is resolved from my perspective, but FWIW, displaying the error message from the 403'd HTTP request, like `CopilotChat.nvim` does, might be a nice addition at some point.

**Comment by yetone** [comment]
Thank you for the suggestion. We will improve the error handling logic when requesting the AI API.
