### ISSUE TITLE
Latest update introduced new errors

### ISSUE THREAD

**Issue by zeroaddresss** [yetone/avante.nvim#165]
The plugin used to work smoothly before latest update, now I'm getting the following error (note that I haven't changed my config at all):
```
Failed to run `config` for avante.nvim
...hare/nvim/lazy/avante.nvim/lua/avante/providers/init.lua:115: module 'avante.providers.deepseek' not found:
	no field package.preload['avante.providers.deepseek']
cache_loader: module avante.providers.deepseek not found
cache_loader_lib: module avante.providers.deepseek not found
	no file './avante/providers/deepseek.lua'
	no file '/opt/homebrew/share/luajit-2.1/avante/providers/deepseek.lua'
	no file '/usr/local/share/lua/5.1/avante/providers/deepseek.lua'
	no file '/usr/local/share/lua/5.1/avante/providers/deepseek/init.lua'
	no file '/opt/homebrew/share/lua/5.1/avante/providers/deepseek.lua'
	no file '/opt/homebrew/share/lua/5.1/avante/providers/deepseek/init.lua'
	no file '/Users/asdrubale/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/avante/providers/deepseek.lua'
	no file '/Users/asdrubale/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/avante/providers/deepseek/init.lua'
	no file './avante/providers/deepseek.so'
	no file '/usr/local/lib/lua/5.1/avante/providers/deepseek.so'
	no file '/opt/homebrew/lib/lua/5.1/avante/providers/deepseek.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/asdrubale/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5.1/avante/providers/deepseek.so'
	no file './avante.so'
	no file '/usr/local/lib/lua/5.1/avante.so'
	no file '/opt/homebrew/lib/lua/5.1/avante.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/Users/asdrubale/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5.1/avante.so'
# stacktrace:
  - /avante.nvim/lua/avante/providers/init.lua:115 _in_ **__index**
  - /avante.nvim/lua/avante/providers/init.lua:205 _in_ **setup**
  - /avante.nvim/lua/avante/init.lua:210 _in_ **setup**
```

If it might help, my current setup is as follows:
```lua
{
    "yetone/avante.nvim",
    event = "VeryLazy",
    endpoint = "https://api.deepseek.com",
    build = "make",
    opts = {
      provider = "deepseek",
      deepseek = {
        endpoint = "https://deepseek.com/api",
        model = "deepseek-coder",
        temperature = 0,
        max_tokens = 4096,
      },
    },
    dependencies = {
      "nvim-tree/nvim-web-devicons",
      "stevearc/dressing.nvim",
      "nvim-lua/plenary.nvim",
      "MunifTanjim/nui.nvim",
      --- The below is optional, make sure to setup it properly if you have lazy=true
      {
        "MeanderingProgrammer/render-markdown.nvim",
        opts = {
          file_types = { "markdown", "Avante" },
        },
        ft = { "markdown", "Avante" },
      },
    },
  }
```

**Comment by aarnphm** [comment]
we decided not to support deepseek and groq as it is openai-compatible. You can use the following in the vendors section:

```lua
        ---@type AvanteProvider
        deepseek = {
          endpoint = "https://api.deepseek.com/chat/completions",
          model = "deepseek-coder",
          api_key_name = "DEEPSEEK_API_KEY",
          parse_curl_args = function(opts, code_opts)
            return {
              url = opts.endpoint,
              headers = {
                ["Accept"] = "application/json",
                ["Content-Type"] = "application/json",
                ["Authorization"] = "Bearer " .. os.getenv(opts.api_key_name),
              },
              body = {
                model = opts.model,
                messages = require("avante.providers").openai.parse_message(code_opts), -- you can make your own message, but this is very advanced
                temperature = 0,
                max_tokens = 4096,
                stream = true, -- this will be set by default.
              },
            }
          end,
          parse_response_data = function(data_stream, event_state, opts)
            require("avante.providers").openai.parse_response(data_stream, event_state, opts)
          end,
        },
```

See https://github.com/yetone/avante.nvim/wiki for more information.

**Comment by zeroaddresss** [comment]
> we decided not to support deepseek and groq as it is openai-compatible. You can use the following in the vendors section:
> 
> ```lua
>         ---@type AvanteProvider
>         deepseek = {
>           endpoint = "https://api.deepseek.com/chat/completions",
>           model = "deepseek-coder",
>           api_key_name = "DEEPSEEK_API_KEY",
>           parse_curl_args = function(opts, code_opts)
>             return {
>               url = opts.endpoint,
>               headers = {
>                 ["Accept"] = "application/json",
>                 ["Content-Type"] = "application/json",
>                 ["Authorization"] = "Bearer " .. os.getenv(opts.api_key_name),
>               },
>               body = {
>                 model = opts.model,
>                 messages = require("avante.providers").openai.parse_message(code_opts), -- you can make your own message, but this is very advanced
>                 temperature = 0,
>                 max_tokens = 4096,
>                 stream = true, -- this will be set by default.
>               },
>             }
>           end,
>           parse_response_data = function(data_stream, event_state, opts)
>             require("avante.providers").openai.parse_response(data_stream, event_state, opts)
>           end,
>         },
> ```
> 
> See https://github.com/yetone/avante.nvim/wiki for more information.

is it crucial to use the endpoint you specified?
[Docs](https://platform.deepseek.com/api-docs/) show multiple endpoints:
https://api.deepseek.com
https://api.deepseek.com/v1 (OpenAI compatible)
https://api.deepseek.com/chat/completions (the one you used in the snippet)

**Comment by aarnphm** [comment]
you can see the `opts.endpoint` below. it is just for convenience.
