### ISSUE TITLE
just found another good-looking markdown plugin

### ISSUE THREAD

**Issue by 2nthony** [yetone/avante.nvim#175]
https://github.com/OXY2DEV/markview.nvim

**Comment by yetone** [comment]
Thank you for the recommendation, let me try out this plugin.

**Comment by aarnphm** [comment]
I think this should already be supported, as Avante is a markdown filetype

**Comment by KevinNitroG** [comment]
> I think this should already be supported, as Avante is a markdown filetype

But I don't know how to config it to make it work with avante 😕

**Comment by chgara** [comment]
It can't be used with this plugin, author says the following

https://github.com/OXY2DEV/markview.nvim/issues/7#issuecomment-2198201945

**Comment by aarnphm** [comment]
What? we register treesitter of Avante to markdown. This is not correct

https://github.com/yetone/avante.nvim/blob/cd9412514ea013b6b0e884b44c14952c7734e2d1/lua/avante/init.lua#L165

**Comment by chgara** [comment]
> What? we register treesitter of Avante to markdown. This is not correct
> 
> https://github.com/yetone/avante.nvim/blob/cd9412514ea013b6b0e884b44c14952c7734e2d1/lua/avante/init.lua#L165

I have just now tried in local and it does not work trying to use the plugin, even configured for avante file type in the plugin.
It seems to be other things that need to be set to make it work, other person says the same in the issue

https://github.com/OXY2DEV/markview.nvim/issues/7#issuecomment-2291115436

That or maybe I am missing something


Here is a video of my trying it, and showing that if works for markdown but not for avante, and also the config I used.

https://github.com/user-attachments/assets/76934195-cc7d-4b60-9182-54195e45d8a0

**Comment by aarnphm** [comment]
Hmm I think the culprit is this https://github.com/OXY2DEV/markview.nvim/blob/main/plugin/markview.lua

```lua
  {
    "OXY2DEV/markview.nvim",
    enabled = true,
    lazy = false,
    ft = { "markdown", "norg", "rmd", "org", "vimwiki", "Avante" },
    opts = {
      file_types = { "markdown", "norg", "rmd", "org", "vimwiki", "Avante" },
      buf_ignore = {},
      max_length = 99999,
    },
  },
```
Even I enable all all buffer it doesn't seem to register correctly

**Comment by chgara** [comment]
> Hmm I think the culprit is this https://github.com/OXY2DEV/markview.nvim/blob/main/plugin/markview.lua
> 
> ```lua
>   {
>     "OXY2DEV/markview.nvim",
>     enabled = true,
>     lazy = false,
>     ft = { "markdown", "norg", "rmd", "org", "vimwiki", "Avante" },
>     opts = {
>       file_types = { "markdown", "norg", "rmd", "org", "vimwiki", "Avante" },
>       buf_ignore = {},
>       max_length = 99999,
>     },
>   },
> ```
> 
> Even I enable all all buffer it doesn't seem to register correctly

I think you need to use "filetypes" as name for the option, not "file_types"

https://github.com/OXY2DEV/markview.nvim/wiki/Configuration-options#-configuration-options

I think that the problem is in this function, in the file you referenced: 

https://github.com/OXY2DEV/markview.nvim/blob/1fd113802e008f09c6bb91d352f770e8b0bd4da4/plugin/markview.lua#L152

**Comment by aarnphm** [comment]
ye my bad, but this work

```lua
  {
    "OXY2DEV/markview.nvim",
    enabled = true,
    lazy = false,
    ft = { "markdown", "norg", "rmd", "org", "vimwiki", "Avante" },
    opts = {
      filetypes = { "markdown", "norg", "rmd", "org", "vimwiki", "Avante" },
      buf_ignore = {},
      max_length = 99999,
    },
  },
 ```

**Comment by aarnphm** [comment]
<img width="1419" alt="Screenshot 2024-08-27 at 19 29 39" src="https://github.com/user-attachments/assets/149a10b5-5d68-4696-a923-c4a880e90b36">

**Comment by aarnphm** [comment]
For future reference, all markdown renderer plugins should be supported by Avante by default, as Avante filetype is a markdown alias.
