### ISSUE TITLE
`AvanteSwitchProvider` Command Duplicates Custom Providers Every Time It’s Called

### ISSUE THREAD

**Issue by bassamsdata** [yetone/avante.nvim#176]
Every time I switch the provider, my custom providers "mistral" and "groq" get duplicated. The screenshot below clearly illustrates the issue.

<img width="472" alt="Screenshot 2024-08-23 at 11 11 59 AM" src="https://github.com/user-attachments/assets/be2fff93-0554-4f1a-82b7-be337960740f">

Thank you

**Comment by aarnphm** [comment]
This is no fixed on main

**Comment by bassamsdata** [comment]
thank you
