### ISSUE TITLE
Replace the input to be editable just like a buffer

### ISSUE THREAD

**Issue by Kazy** [yetone/avante.nvim#188]
A prompt or question can often be much longer than just a simple input. With the current implementation, it is difficult to see the full question and impossible to insert new lines. 

Would it be possible to use a Nui Popup instead of an Input (or anything else that would achieve the same thing) ? And also use a dedicated shortcut instead of `<CR>` to send the prompt ? 

I have an implementation in my fork, happy to submit it if you agree with the idea. This could also be behind a configuration.

**Comment by yetone** [comment]
I am also considering directly abandoning nui.input and using a regular floating window + buffer to do this. Of course, this floating window is still fixed at the bottom of the sidebar to simulate Cursor interaction (I don't really like entering large chunks of content in pop-ups). Is your fork implemented this way as well?

**Comment by Kazy** [comment]
> I am also considering directly abandoning nui.input and using a regular floating window + buffer to do this. Of course, this floating window is still fixed at the bottom of the sidebar to simulate Cursor interaction (I don't really like entering large chunks of content in pop-ups). Is your fork implemented this way as well?

It is using Nui, but using a Popup instead of an Input. I'll send a PR if you want to try !

**Comment by yetone** [comment]
Will the popup cover other content? It no longer looks like Claude. If that's the case, you can wait for my current modifications and see how it works for you.

**Comment by Kazy** [comment]
It doesn't, but happy to let you change it as well :)

**Comment by yetone** [comment]
‌‌You can try the latest version.

**Comment by Kazy** [comment]
> ‌‌You can try the latest version.

Perfect, thank you !
