### ISSUE TITLE
key binding to accept all changes

### ISSUE THREAD

**Issue by theesfeld** [yetone/avante.nvim#197]
I dont want to set the global automatic accept all, but sometimes during the review I DO want to accept all. would a key binding make sense here?

**Comment by aarnphm** [comment]
This would include a callback hook. Add some point we might add this. @yetone 

but also it is open source feel free to propose something concrete.

**Comment by yetone** [comment]
Adding acceptance for all shortcuts makes sense.

**Comment by yetone** [comment]
‌‌‌‌‌‌This feature is already in the latest version.
