### ISSUE TITLE
may i ask how to setup config?

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#21]
I am not using lazy nvim to install the avante, instead, i use Plugin to install it

And seems
```
require("avante").setup(){
}
```
can not config the configs.

**Comment by yuchanns** [comment]
```
require("avante").setup({
    -- place your config here
})

```

**Comment by atlas-comstock** [comment]
I see..
somehow other plugins have different format

```
require("CopilotChat").setup {
  model = 'gpt-4', -- GPT model to use, 'gpt-3.5-turbo' or 'gpt-4'
  question_header = '🧙:',
  separator = '🌟🌟🌟🌟🌟',
  answer_header = '🤖: ',
  temperature = 0.7, -- GPT temperature
  mappings = {
    complete = {
      detail = 'Use @<Tab> or /<Tab> for options.',
      insert ='<Tab>',
    },
    accept_diff = {
      normal = '<C-0>',
      insert = '<C-0>'
    },
  },
}
```

**Comment by yuchanns** [comment]
No, they are the same. Both `fn({})` and `fn {}` are valid function call syntaxes. The latter is a syntactic sugar of the previous.

**Comment by atlas-comstock** [comment]
> No, they are the same. Both `fn({})` and `fn {}` are valid function call syntaxes. The latter is a syntactic sugar of the previous.

yeah, thanks. just forgot the syntax
