### ISSUE TITLE
Claude stuck on "Generating response"...

### ISSUE THREAD

**Issue by ScaferuZ** [yetone/avante.nvim#211]
I just installed Avante with the defauilt configuration, on the docs, it says that on the first time opening it, we will be prompted to input our API key, but i didnt get it. then i store my claude key on my shell, and right now i cant figure it out why its not working. can anyone please help me? thanks!

**Comment by Milk-Maven** [comment]
I just installed it too and i"m having the same issue 

<img width="256" alt="image" src="https://github.com/user-attachments/assets/5b178790-63d9-4b48-86f4-698b8dbe774c">

**Comment by uflaks** [comment]
Same here, I also skipped the prompt for key as I did not have it by hand, but added it to my .zshrc later (by onepassword cli). Also if I choose copilot: 
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/0cfb020c-b61e-4309-92f7-6f6f945d1e66">

**Comment by aarnphm** [comment]
Can you send your configuration here?

**Comment by Milk-Maven** [comment]
Just using the default

{
      "yetone/avante.nvim",
      event = "VeryLazy",
      build = "make",
      opts = {
        -- add any opts here
      },
      dependencies = {
        "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
        "stevearc/dressing.nvim",
        "nvim-lua/plenary.nvim",
        "MunifTanjim/nui.nvim",
        --- The below is optional, make sure to setup it properly if you have lazy=true
        {
          "MeanderingProgrammer/render-markdown.nvim",
          opts = {
            file_types = { "markdown", "Avante" },
          },
          ft = { "markdown", "Avante" },
        },
      },
    }

**Comment by uflaks** [comment]
return {
	{
		"yetone/avante.nvim",
		event = "VeryLazy",
		build = "make lua51",
		opts = {
			-- add any opts here
		},
		dependencies = {
			"nvim-tree/nvim-web-devicons",
			"stevearc/dressing.nvim",
			"nvim-lua/plenary.nvim",
			"MunifTanjim/nui.nvim",
			--- The below is optional, make sure to setup it properly if you have lazy=true
			-- {
			-- 	"MeanderingProgrammer/render-markdown.nvim",
			-- 	opts = {
			-- 		file_types = { "markdown", "Avante" },
			-- 	},
			-- 	ft = { "markdown", "Avante" },
			-- },
		},
	},
}

**Comment by aarnphm** [comment]
This is now fixed on main

**Comment by ScaferuZ** [comment]
![image](https://github.com/user-attachments/assets/a6496de5-0d26-4707-b583-40ce6b0981c5)
when i first opened my nvim, it said that tiktoken_core is not found, does that mean the API is not found? but this is where i stored my claude token
![image](https://github.com/user-attachments/assets/0892b4a0-7aed-406e-a90a-3145743c96af)

**Comment by aarnphm** [comment]
Ah oversight on my end, it has to do with vim.schedule. 

it should evaluate envvar correctly now.

**Comment by en3sis** [comment]
> Ah oversight on my end, it has to do with vim.schedule.
> 
> it should evaluate envvar correctly now.

I just installed Avante for the first time and I am running into some issues with loading the env, it's set on my shell but every time I open nvim i get the key prompt and a message that says: 
![image](https://github.com/user-attachments/assets/f0364866-c203-4f9b-a121-5615d2f6a577)

Could this be related?

**Comment by ScaferuZ** [comment]
im sorry this might not be related, but i dont know whereelse to ask about this, 

for those who use claude, do we need to upgrade our account to the paid one? can we just use the free tier to use the API key? @uflaks @Milk-Maven

**Comment by uflaks** [comment]
> im sorry this might not be related, but i dont know whereelse to ask about this, 
> 
> 
> 
> for those who use claude, do we need to upgrade our account to the paid one? can we just use the free tier to use the API key? @uflaks @Milk-Maven 

I am already on a paid plan so I am not certain
