### ISSUE TITLE
THANKS A LOT!!

### ISSUE THREAD

**Issue by jikkuatwork** [yetone/avante.nvim#217]
I was having serious considerations to switch to Zed/Cursor throwing away my decade long experience with vim/nvim. This project is super promising. I loved the first stint. I can see using it!

Hope to see this maintained. Also a feedback, ability to clear context or the window might be great.

**Comment by shaleix** [comment]
> LSP + Tree-sitter + LLM Integration: Integrate with LSP and Tree-sitter and LLM to provide more accurate and powerful 
> code suggestions and analysis.
Can't wait for this feature. it will significantly improve the accuracy and speed of cmp
