### ISSUE TITLE
Error. Doesn't effect the plugin but tad bit annoying

### ISSUE THREAD

**Issue by aryang20** [yetone/avante.nvim#220]
<img width="454" alt="Screenshot 2024-08-25 at 2 10 56 PM" src="https://github.com/user-attachments/assets/f785d790-773d-43c8-a342-890566d9a8c9">
<img width="234" alt="Screenshot 2024-08-25 at 2 12 27 PM" src="https://github.com/user-attachments/assets/55091271-a5c8-4719-9750-80b9d48333da">

both avconfig.lua and avante.lua are in the same folder

**Comment by aarnphm** [comment]
what? This is user configuration, not related to the plugin.
