### ISSUE TITLE
[Off-topic] I really like the your git diff color style and the hint for shortcut!

### ISSUE THREAD

**Issue by LintaoAmons** [yetone/avante.nvim#222]
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/a8bb8d3b-b974-4da2-96ef-f1ece6decf41">

This view is so good! The color and the small hint at the right corner.

Hope one day you can turn it into a git diff plugin~

Take care and have some good sleep!

**Comment by yetone** [comment]
Thanks!
