### ISSUE TITLE
Is there anyway to adjust custom color scheme from the patch ?

### ISSUE THREAD

**Issue by zdk** [yetone/avante.nvim#229]
I have tried using avante.nvim and applying the patch from Claude.
Here is one of my sample screenshots:

![CleanShot 2567-08-26 at 13 50 14@2x](https://github.com/user-attachments/assets/03835f94-7bb3-49df-90e0-f8a3461e55e7)

It's a bit difficult to read the patch with the color scheme.

Not sure if it's something in my neovim setup or is it something I can config with avante.nvim, any suggestions ?

**Comment by yetone** [comment]
Yes, you can configure them in this way

<img width="355" alt="image" src="https://github.com/user-attachments/assets/d150a607-69e7-4c4e-a09a-49383006346b">

**Comment by zdk** [comment]
@yetone Thanks! 🙏
