### ISSUE TITLE
lua-tiktoken-temp build error

### ISSUE THREAD

**Issue by luuk00101** [yetone/avante.nvim#233]
Hey guys, any idea how to solve this build issue? I was trying to update the plugin. I have no idea, where the build folder might even be.

git clone https://github.com/gptlang/lua-tiktoken.git build/lua-tiktoken-temp
fatal: destination path 'build/lua-tiktoken-temp' already exists and is not an empty directory.
make: *** [build/tiktoken_core.dylib] Error 128

**Comment by luxus** [comment]
`rm -rf ~/.local/share/nvim/lazy/avante.nvim/build`

**Comment by futurisold** [comment]
Would be nice if it can be explicitly removed when the build fails

**Comment by luuk00101** [comment]
@luxus thank you very much :)
