### ISSUE TITLE
<esc> for sidebar overwrites other mappings

### ISSUE THREAD

**Issue by yngwi** [yetone/avante.nvim#234]
I have this mapping to execute `:noh` whenever I press escape: `vim.keymap.set("n", "<esc>", ":noh<cr><esc>", { remap = false, silent = true, nowait = true })`. This doesn’t work any more after I open the Avante sidebar. Is there a way to avoid this, maybe make "esc" a mapping only for the Avante-related file types?

**Comment by yetone** [comment]
The latest version has fixed this issue.

**Comment by yngwi** [comment]
Thank you!
