### ISSUE TITLE
flood of `Error: Error detected while processing WinResized Autocommands for "*":`

### ISSUE THREAD

**Issue by piotrostr** [yetone/avante.nvim#235]
<img width="752" alt="image" src="https://github.com/user-attachments/assets/eaad38b9-590a-41b8-982e-96b44e0efeab">

traceback:
```
Error executing lua callback: ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:589: Invalid 'window': Expected Lua number
stack traceback:
	[C]: in function 'nvim_win_is_valid'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:589: in function <...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:588>
```

my config is default from README.md, tried build from source with luajit but same thing happens

the extension works fine though, i am able to apply the diff hunks

**Comment by yetone** [comment]
@culda Can you update to the latest version? The latest version should have fixed this issue.

**Comment by yetone** [comment]
> FYI I had this earlier when cycling through some quickfix items and hitting enter. Tried to replicate it but couldn't. Never seen the top error
> 
> ```
> E5108: Error executing lua: ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1268: Invalid 'buffer': Expected Lua number                                                                       
> stack traceback:                                                                                                                                                                                                   
>         [C]: in function 'nvim_buf_get_lines'                                                                                                                                                                      
>         ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1268: in function 
> ```

The latest version has already fixed this issue.

**Comment by yetone** [comment]
@piotrostr Can you update to the latest version? The latest version should have fixed this issue.

**Comment by piotrostr** [comment]
yeah, was just submitting a PR with a fix and saw I'm 50+ commits behind, latest version works all gucci, marking as resolved

thanks! :)
