### ISSUE TITLE
instead of showing diff on current file, it would be much better to show it on sidebar

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#25]

**Comment by atlas-comstock** [comment]
maybe can suggest using https://github.com/sindrets/diffview.nvim?tab=readme-ov-file?

**Comment by yetone** [comment]
‌‌‌The original intention of this plugin was to completely simulate Cursor's interaction and behavior.

**Comment by atlas-comstock** [comment]
yes, but it's always good to make it better than Cursor if possible?

**Comment by aarnphm** [comment]
I never find diffview easy to use :)

**Comment by yetone** [comment]
In my opinion, this interaction isn't as good as Cursor.
