### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by lvim-tech** [yetone/avante.nvim#257]
Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/avante.nvim/lua/avante/utils.lua:14: module 'avante.utils.get_os_name' not found:

**Comment by jakubsuchy** [comment]
Seeing the same.

nvim 0.10.1
MacOS

**Comment by aarnphm** [comment]
should be fixed on main now, my bad.

**Comment by Pixxle** [comment]
@aarnphm That was quick! thanks
