### ISSUE TITLE
About the history log

### ISSUE THREAD

**Issue by yuchanns** [yetone/avante.nvim#26]
However, according to @aarnphm's suggestion, we should use [shada](https://neovim.io/doc/user/starting.html#shada-file) to store the history. I'm concerned that future refactoring might disrupt your current efforts. Are you interested in doing this refactoring?

_Originally posted by @yetone in https://github.com/yetone/avante.nvim/issues/18#issuecomment-2292840128_
            
We previously discussed the history log behavior of avante.nvim.

Using shada to store history is effective, but I would propose a more flexible approach that allows users to customize their history storage. For instance, some users might prefer to save and load from an abstract storage solution with cloud integration. The default option would still be shada.

What are your thoughts?

**Comment by yetone** [comment]
‌‌‌‌‌Saving in the cloud is a good feature. If the history is stored in the cloud, how can we uniquely locate a specific file within a project? Or to rephrase the question: what should the project ID be? It shouldn't be an absolute path, right?

**Comment by aarnphm** [comment]
Saving to the cloud is only useful for `nvim --remote` fwiw.

shada will be managed by nvim and with 0.11 dev it is pretty much free lunch as we don't have to worry too much about IO.

afaik doing anything IO intensive (such as saving history and polling from the cloud in neovim) is often frowned upon. If you know of any plugins that do this well, I'm more than happy to be proven wrong.

**Comment by aarnphm** [comment]
I was looking into this a bit, but now the logs is refactored to $XDG_DATA_STATE/avante, we can keep saving json for now.
