### ISSUE TITLE
[Critical Bug] Sending message to fast!, API key is not yet set 

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#269]
Using Azure setting

**Comment by atlas-comstock** [comment]
commit ad5b61bf6a64343673b5bcc1397a0556143bcbfc (HEAD -> main, origin/main, origin/HEAD)
Author: Aaron Pham <contact@aarnphm.xyz>
Date:   Tue Aug 27 02:12:35 2024 -0400

    perf: async login (closes #253) (#258)

    Signed-off-by: Aaron Pham <contact@aarnphm.xyz>


commit id

**Comment by atlas-comstock** [comment]
resetting to `git reset --hard f03c0918c90d9a904965e33fe566f4614845a1c7` works

**Comment by aarnphm** [comment]
solve with #268

**Comment by atlas-comstock** [comment]
confirmed fixed
