### ISSUE TITLE
[imrpovement] setting submit insert key doesn't work

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#270]
I set it via
```
  submit = {
      normal = "<CR>",
      insert = "<C-0>",
    },
```

have also try <C-f> , same; also need to update the hint here after changing the key
<img width="534" alt="image" src="https://github.com/user-attachments/assets/ee5b6348-cc17-4923-8223-05d6ef6c839c">

**Comment by yetone** [comment]
This hint indicates that the setting was not successful:

<img width="151" alt="image" src="https://github.com/user-attachments/assets/81d98278-faed-4a61-aa86-7a4a278be4e1">

The right way to configure it:

```lua
mappings = {
	submit = {
		normal = "<CR>",
		insert = "<C-0>",
	},
},
```

**Comment by aarnphm** [comment]
Make sure your terminal support `<C-0>` 
<img width="754" alt="Screenshot 2024-08-27 at 03 39 10" src="https://github.com/user-attachments/assets/25e434a6-3c16-49bc-9422-15c4e81006db">

**Comment by aarnphm** [comment]
Your configuration is not correct according to the spc
