### ISSUE TITLE
Copilot integration broken

### ISSUE THREAD

**Issue by Zamua** [yetone/avante.nvim#282]
hello,

i'm seeing an error with copilot integration after recent changes. when i try to use avante for anything i see the following
```
Received error from Copilot API: Bad Request
```

when i checkout commit hash 07af0a91f29584cdabf440dd3d4a0ed677ecf63e then the error goes away and functionality is restored
```
# this fixes it
cd ~/.local/share/nvim/lazy/avante.nvim
git checkout 07af0a91f29584cdabf440dd3d4a0ed677ecf63e
<restart nvim>
```

**Comment by aarnphm** [comment]
This has to do with the recent integrations from support pasting from clipboard. Copilot currently doesn't support image, so the text message is supposedly to be string instead of a list of message

**Comment by Zamua** [comment]
when i update and retry, i now see
```
Received error from Copilot API: bad request: unknown Editor-Version header for IDE auth
```

**Comment by rachartier** [comment]
Strange. When I replace `Editor-Version` by `vscode/1.70.2` inside the plugin's code, it all work great.

![image](https://github.com/user-attachments/assets/a16d97a7-5dfa-436e-a28a-0024f8c954de)

**Comment by aarnphm** [comment]
sorry, I was having lunch, but https://github.com/yetone/avante.nvim/pull/287 should fix this now. Thanks for all the feedback
