### ISSUE TITLE
Diff background color makes text unreadable

### ISSUE THREAD

**Issue by AdamDorwart** [yetone/avante.nvim#283]
Sorry if I'm knocking on the wrong door. I just installed the plugin and went to apply a patch and it's pretty unreadable because of the background color. I'm not sure if these are default colors set by this plugin or something wrong with my setup (mostly vanilla Astronvim w/ Astrodark theme). When I select a different theme (even reselecting Astrodark) these background colors go away which is why I'm starting here. If they are set here I just need some configuration to make them readable for my theme. Thanks!

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/b6fcf06e-dfe8-4012-8ef6-0b15d9aee719">

**Comment by aarnphm** [comment]
That depends on `DiffAdd` and `DiffText`, so if they colorscheme doesn't set those highlight you will have to

**Comment by AdamDorwart** [comment]
Thanks, I'm still pretty new to neovim. I'm enjoying the plugin!

For anyone else with skill issues like me here's what I changed:
`~/.config/nvim/lua/plugins/astroui.lua`
```lua
return {
  "AstroNvim/astroui",
  ---@type AstroUIOpts
  opts = {
    colorscheme = "astrodark",
    highlights = {
      astrodark = {
        DiffAdd = { fg = "#00ff00", bg = "#005500" },
        DiffText = { fg = "#ffff00", bg = "#555500" },
      },
    },
}
```

**Comment by aarnphm** [comment]
see https://github.com/AstroNvim/astrotheme/pull/139
