### ISSUE TITLE
Edit code not working properly with copilot

### ISSUE THREAD

**Issue by chgara** [yetone/avante.nvim#296]
When trying to edit a piece of code with the edit functionality using copilot as provider it does not edit the code properly it gives the full file prefixed by the type of it. If seen the demos of the feature working so I must asume that copilot needs other type of prompt or something like that.

Also the UI of it its kinda bugged when doing the response, but it can be that I use dressing.nvim for changing the default input.

I attach a video of it.

Thks.

https://github.com/user-attachments/assets/51a15bf0-0168-4187-b2c9-7bc73f666d98

**Comment by pidgeon777** [comment]
> When trying to edit a piece of code with the edit functionality using copilot as provider it does not edit the code properly it gives the full file prefixed by the type of it. If seen the demos of the feature working so I must asume that copilot needs other type of prompt or something like that.

I confirm this issue using copilot.

**Comment by yetone** [comment]
Support for the Copilot provider has been removed
