### ISSUE TITLE
Add Ollama Support for Avante Neovim Plugin

### ISSUE THREAD

**Issue by zetsuchan** [yetone/avante.nvim#300]
We need to integrate Ollama support into the Avante Neovim plugin to enhance its functionality and provide users with a more powerful development environment. Ollama's features will allow us to offer advanced capabilities such as real-time collaboration, enhanced AI-driven code suggestions, and improved project management within Neovim.

Tasks:
1. Research Ollama Integration:
   - Investigate the Ollama API and SDK.
   - Identify the key features of Ollama that would be beneficial to integrate into Avante.

2. Design the Integration:
   - Plan how Ollama's features will be incorporated into Avante.
   - Design the user interface for interacting with Ollama within Neovim.

3. Implement the Integration:
   - Write the necessary code to integrate Ollama with Avante.
   - Ensure that the integration is seamless and doesn't disrupt the existing functionality of the plugin.

4. Testing:
   - Test the integration in different environments to ensure compatibility.
   - Fix any bugs or issues that arise during testing.

5. Documentation:
   - Update the README and any other relevant documentation to include instructions on how to use Ollama within Avante.
   - Provide examples and use cases to help users understand the new functionality.

6. Release:
   - Prepare a new release of Avante that includes the Ollama integration.
   - Announce the new feature to the community and gather feedback.

Benefits:
- Enhances the functionality of Avante by leveraging Ollama's advanced features.
- Provides users with more powerful tools for collaboration and code management.
- Keeps Avante competitive with other Neovim plugins by integrating cutting-edge technology.

**Comment by aarnphm** [comment]
check wiki
