### ISSUE TITLE
feat: Lazy loading of secret

### ISSUE THREAD

**Issue by fredrikaverpil** [yetone/avante.nvim#305]
Hey 👋  and thanks for putting together Avante! 😊

I think it would be really nice if you could avoid relying on setting environment variables such as `ANTHROPIC_API_KEY` in the environment. One option would be to also be able to provide a terminal command which fetches the secret. For example, there's the [`op` CLI command for 1Password](https://developer.1password.com/docs/cli/get-started/).

If such a feature would be implemented, it would also be important to lazy load this, or a 1Password prompt would appear by just starting Neovim. I would want that to appear only when I actually open the plugin or when I start chatting with e.g. Claude.

**Comment by aarnphm** [comment]
you can use it with `cmd:op ...` into api_key

```lua
      claude = {
        api_key_name = "cmd:bw get notes anthropic-api-key",
      },
```

**Comment by fredrikaverpil** [comment]
Nice @aarnphm !

However, this is not lazy loaded (as it is in codecompanion btw). This means this popup will appear as soon as I launch `nvim` when I've configured the 1Password CLI to be used:

![Screenshot 2024-08-29 at 09 22 08](https://github.com/user-attachments/assets/31a0fc9d-f072-4735-946e-5903b892dd7c)

**Comment by strayer** [comment]
> you can use it with `cmd:op ...` into api_key
> 
> ```lua
>       claude = {
>         api_key_name = "cmd:bw get notes anthropic-api-key",
>       },
> ```
> 
> inspired by codecompanion.nvim

This currently doesn't work when the command includes parameters with spaces: `op read "op://vault/anthropic/API Key"`. I think the issue is that the command is simply split by spaces here:

https://github.com/yetone/avante.nvim/blob/e16111ba341511bb6aff30444bf00e9aa85461a1/lua/avante/providers/init.lua#L126

This then causes `op` to be called with two parameters for the secret secret reference: `"op://vault/anthropic/API` and `Key"`.

For reference, [Robitx/gp.nvim](https://github.com/Robitx/gp.nvim) allows specifying a table as an API key which gp.nvim will then execute: `openai_api_key = { "bw", "get", "password", "OAI_API_KEY" }`

**Comment by aarnphm** [comment]
I added support for table on secrets at #500. For lazy loading secrets currently there is no guarantee for avante to ensure the secrets to be setup correctly before running stream

If you want to lazy loading this you can try doing it through `cmd = {"AvanteAsk"}` on lazy.nvim.

> However, this is not lazy loaded (as it is in codecompanion btw). This means this popup will appear as soon as I launch `nvim` when I've configured the 1Password CLI to be used:
> 
> ![Screenshot 2024-08-29 at 09 22 08](https://private-user-images.githubusercontent.com/994357/362574571-31a0fc9d-f072-4735-946e-5903b892dd7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTQ3OTQsIm5iZiI6MTcyNTQxNDQ5NCwicGF0aCI6Ii85OTQzNTcvMzYyNTc0NTcxLTMxYTBmYzlkLWYwNzItNDczNS05NDZlLTU5MDNiODkyZGQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwMTQ4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzQxMTlkMmFlZTJjNTg3NjdmMjViOGY0YTZmOTk4OWZjY2Y5ODgxZjA2NTE2NDQwOTE1MTA3ZGU2NmZiZTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.03lfxUrKE6fquqQYakgNTzcerHHowLBqXhNxYyQVygU)
> 
> I have only configured Claude, but I guess I would get one popup per key that is requested by avante.
> 
> If you wish we can re-open this issue and rename the title to make it more clear that lazy loading is not supported.

This will requires a cleanup of providers, which we might do sometime later.

**Comment by olimorris** [comment]
@aarnphm as the CodeCompanion maintainer, I would ❤️ to get a shout out in your README 😄 .

**Comment by cyaconi** [comment]
I also use 1password's `op read`, however the `cmd = {"AvanteAsk"}` didn't work for me. The 1password popup appears as soon as I open neovim and not in my first attempt using avante

**Comment by benvp** [comment]
This works for me:

```
  cmd = { 'AvanteAsk', 'AvanteToggle', 'AvanteChat' },
  keys = {
    { '<leader>aa', '<cmd>AvanteToggle<cr>', desc = 'Toggle Avante' }
  },
```

Will lazy load avante if `<leader>aa` . You have to make sure to *not* have `event = "VeryLazy"` and/or `lazy = false` in your config.

**Comment by fredrikaverpil** [comment]
Nice, thank you @benvp, works for me!

**Comment by fredrikaverpil** [comment]
I'm not sure what happened, but Avante probably changed in some way. I am getting the 1password popup everytime I start Neovim with this config:


```lua
return {
  {
    "yetone/avante.nvim",
    lazy = true,
    version = false,
    build = "make",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "MunifTanjim/nui.nvim",
      "echasnovski/mini.icons",
    },
    opts = {
      provider = "claude",
      providers = {
        claude = {
          -- FIXME: this unfortunately triggers on Neovim startup
          api_key_name = "cmd:op read op://Personal/Anthropic/tokens/neovim --no-newline",
        },
      },
    },
    cmd = {
      "AvanteAsk",
      "AvanteToggle",
    },
    keys = {
      { "<leader>aa", "<cmd>AvanteToggle<cr>", desc = "Toggle Avante" },
    },
  },
}
```

Has anyone figured out a workaround?

**Comment by fredrikaverpil** [comment]
I opened up a PR which at least works on my end; https://github.com/yetone/avante.nvim/pull/2372
