### ISSUE TITLE
tiktoken_core not found

### ISSUE THREAD

**Issue by toblerlee** [yetone/avante.nvim#31]
I am on m3 macbook pro with cargo installed.  I get this message once "tiktoken_core not found".  I never got messages from claude or openai only stuck at "Generating response from claude..."

**Comment by wey-gu** [comment]
try this

```
brew install cargo
```

then trigger install of this plugin again for building tiktoken_core

**Comment by toblerlee** [comment]
Thanks.  I did try it and tiktoken error is gone but claude is still stuck without answer.
I got following warning which I am not sure if related
`~/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua` can't modify buffer or window
`function Line:render(bufnr, ns_id, linenr_start, linenr_end)
  local row_start = linenr_start - 1
  local row_end = linenr_end and linenr_end - 1 or row_start + 1
  local content = self:content()
  vim.api.nvim_buf_set_lines(bufnr, row_start, row_end, false, { content })
  self:highlight(bufnr, ns_id, linenr_start)
end`

**Comment by aarnphm** [comment]
this is unrelated, tho I do know about this issue.

**Comment by aarnphm** [comment]
can you create a separate ticket to track this?

**Comment by toblerlee** [comment]
Done.  I create new ticket, thank you.
