### ISSUE TITLE
nui not allowed to change text or change window

### ISSUE THREAD

**Issue by toblerlee** [yetone/avante.nvim#32]
![WhatsApp Image 2024-08-16 at 21 23 46](https://github.com/user-attachments/assets/9538ab29-8737-4464-a8ee-c2bc5606f11e)

~/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua line 72

I am not able to get response from either claude or openai

**Comment by yetone** [comment]
‌‌‌Can you upgrade to the latest version and try it?

**Comment by toblerlee** [comment]
<img width="1388" alt="Screenshot 2024-08-17 at 1 38 00 PM" src="https://github.com/user-attachments/assets/ffc56406-1613-4d02-9b18-5f3997d887c2">
same same.  I am still stuck at "generating response from claude..."

**Comment by aarnphm** [comment]
did you move the cursor somewhere, I tried with both claude and openai and the stream generates fine?

**Comment by aarnphm** [comment]
I would recommend trying in a normal terminal, without tmux and vscode :) I don't use tmux so I'm not entirely sure whether it would affect input

**Comment by toblerlee** [comment]
![Screenshot 2024-08-17 at 2 12 21 PM](https://github.com/user-attachments/assets/5dba08d2-3381-4d08-9127-e28ec9c98b2e)
Thanks I also tried a normal terminal without extra tmux or vscode.  I moved cursor around as well but didn't help

**Comment by aarnphm** [comment]
Can you just try exporting the envvar for now, I'm working on a fix rn

**Comment by toblerlee** [comment]
Yes I tried exporting the envvar and I even tried to generate new key but same result

**Comment by aarnphm** [comment]
Can you try this branch? https://github.com/yetone/avante.nvim/pull/58

Not sure how to reproduce

**Comment by ipunkid** [comment]
I had the exact same issue as well, stuck at the generating response process. I noticed that AvanteAsk's curl call to Claude only consumed 6kb of network data. Could this be due to network environment issues?
<img width="1012" alt="截屏2024-08-18 16 17 17" src="https://github.com/user-attachments/assets/8b6eebf6-e90a-4d69-b68a-dad211fc7cb0">

**Comment by yetone** [comment]
‌‌‌‌It seems like a network environment issue. You can try switching providers, for example, switch to OpenAI. @ipunkid
