### ISSUE TITLE
Feature Request: Ability to Switch AI Providers

### ISSUE THREAD

**Issue by arnm** [yetone/avante.nvim#327]
Currently, Avante.nvim requires users to specify a single AI provider in the configuration, which necessitates updating the configuration and reloading Neovim to switch providers. This process can be cumbersome, especially for users who wish to experiment with different AI models or need to switch providers frequently based on their tasks.

## Proposed Feature:
Dynamic Provider Switching: Implement a command that allows users to switch between configured providers without needing to reload the entire configuration.

## Benefits:
Flexibility: Users can easily switch between different AI models based on their current needs or preferences.
Efficiency: Reduces the downtime associated with reloading Neovim and reconfiguring the plugin.

Personally, I'm cost conscious and utilize gpt-4o-mini for tedious non-complex tasks which is considerably cheaper than claude 3.5 sonnet. I would use claude for more complex tasks, like refactoring.

**Comment by Koihin88** [comment]
`:AvanteSwitch`

**Comment by arnm** [comment]
> `:AvanteSwitch`

Awesome, already exists `:AvanteSwitchProvider`
