### ISSUE TITLE
inlay hints enabled automatically after accepting change

### ISSUE THREAD

**Issue by dbarrosop** [yetone/avante.nvim#334]
Hello,
I am not sure what's happening here but after accepting a change proposal inlay hints seem to enable themselves automatically in that buffer.

Thanks!

**Comment by aarnphm** [comment]
not sure what do you mean here?

The apply text should only show in visual mode. If possible can you record a video?

**Comment by dbarrosop** [comment]
Of course:

https://www.loom.com/share/6794b69e92254eed84b22894c5bbe9c1

Notice the inlay hints in `fmt.Println`, they appear after accepting the changes.

**Comment by aarnphm** [comment]
ah I see, will post a pr to fix

**Comment by dbarrosop** [comment]
Thanks, I can confirm the problem is gone.
