### ISSUE TITLE
Asking a question about a code block when the sidebar is already open doesnt work

### ISSUE THREAD

**Issue by GRVYDEV** [yetone/avante.nvim#338]
First of all I want to say this is outstanding. It was very easy to get setup and it just works so major kudos. I did notice a small bug when I tried to ask a question about a code block (highlighted and then did <leader>aa) when the sidebar was already open. This didnt seem to work. Unsure what your thoughts on the expected behavior here are but I would be fine if it just cleared out the sidebar and started a new one with the selected code.

**Comment by aarnphm** [comment]
Not entirely sure how to reproduce this, but your workflow works fine here:


https://github.com/user-attachments/assets/e452d557-5810-43fc-acab-fd82f82e90f1

**Comment by GRVYDEV** [comment]
Ah my bad it does work properly however there is a bug where it resizes my window. If you do it with 2 vertical splits the second time you do <leader>aa it will resize the split as if the ask window closed. I will try to get a video to showcase this soon. It appears that it is more of a visual bug

**Comment by aarnphm** [comment]
you can just do `wincmd =` yourself.
