### ISSUE TITLE
The new version's UX is not good

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#35]
Sidebar is hard to operate/view and press A on different code chages is quite messy

**Comment by atlas-comstock** [comment]
And i tried a few times, the generated diff is not correct.

**Comment by yetone** [comment]
‌‌You can try the latest version, which has great shortcut key hints.

https://github.com/user-attachments/assets/ac21c529-c402-40d1-b16c-9d6886ca8e80

**Comment by atlas-comstock** [comment]
@yetone yes, this is the version i mentioned about here.

**Comment by yetone** [comment]
Why is the sidebar difficult to operate and view? It's the same interaction as with the Cursor IDE. What kind of interaction do you want?

**Comment by atlas-comstock** [comment]
@yetone 
For the not correct result, it looks like the answer because the file is too long and LLM is confused and give wrong output.

For the UX, sometimes, i use nvim windows op <ctrl> w + jkl to jump to the sidebar; however, most of the time the `A` can't be triggered, unless i use mouse to click it

(also i couldn't find a good way to expand it: if i use <ctrl>w + t to open it in new window, A does not work

**Comment by atlas-comstock** [comment]
After using https://github.com/hrishioa/mandark and your plugin(maybe Cursor), i like mandark's UX better.

Reason:
1. after calling LLM to update/write the code, by right we expect to apply them;
2. it would be better to have dedicate screen to show the diff one by one, and users view the change/reason to change, decide apply or not; then the next one
3. Better to provide overall `git diff`(or this op's change in case LLM was wrong) for current change if possible
4. Done

**Comment by yetone** [comment]
‌‌‌‌‌2 and 3 are features that have always existed.

**Comment by yetone** [comment]
press A ‌‌‌‌‌‌‌The function has always been normal on my end, very normal.

**Comment by aarnphm** [comment]
@yetone we can add `<C-w>j` and `<C-w>k` to navigate the buffer as well?

**Comment by yetone** [comment]
‌I tried the latest version of the code and indeed there is an issue with A key not being bound. Only the history record has A key, the new chat result does not. @aarnphm

**Comment by yetone** [comment]
‌‌‌Hello, the latest version has fixed the issue where the A shortcut key was not binding correctly. @atlas-comstock

**Comment by yetone** [comment]
‌‌‌‌‌‌Major update: After a series of prompt optimizations, the probability of incorrect lines in the returned modified code snippets has been greatly reduced! The results are now mostly correct!

**Comment by atlas-comstock** [comment]
@yetone thanks, much better now(however i encountered incorrect even in small portion of code this time lol, it's ok)

Another issue in myside is that , all output are automatically wrapped and not expanded, is it expected?

**Comment by yetone** [comment]
@atlas-comstock wrap is because I [hardcoded](https://github.com/yetone/avante.nvim/blob/c25521070a0a28ebbddca6320632926415838efd/lua/avante/view.lua#L45) this option, I prefer wrap because long text lines can be seen without moving the cursor, but I can consider making wrap a configurable option to suit everyone's taste.

**Comment by yetone** [comment]
@atlas-comstock The latest version of wrap can be configured.

<img width="331" alt="image" src="https://github.com/user-attachments/assets/237b59e1-29d7-409a-816a-5beeb564dc13">

**Comment by atlas-comstock** [comment]
@yetone aha, sry, wrap in my context is collapse the sentence automatically.  Yes, i like the wrap line now.

<img width="528" alt="image" src="https://github.com/user-attachments/assets/09e0e530-5aa9-441c-b144-04c01c1bf1c7">

**Comment by aarnphm** [comment]
> @yetone aha, sry, wrap in my context is collapse the sentence automatically. Yes, i like the wrap line now.
> 
> <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/7270555/358889157-09e0e530-5aa9-441c-b144-04c01c1bf1c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5Njk1ODEsIm5iZiI6MTcyMzk2OTI4MSwicGF0aCI6Ii83MjcwNTU1LzM1ODg4OTE1Ny0wOWUwZTUzMC01YWE5LTQ0MWMtYjE0NC0wNGMwMWMxYmYxYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MThUMDgyMTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc5ZGIyYjJjMWE4ZmQ5MjI0MDI3NDc4NzU5NWZmMDk0MjE1OGY5NmQyNTY2NzkzMWFkMjdlNzJmYzc4MDUyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fJ9CYyWQJeUd-qEE8AepfNSAPR0rvqwak7-T5URXLho">

You should change how conceallevel work on your config :)

**Comment by atlas-comstock** [comment]
@aarnphm yeah, thanks.

```
      vim.wo[winid].conceallevel = 2
```

how to config this now?

**Comment by aarnphm** [comment]
This is unrelated, as this is only affected for the dressing api_key buffer
