### ISSUE TITLE
Highlighted line(s) still shows original key mapping, despite change in plugins file

### ISSUE THREAD

**Issue by riordant** [yetone/avante.nvim#358]
![image](https://github.com/user-attachments/assets/0763075f-6cc9-4db9-9cee-400287a0fad6)

Notice it still says `<leader>aa ask`, despite change to `<leader>g` for the keymapping (`<leader>g` still works, just visual issue)

Thanks for awesome plugin

**Comment by XenoCode54** [comment]
You might have to make those changes instead in your
`~/.local/share/nvim/lazy/avante.nvim/lua/avante/config.lua`

**Comment by aarnphm** [comment]
see https://github.com/yetone/avante.nvim/wiki#keymaps-and-api-i-guess.

I don't know how to know how to update the hint correctly. so if you have any suggestion you are more than welcome to

**Comment by aarnphm** [comment]
I added a snippet to the wiki for your reference.

**Comment by riordant** [comment]
Thanks!
