### ISSUE TITLE
Claude AI Pro subscription support?

### ISSUE THREAD

**Issue by XenoCode54** [yetone/avante.nvim#359]
Hi, 

this might be a dumb question but, 

After subscribing to Claude AI Pro, can it be used with Avante or does it only support the Claude Api (which is a pay-as-you-go) version?

Thank you.

**Comment by theesfeld** [comment]
The API use (Avante, etc) is a different account than the Anthropic web chat interface. Its the 'pay-as-you-go' account you referenced.

**Comment by aarnphm** [comment]
API and pro chat are two different things (similar to ChatGPT and OpenAI API).

closed due to not related to avante.nvim.
