### ISSUE TITLE
Warnings blocking nvim startup && Plug broken recently.

### ISSUE THREAD

**Issue by jmoudrik** [yetone/avante.nvim#362]
Hi,

**Issues**
- avante now blocks nvim startup with 2 unnecessary warnings (img clip not installed, lazy not installed), which however need to be "entered" away on each nvim start (is this maybe an error in my config?)
- `img-clip.nvim` is actually installed on my system, but not through lazy
- this only started happening today, before my `Plug` setup was working completely fine (with no blocking warns)

**My setup**
- avante installed via plug `Plug 'yetone/avante.nvim', { 'do': 'make' }`
- img clip as well `Plug 'HakonHarnes/img-clip.nvim'`
- avante configures normally in lua via `require('avante').setup({...})`
- no lazy stuff

**Suggested solution**
- non-blocking warning or a way to disable warning (nobody imo wants to have startup blocked by enter); or is there an external possibility to silence the startup from lua config / mea culpa?
- checking for module existence should be imho done directly, not via Lazy -- with this, other pkg managers would work directly, here:
https://github.com/yetone/avante.nvim/blob/24b0bfadea4ef4cb02581e3bf8b4d5d935ca9a25/lua/avante/utils/init.lua#L23-L29

EDIT: now that I am looking again, it has a branch for non-lazy pkg, but in that case, it does not catch img-clip from Plug?

**Comment by jmoudrik** [comment]
Ok, now I believe that the "img-clip" not recognized should be fixed by
changing  `Utils.has("img-clip.nvim")` -> `Utils.has("img-clip.nvim") or Utils.has("img-clip")`
(cause the non lazy branch of check does not have key `img-clip.nvim` in `package.loaded`

Here 
https://github.com/yetone/avante.nvim/blob/24b0bfadea4ef4cb02581e3bf8b4d5d935ca9a25/lua/avante/config.lua#L189

I'll open PR

**Comment by MathieuTuli** [comment]
+1

#363 should solve the img-clip

but it seems `lazy` is now required - you can solve that error by just installing lazy/having it as a dependency in your package manager

**Comment by yetone** [comment]
Can the latest version fix this issue?

**Comment by jmoudrik** [comment]
@yetone yeah, I believe it is "fixed" with #363, in a way that fixing the `img-clip` warn has suppressed the lazy warning as well.

I am running the Plug, lazy-less setup && currently no issues. I will be checking & will try to make sure it stays running.

**Comment by jmoudrik** [comment]
actually, I wanted to ask, @MathieuTuli 

> but it seems lazy is now required - you can solve that error by just installing lazy/having it as a dependency in your package manager

it seems where?

My understanding is that the "core" of this is that avante warns when img-clip is not installed (and it might mention lazy not being installed as well), but fixing the lazy hides the lazy warning (not sure about the dep checks tho too much).

**Comment by aarnphm** [comment]
lazy is not required, i include check a few places whenever we use lazy core logic?

Do you have screenshot of where the warning are?

**Comment by MathieuTuli** [comment]
it works if I don't install lazy or img-clip.

I can't seem to get img-clip working yet, I don't really have time to check this right now though.

For lazy, I can install it and it hides the warning, but then I get 
```lua
packer.nvim: Error running config for avante.nvim: .../pack/packer/start/avante.nvim/lua/avante/utils/init.lua:135: attempt to index upvalue 'Keys' (a nil value)
```

tbh I suspect this is a skill issue on my part not installing stuff right, I just don't have time right now to debug I'll check after work.

**Comment by MathieuTuli** [comment]
I've crudely installed `lazy.nvim` with packer just adding it as a dependency to `avante.nvim` - which I presume is just a bad idea overall as it doesn't setup lazy properly. So overall I think this is more a me/my setup issue than an avante issue, I'll be able to answer that more confidently later though

**Comment by aarnphm** [comment]
you shouldn't use a dependency manager to install another dependency manager.

**Comment by MathieuTuli** [comment]
agreed - we can ignore me in this thread

**Comment by aarnphm** [comment]
will close since it seems to me it is already resolved?
