### ISSUE TITLE
feat: custom base user prompt / other modes 

### ISSUE THREAD

**Issue by SiyuLiu0329** [yetone/avante.nvim#379]
Currently, the base user prompts specifically ask the LLM to edit code. It would be great to have other prompt options for explanation, search, analysis, documentation, test generation ...

Since the possibilities are endless, it would be good to give the user control by providing a `/custom-prompt ...` command. In the future, they could even store their prompts and telescope-select which one to use.

**Comment by aarnphm** [comment]
closed due to duplication of #254
