### ISSUE TITLE
Disable warning for `img-clip` through config

### ISSUE THREAD

**Issue by pratyushmittal** [yetone/avante.nvim#385]
Hey,

How can we disable warnings for `img-clip`? I don't want to use image support and don't want to install additional dependencies.

I tried adding `support_paste_from_clipboard = false` in `opts` but it does't disable the startup warning:

```
  {
    'yetone/avante.nvim',
    event = 'VeryLazy',
    opts = {
      support_paste_from_clipboard = false,
    }
```

**Comment by aarnphm** [comment]
when are you seeing this?

**Comment by aarnphm** [comment]
hopefully #388 fixes this

**Comment by pratyushmittal** [comment]
Thanks @aarnphm for looking into it so quickly.

The warning is still there. I think the `silent_warning` parameter is being considered only for `KEY` warning. It is not taken into account for `img-clip` warning.

**Comment by aarnphm** [comment]
am I missing something here?
https://github.com/yetone/avante.nvim/blob/61acd714ba08b961f055906e45592909387eae07/lua/avante/config.lua#L234 will check if img-clip is available or not. If not (in your case), then it called `warn`, but warn is a no op if debug=false

What is the output of `print(vim.inspect(require("avante.config").options))` (make sure to remove sensitive info if you have any in your vendor setup)

**Comment by coveres** [comment]
I'm also getting the warning when i open up neovim. Weird thing is `silent_warning` is set to true and `debug` is false but somehow still getting the warning message.

**Comment by coveres** [comment]
ok i think i know the issue, config.lua line 178 calls the `support_paste_image()` before the `silent_warning` is set, should be an easy fix.

**Comment by coveres** [comment]
Ok i know the issue `after/plugin/avante.lua` runs first, printing the `Config` within the file shows `options = {}` (no silent_warning) hence the check within the `warn' function fails.

**Comment by aarnphm** [comment]
I thought after/* will be run after plugins are being loaded?

**Comment by pratyushmittal** [comment]
Hey @aarnphm, it is still showing the warning.

Attaching a video of it:

https://github.com/user-attachments/assets/4e0d2599-35ee-4834-a16a-b72539a8d425

**Comment by aarnphm** [comment]
Can you try with #414 ?

**Comment by pratyushmittal** [comment]
Hey, I updated Lazy and tried it with follow config. It still show the warning.

```
  {
    'yetone/avante.nvim',
    event = 'VeryLazy',
    opts = {
      silent_warning = true,
      skip_warning = true,
      support_paste_image = false,
      paste_image = false,
    }
    ...,
```

The warning goes if I remove `event = 'VeryLazy'`. When removing `VeryLazy`, then passing nothing in `opts` also works.
