### ISSUE TITLE
bug: You must setup copilot with either copilot.lua or copilot.vim

### ISSUE THREAD

**Issue by franroa** [yetone/avante.nvim#390]
Hi, I am getting this error when adding the new copilot provider:

```
Failed to run `config` for avante.nvim
...e/nvim/lazy/avante.nvim/lua/avante/providers/copilot.lua:150: You must setup copilot with either copilot.lua or copilot.vim
```

Copilot is already active and working, though.
Do I need to do something special for configuring it?

Thank you in advance!

**Comment by aarnphm** [comment]
is there a `~/.config/github-copilot/hosts.json` available?

**Comment by yetone** [comment]
<img width="662" alt="image" src="https://github.com/user-attachments/assets/85e849e7-5ea3-447a-a974-db396be6e0b9">

https://github.com/yetone/avante.nvim#installation

Please add this dependency.
