### ISSUE TITLE
Content is not an image

### ISSUE THREAD

**Issue by noahgsolomon** [yetone/avante.nvim#408]
I get this error from img-clip when I paste into the chat box using avante

**Comment by aarnphm** [comment]
this seems like a bug on their end, because they are overwriting vim.paste.

This means that if the given content is just plaintext, users will see this error.

**Comment by aarnphm** [comment]
since #410, we will only supress this message on AvanteInput buffer, otherwise it will still fallback to their default behaviour of warning. 

It stems from here https://github.com/HakonHarnes/img-clip.nvim/blob/28a32d811d69042f4fa5c3d5fa35571df2bc1623/lua/img-clip/paste.lua#L23
