### ISSUE TITLE
Error while sending request with a selection of code lines: A maximum of 4 blocks with cache_control may be provided. Found 5.

### ISSUE THREAD

**Issue by lucaszweili** [yetone/avante.nvim#416]
I just installed the `avante` plugin on my LazyVim. First, it looks amazing but when trying to send API requests with a selection of code lines, I get the same error response:

```
🚨 Error: "API request failed with status 400. Body: '{\"type\":\"error\",\"error\":{\"type\":\"invalid_request_error\",\"message\":\"A maximum of 4 blocks with cache_control may be provided. Found 5.\"}}'"
```
<img width="1330" alt="Capture d’écran 2024-08-31 à 10 59 05" src="https://github.com/user-attachments/assets/0d8c6775-67a3-4e4b-8bdc-0cbd0f3bad50">

Thank you

**Comment by NeutronicMC** [comment]
Same issue here, just installed 20 minutes ago on v0.10.1 macos and am using the default config provided in README.md
