### ISSUE TITLE
bug: Can not submit question

### ISSUE THREAD

**Issue by yuchanns** [yetone/avante.nvim#422]
It seems that #407 introduces a bug that I'm not able to submit a question now.

I've tested in Linux and Windows

cc @aarnphm

**Comment by esezen** [comment]
I'm having the same issue. Downgrading to the previous commit resolves the issue. I'm getting the following error:
```
🚨 Error: "API request failed with status 400. Body: '{\"type\":\"error\",\"error\":{\"type\":\"invalid_request_error\",\"message\":\"tokenizer_id: Extra inputs are not permitted\"}}'"
```

**Comment by yetone** [comment]
@aarnphm Because your PR is a bit complex, I can't solve this problem right away. So to quickly fix it, I've temporarily rolled back your PR.
