### ISSUE TITLE
Edit functionality fails.

### ISSUE THREAD

**Issue by latkins** [yetone/avante.nvim#435]
I get the error 
```E5108: Error executing lua ...cal/share/nvim/lazy/avante.nvim/lua/avante/selection.lua:300: attempt to index field 'selection' (a nil value)
stack traceback:
        ...cal/share/nvim/lazy/avante.nvim/lua/avante/selection.lua:300: in function 'create_editing_input'
        ...m/.local/share/nvim/lazy/avante.nvim/lua/avante/init.lua:311: in function 'edit'
        [string ":lua"]:1: in main chunk
```

when attempting to use the edit functionality. The stacktrace points to the same line in both `V` and `v` mode, so `Utils.get_visual_selection_and_range()` may not be working correctly? I am far from a lua expert, but happy to help debug. 

![image](https://github.com/user-attachments/assets/71b40a67-0a3e-446b-9ce8-4f6705c50e9a)

**Comment by aarnphm** [comment]
are you on main? works for me


https://github.com/user-attachments/assets/6d5e0e4f-b108-4379-8d55-25192b8d85ef

**Comment by Tarquinen** [comment]
On this topic, edit changes more than just the selected code for me:
![image](https://github.com/user-attachments/assets/5fb1dfcc-d028-4986-b388-5d249fb08e70)
![image](https://github.com/user-attachments/assets/5d231d1e-7d5f-416f-a06b-6943e8911ee1)
Am I using it incorrectly?

**Comment by yetone** [comment]
> On this topic, edit changes more than just the selected code for me:在这个主题上，编辑更改不仅仅是为我选择的代码： ![image](https://private-user-images.githubusercontent.com/78942835/363444695-5fb1dfcc-d028-4986-b388-5d249fb08e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjA4NjMsIm5iZiI6MTcyNTE2MDU2MywicGF0aCI6Ii83ODk0MjgzNS8zNjM0NDQ2OTUtNWZiMWRmY2MtZDAyOC00OTg2LWIzODgtNWQyNDlmYjA4ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNDY4ZGRlMTZiYTMzYjAxM2MyOGMzMGUxZTFiNjA2NjFlMzI0NWZiNjk3MDI2NmNkZjBiZWVmNTdkMzU2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6wk6sybQWhVQ6OjliKcqIwXfCqJMYrXLd8tGuwICDU) ![image](https://private-user-images.githubusercontent.com/78942835/363444716-5d231d1e-7d5f-416f-a06b-6943e8911ee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjA4NjMsIm5iZiI6MTcyNTE2MDU2MywicGF0aCI6Ii83ODk0MjgzNS8zNjM0NDQ3MTYtNWQyMzFkMWUtN2Q1Zi00MTZmLWEwNmItNjk0M2U4OTExZWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmZjNzQzNTU1ZDJhZWEzOTFkMTNjM2IxNjQyZjE2YThlYzdmNTJiMTE5Yjg5MWYwYTI1YTdkYTc4MWFlMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G0_wAonLxRMVetmk__DwqTIOq9qTh-K3w9c1O-_SPq8) Am I using it incorrectly?是我使用方式不对吗？

The performance of OpenAI is very poor, it often doesn't follow instructions. I suggest using Claude only.

**Comment by latkins** [comment]
> are you on main? works for me

Yes, on `77d344d`. I tried triggering `get_visual_selection_and_range` with a function (which may be incorrect)

`:lua print(require('avante.utils').get_visual_selection_and_range())<CR>`

which gives `nil`. Presumably this means I have some conflicting settings somewhere that stop this working.

**Comment by latkins** [comment]
Ok it is definitely my problem. I have defined the shortcut via `whichkey` with
```        
      {
          mode = { "v" },
          { "<leader>ae", ":lua require('avante').edit()<CR>", desc = "Avante Edit" },
          { "<leader>ab", ":lua print(vim.fn.mode())<CR>"  },
      }
```
when I use `<leader>ab`, the mode reported is `n`, which causes `get_visual_selection_and_range()` to return `nil`, which then causes the error.

**Comment by latkins** [comment]
For anyone else who runs into this, this works:

`{ "<leader>ae", function() require('avante').edit() end, desc = "Avante Edit" },`

**Comment by Tarquinen** [comment]
> > On this topic, edit changes more than just the selected code for me:在这个主题上，编辑更改不仅仅是为我选择的代码： ![image](https://private-user-images.githubusercontent.com/78942835/363444695-5fb1dfcc-d028-4986-b388-5d249fb08e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjA4NjMsIm5iZiI6MTcyNTE2MDU2MywicGF0aCI6Ii83ODk0MjgzNS8zNjM0NDQ2OTUtNWZiMWRmY2MtZDAyOC00OTg2LWIzODgtNWQyNDlmYjA4ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNDY4ZGRlMTZiYTMzYjAxM2MyOGMzMGUxZTFiNjA2NjFlMzI0NWZiNjk3MDI2NmNkZjBiZWVmNTdkMzU2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6wk6sybQWhVQ6OjliKcqIwXfCqJMYrXLd8tGuwICDU) ![image](https://private-user-images.githubusercontent.com/78942835/363444716-5d231d1e-7d5f-416f-a06b-6943e8911ee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjA4NjMsIm5iZiI6MTcyNTE2MDU2MywicGF0aCI6Ii83ODk0MjgzNS8zNjM0NDQ3MTYtNWQyMzFkMWUtN2Q1Zi00MTZmLWEwNmItNjk0M2U4OTExZWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmZjNzQzNTU1ZDJhZWEzOTFkMTNjM2IxNjQyZjE2YThlYzdmNTJiMTE5Yjg5MWYwYTI1YTdkYTc4MWFlMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G0_wAonLxRMVetmk__DwqTIOq9qTh-K3w9c1O-_SPq8) Am I using it incorrectly?是我使用方式不对吗？
> 
> The performance of OpenAI is very poor, it often doesn't follow instructions. I suggest using Claude only.

Nice this change works. Any idea how curser gets theirs to work with openai? Maybe a different prompt depending on the model?

**Comment by yetone** [comment]
> > > On this topic, edit changes more than just the selected code for me:在这个主题上，编辑更改不仅仅是为我选择的代码： ![image](https://private-user-images.githubusercontent.com/78942835/363444695-5fb1dfcc-d028-4986-b388-5d249fb08e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjA4NjMsIm5iZiI6MTcyNTE2MDU2MywicGF0aCI6Ii83ODk0MjgzNS8zNjM0NDQ2OTUtNWZiMWRmY2MtZDAyOC00OTg2LWIzODgtNWQyNDlmYjA4ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNDY4ZGRlMTZiYTMzYjAxM2MyOGMzMGUxZTFiNjA2NjFlMzI0NWZiNjk3MDI2NmNkZjBiZWVmNTdkMzU2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6wk6sybQWhVQ6OjliKcqIwXfCqJMYrXLd8tGuwICDU) ![image](https://private-user-images.githubusercontent.com/78942835/363444716-5d231d1e-7d5f-416f-a06b-6943e8911ee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjA4NjMsIm5iZiI6MTcyNTE2MDU2MywicGF0aCI6Ii83ODk0MjgzNS8zNjM0NDQ3MTYtNWQyMzFkMWUtN2Q1Zi00MTZmLWEwNmItNjk0M2U4OTExZWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmZjNzQzNTU1ZDJhZWEzOTFkMTNjM2IxNjQyZjE2YThlYzdmNTJiMTE5Yjg5MWYwYTI1YTdkYTc4MWFlMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G0_wAonLxRMVetmk__DwqTIOq9qTh-K3w9c1O-_SPq8) Am I using it incorrectly?是我使用方式不对吗？
> > 
> > 
> > The performance of OpenAI is very poor, it often doesn't follow instructions. I suggest using Claude only.
> 
> Nice this change works. Any idea how curser gets theirs to work with openai? Maybe a different prompt depending on the model?

Cursor has done a lot of prompt engineering work, and these prompts are all closed-source. They even have their own trained models for assistance, so they cannot be compared on the same level.
