### ISSUE TITLE
LibreSSL error

### ISSUE THREAD

**Issue by luuk00101** [yetone/avante.nvim#443]
Guys I just got this error, no idea what happened. Didn't change anything since morning.

message = 'post https://api.anthropic.com/v1/messages - curl error exit_code=56 stderr={ "curl: (56) LibreSSL SSL_read: LibreSSL/3.3.6: error:1404C42E:SSL routines:ST_OK:tlsv1 alert protocol version, errno 0" }',
  stderr = '{ "curl: (56) LibreSSL SSL_read: LibreSSL/3.3.6: error:1404C42E:SSL routines:ST_OK:tlsv1 alert protocol version, errno 0" }'

**Comment by cescobaz** [comment]
Hello @luuk00101 , I have the same issue, how did you solve it?
Many thanks!
