### ISSUE TITLE
avante stop generating and freezes

### ISSUE THREAD

**Issue by ScaferuZ** [yetone/avante.nvim#444]
i dont know if its an issue with my hardware or avante itself. but, sometimes, when I was prompting, claude would just stop responding and I had to close my tmux server because I can't do anything on the nvim window. after I start the server again, and tried to prompt again, it shows this error
![image](https://github.com/user-attachments/assets/1bffa310-fffe-49a7-a2ad-aeab63f3f2d4)

**Comment by yetone** [comment]
Claude is overloaded.

**Comment by oschrenk** [comment]
Same issue.

Is there a way to not crash and freeze nvim but instead show an error message or close the avante window?


My current workflow now is killing nvim and restart the process?

**Comment by aarnphm** [comment]
Hmm there is a bug with suggestion timer atm to cause overloading. I will look into this during the weekend or so

**Comment by V4G4X** [comment]
The cause being overloaded can't be right.  
I just put in my first 10 dollars.  

Fired up avante and got this on my first message.

**Comment by srgsanky** [comment]
Similar bug report https://github.com/yetone/avante.nvim/issues/598

**Comment by srgsanky** [comment]
I saw this error for the first time today (10AM PST on a Friday). It was temporary and resolved itself after some time.

**Comment by aarnphm** [comment]
I think this is just API up time, I saw it this morning too, then not this afternoon
