### ISSUE TITLE
Highlight group bold setting is not inherited

### ISSUE THREAD

**Issue by cfal** [yetone/avante.nvim#448]
i have this in my config:
```
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#444444", bg = "#000000", bold = false });
vim.api.nvim_set_hl(0, "DiffText", { fg = "#444444", bg = "#1c1c1c", bold = false });
```

but the diffs still show up as bold in my terminal.

this change fixed it, although i'm unsure if it's the correct approach: https://github.com/cfal/avante.nvim/commit/ac56384c4c354353cff1928c4958df2e7148674a

**Comment by aarnphm** [comment]
#451

**Comment by aarnphm** [comment]
them it seems like a neovim bug to me. how is bold = false results bold to nil? shouldn't it be just bold=false?
