### ISSUE TITLE
Allow not displaying emojis

### ISSUE THREAD

**Issue by cfal** [yetone/avante.nvim#449]
the emojis in the various messages can cause layout issues when used in a terminal neovim instance in some terminal emulators. i'm seeing this occur frequently especially in tmux and requires a `reset` to fix. perhaps there are other fixes, but removing emojis from messages resolved the problem: https://github.com/cfal/avante.nvim/commit/efa5cece8c3f13bf4b4d603961675fac192dc212

it would be great if this was configurable.

**Comment by JoseConseco** [comment]
I was wondering why my output from awante sidebar look all messed up:
![image](https://github.com/user-attachments/assets/7d4bc581-cadd-46b2-a9f5-079f3b5b964d)

So this is due emojis?

**Comment by aarnphm** [comment]
hmm strange since these are already ascii. but I'm also fine with removing this.
