### ISSUE TITLE
Thoughts on optionally using open buffers as context? 

### ISSUE THREAD

**Issue by culda** [yetone/avante.nvim#456]
If not done already I could have a go at implementing.

This morning I I had a case where I had some functions in a file and I want to create an object with all of them.
I want to tell it to autocomplete but I need the a.go file in my context

obj := options(WithX(), WithY(), WithZ())

//a.go
func WithX()
func WithY()
func WithZ()

**Comment by aarnphm** [comment]
we are working on context-aware workspace, similar to https://github.com/yetone/avante.nvim/issues/76

**Comment by aarnphm** [comment]
If you have any suggestion feel free to help work on this
