### ISSUE TITLE
Make sure to build avante (missing avante_templates) stack traceback

### ISSUE THREAD

**Issue by noahgsolomon** [yetone/avante.nvim#485]
I get this error when trying to use avante.nvim on my mac. on my linux machine it works fine. My avante config is the exact same as the one provided in the readme

E5108: Error executing lua: ...hs/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:59: Make sure to build avante (missing avante_templates)
stack traceback:
	[C]: in function 'error'
	...s/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:75: in function 'get'
	...hs/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:59: in function 'stream'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1260: in function 'handle_submit'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1313: in function <...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1303>

**Comment by MichaelM3** [comment]
if you're using `build = ":AvanteBuild source=false"` like I am, I had same issue. My `cargo` version was `1.72` after running `rustup update` cargo was updated to `1.80` and then `AvanteBuild` works and builds binary correctly.

**Comment by yetone** [comment]
This issue has been resolved, see details: https://github.com/yetone/avante.nvim/issues/474
