### ISSUE TITLE
Specify GITHUB_TOKEN `action:scope`

### ISSUE THREAD

**Issue by NihadBadalov** [yetone/avante.nvim#492]
> For prebuilt binary, one must set the following GITHUB_TOKEN in given shell (instruction for creating PAT is [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)) (requires action:scope)

What action and what scope?

**Comment by luxus** [comment]
i guess its workflows.. at least that works :D
