### ISSUE TITLE
Vim Plug installation failed

### ISSUE THREAD

**Issue by jikkuatwork** [yetone/avante.nvim#495]
Post installation its showing this error:

```
Error detected while processing function <SNR>4_lod_cmd:
line    3:
E492: Not an editor command: AvanteAsk
Press ENTER or type command to continue
```

My [init.lua](https://rentry.co/init-lua)

**Comment by aarnphm** [comment]
just remove AvanteAsk for now. I'm not entirely sure how lazy loading works on vim-plug

**Comment by jikkuatwork** [comment]
Sorry, can you explain? How can I remove `AvanteAsk`? Now, <leader>aa is not triggering.

**Comment by aarnphm** [comment]
```vim
Plug('yetone/avante.nvim', {['branch'] = 'main', ['do'] = function() require('avante.api').build() end})
```

**Comment by jikkuatwork** [comment]
Did it, but now nothing works. leader aa doesn't work.

**Comment by aarnphm** [comment]
Did you call `setup()`? vim-plug doesn't invoke setup automatically.

**Comment by aarnphm** [comment]
See the lua setup section.

**Comment by jikkuatwork** [comment]
Thanks a ton, finally got it working!
