### ISSUE TITLE
HTTP 401 error with gemini provider's tokenizer (gemma-2b)

### ISSUE THREAD

**Issue by meinside** [yetone/avante.nvim#499]
This error occurs with gemini:

```
Error executing vim.schedule lua callback:
called `Result::unwrap()` on an `Err` value: 
RequestError(Status(401, Response[status: 401, status_text: Unauthorized, url: https://huggingface.co/google/gemma-2b/resolve/main/tokenizer.json]))
```

I see codes which check for an environment variable named `HF_TOKEN`, but it is not used elsewhere.

**Comment by aarnphm** [comment]
Hi there, gemma/2b is a gated models, so you must have access to the repo on huggingface in order to use the tokenizer.

**Comment by meinside** [comment]
I exported my huggingface's token (with the required access to gemma models), but it seems not picked up by the tokenizer.

**Comment by meinside** [comment]
I tested with my huggingface's token:

```bash
$ curl "https://huggingface.co/google/gemma-2b/resolve/main/tokenizer.json" -H "Authorization: Bearer $HF_TOKEN"
```

then I got a url which redirects to the tokenizer json file:

```
Found. Redirecting to https://some-url-to-tokenizer-json-with-many-many-query-params
```

so I think the token is valid. Is there anything else I can check?

**Comment by aarnphm** [comment]
I will just gpt-4o for now, until I implement token counting will revisit this

**Comment by meinside** [comment]
Ok, thanks!
