### ISSUE TITLE
How do i start a new chat in the same file?

### ISSUE THREAD

**Issue by SalamanderXing** [yetone/avante.nvim#516]
In a file once I toggled the sidebar with leader-aa and chatted, I'd like to start a new chat. Is this possible?

**Comment by aarnphm** [comment]
Wdym? Are you asking for cleaning chat history?

You can use it with `/clear`.

**Comment by SalamanderXing** [comment]
I see, yes that's kind of what I meant. 
t would be nice to be able to navigate previous chats as well, as you can do with cursor (access previously cleared chats) and continue a previous chat.

Amazing project btw so glad I can keep using nvim and have the latest llm integrated in it :)

**Comment by aarnphm** [comment]
feel free to propose something. I think this is best for telescope integration or sth.
