### ISSUE TITLE
Chat with selected code bug

### ISSUE THREAD

**Issue by luuk00101** [yetone/avante.nvim#519]
I just tried to select a code and chat with it. A bug popped up immediately after submitting my question. Here's the error:

<img width="1340" alt="image" src="https://github.com/user-attachments/assets/18c54666-72dc-431b-9c12-3d813d4538dd">

It now persists accross all the features of the plugin. I can't use it

**Comment by aarnphm** [comment]
hi there, can you provide with neovim version, distribution, minimal config?

**Comment by luuk00101** [comment]
Hey there @aarnphm! 

Thank you for reaching out! I just figured out the problem - the router somehow blocked the connection to the Anthropic servers and the code probably went into a loop trying to get the completion. I switched my internet connection method and the issue resolved. 

Thank you once again and sorry for wasting your time. Together with other contributors, you're doing a great job on the project. Hope to contribute sometime in the future.
