### ISSUE TITLE
[bug] still: `Make sure to build avante (missing avante_templates)` on ask

### ISSUE THREAD

**Issue by jmoudrik** [yetone/avante.nvim#520]
Linux, latest commit 2b89f0d529add18fd39cee37073c17c8179b2358 (the same behavior with `v0.0.2`)
- Plug setup, default config
- `cd ~/.local/share/nvim/plugged/avante.nvim`
   - `build.sh` runs fine && downloads stuff
   - `build` dir now has 2 .so libs, `avante_templates.so  avante_tokenizers.so`
- but still getting the error:
```
E5108: Error executing lua: ....local/share/nvim/plugged/avante.nvim/lua/avante/llm.lua:59: Make sure to build avante (missing avante_templates)                                     
stack traceback:                                                                                                                                                                              
        [C]: in function 'error'                                                                                                                                                              
        ...local/share/nvim/plugged/avante.nvim/lua/avante/path.lua:75: in function 'get'                                                                                                     
        ....local/share/nvim/plugged/avante.nvim/lua/avante/llm.lua:59: in function 'stream'                                                                                                  
        ...al/share/nvim/plugged/avante.nvim/lua/avante/sidebar.lua:1266: in function 'handle_submit'                                                                                         
        ...al/share/nvim/plugged/avante.nvim/lua/avante/sidebar.lua:1319: in function <...al/share/nvim/plugged/avante.nvim/lua/avante/sidebar.lua:1309>
```

Doing something wrong?

**Comment by aarnphm** [comment]
is this vim-plug?

**Comment by jmoudrik** [comment]
yes, but I only used it for "checkout"; I am running the build steps && checking state manually in the `.local/...` dir, so imo not an issue of plug

**Comment by jmoudrik** [comment]
Or is it some directory issue maybe?

**Comment by jmoudrik** [comment]
Specifically, inspecting the `module` (with assert at L138) loaded here: https://github.com/yetone/avante.nvim/blob/b8c484148a4fc93cecd48e3f061ee5dea63c618a/lua/avante/path.lua#L135

I get:
```
Error executing vim.schedule lua callback: ...local/share/nvim/plugged/avante.nvim/lua/avante/path.lua:140: "module 'avante_templates' not found:
	no field package.preload['avante_templates']
	no file './avante_templates.lua'
	no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/avante_templates.lua'
	no file '/usr/local/share/lua/5.1/avante_templates.lua'
	no file '/usr/local/share/lua/5.1/avante_templates/init.lua'
	no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/avante_templates.lua'
	no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/avante_templates/init.lua'
	no file './avante_templates.so'
	no file '/usr/local/lib/lua/5.1/avante_templates.so'
	no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/avante_templates.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'"
```

so it is a dir issue.

**Comment by jmoudrik** [comment]
A working workaround is to move the `.so` files to `/usr/local/lib/lua/5.1/`. But I think there might be a better way to add the build dir into "path" or wherever lua looks for stuff. Gonna try && fix this.

**Comment by aarnphm** [comment]
> For avante.tokenizers and templates to work, make sure to call require('avante_lib').load() somewhere when entering the editor. We will leave the users to decide where it fits to do this, as this varies among configurations. (But we do recommend running this after where you set your colorscheme)

Did you call this somewhere?

**Comment by kirchik95** [comment]
Updated avante to latest and getting same error

**Comment by aarnphm** [comment]
can you set version = false to lazy to make sure you are pulling the latest version?

also can you check if the build directory under `~/.local/share/nvim/lazy/avante.nvim` is built correctly? 

We have updated the build instruction to make it work better with lazy.

**Comment by kirchik95** [comment]
> can you set version = false to lazy to make sure you are pulling the latest version?
> 
> also can you check if the build directory under `~/.local/share/nvim/lazy/avante.nvim` is built correctly?
> 
> We have updated the build instruction to make it work better with lazy.

I've set `lazy = false` and also add `build = "make"` from README.md
And now it's working again, thank you @aarnphm

**Comment by YuCao16** [comment]
@aarnphm Hi, thanks for the great plugin.

I have a similar issue, however, with a different reason, when I run `lua require("avante_templates")`, I got this error:
```
E5108: Error executing lua error loading module 'avante_templates' from file '/data/home/acw759/.local/share/nvim/site/lazy/avante.nvim/lua/../build/avante_templates.so':
        /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /data/home/acw759/.local/share/nvim/site/lazy/avante.nvim/lua/../build/avante_templates.so)
```
My machine's GLIBC version is 2.27, do you have any solution for this?

**Comment by rijacklin** [comment]
`build = "make"` is providing an arm binary on Mac OS. For Intel macs, need to use `build = "make BUILD_FROM_SOURCE=true"`.

**Comment by aarnphm** [comment]
hmm if you want to have binary for intel mac feel free to contribute to the release CI

**Comment by krissen** [comment]
> `build = "make"` is providing an arm binary on Mac OS. For Intel macs, need to use `build = "make BUILD_FROM_SOURCE=true"`.

This should be mentioned in the README.
