### ISSUE TITLE
bug: submit hint overlaps wrapped prompts

### ISSUE THREAD

**Issue by will-lynas** [yetone/avante.nvim#530]
### Describe the bug

When wrapping is set to true on the prompt window and a line gets wrapped, the submit virtual text covers the prompt. It stays on the second line rather than being pushed to the bottom.
<img width="448" alt="image" src="https://github.com/user-attachments/assets/9fc60e6e-45dc-478f-8188-a12bd36ff53d">
<img width="452" alt="image" src="https://github.com/user-attachments/assets/ae54353c-f8ed-4ca3-86d5-9e769b620ada">

### Environment

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```
macOS

**Comment by will-lynas** [comment]
What do you think about this?

<img width="449" alt="image" src="https://github.com/user-attachments/assets/b6bb1b98-0a4d-4293-9f73-9eb98aeb7251">

**Comment by aarnphm** [comment]
I think it is too sparse.

**Comment by will-lynas** [comment]
Fair. How about this then ...

Single line:

<img width="448" alt="image" src="https://github.com/user-attachments/assets/692f62c6-ae59-4938-a5a4-25265fcfb7de">

Multi line (wrapped):

<img width="447" alt="image" src="https://github.com/user-attachments/assets/50a02326-bc65-4d81-b90f-1f09e9d81ad0">

Multi line (not wrapped):

<img width="448" alt="image" src="https://github.com/user-attachments/assets/a6942b11-176e-43e9-a892-d6fd42e78276">

When the window is full, the hint moves to the top so you can see what you are typing:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/aca98173-bd5d-4fa2-9882-0184128a8725">

**Comment by will-lynas** [comment]
Follow up:
If that was the only reason to turn off wrapping be default, can it now be enabled?

**Comment by aarnphm** [comment]
there is a config called windows.wrap

**Comment by aarnphm** [comment]
oh actually I think the reason for turning wrapping off is to support pasting
