### ISSUE TITLE
feature: groq cloud API support

### ISSUE THREAD

**Issue by Vinni-Cedraz** [yetone/avante.nvim#532]
### Feature request

Based on the documentation, it appears that support is currently available for Claude, OpenAI, Azure, Gemini, Cohere, and Copilot. Unfortunately, none of these options are free to use. It is possible that support for other platforms exists but is not documented. If this is not the case, I would like to request the addition of support for Groq Cloud, which is completely free, extremely fast, and utilizes LLaMA

### Motivation

avante.nvim and neovim itself are both open source and free, so it makes sense to make it compatible with the biggest free and open source llm alternative: groq could with llama.

**Comment by aarnphm** [comment]
check readme for reasoning and wiki
