### ISSUE TITLE
feature: make build optional

### ISSUE THREAD

**Issue by YuCao16** [yetone/avante.nvim#534]
### Feature request

Since commit `054695cc`, `build` seems no longer optional, it would be great to bring this option back.

### Motivation

I have to code on a old server with GLIBC2.27, however, execute `avante_template` (excute `lua require("avante_templates")` requires at least GLIBC 2.29:
```
E5108: Error executing lua error loading module 'avante_templates' from file '/data/home/acw759/.local/share/nvim/site/lazy/avante.nvim/lua/../build/avante_templates.so':
        /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /data/home/acw759/.local/share/nvim/site/lazy/avante.nvim/lua/../build/avante_templates.so)
```

**Comment by aarnphm** [comment]
We can bring back pure lua string support, but it seems like too much of work and debt atm.

bringing support avanterules means it will require some tradeoff. To support jinja (in which is a pretty popular templating engine and well known amongst python community), therefore it is sensible to me.

If you found any sort of jinja-comparable implementation in lua happy to add support for that case.

seems like glibc 2.27 is released on 2018, which is north of 6 years from now. idk is there any restriction with upgrading from your end?

**Comment by YuCao16** [comment]
> We can bring back pure lua string support, but it seems like too much of work and debt atm.
> 
> bringing support avanterules means it will require some tradeoff. To support jinja (in which is a pretty popular templating engine and well known amongst python community), therefore it is sensible to me.
> 
> If you found any sort of jinja-comparable implementation in lua happy to add support for that case.
> 
> seems like glibc 2.27 is released on 2018, which is north of 6 years from now. idk is there any restriction with upgrading from your end?

Hi @aarnphm , 

Thanks for your reply, and this amazing plugin. I totally understand that is too much of work to maintain two "template" sort of thing. 

However, from my view, a lot of servers are still running very old compilers, especially HPC, and they won't be updated shortly because it's too costly to do so. I think the reason many users actually use neovim is also because they need to work on very old machines. I can't use cursor at the moment either, because the server I'm using doesn't meet the minimum requirements for cursor either. 

So it looks like I may be stuck with commit 054695cc at the moment...

**Comment by yetone** [comment]
> I think the reason many users actually use neovim is also because they need to work on very old machines. I can't use cursor at the moment either, because the server I'm using doesn't meet the minimum requirements for cursor either.

@YuCao16 Thank you for the feedback. We were not aware of this before, and it is indeed very important. We will pay special attention to this aspect in our future iterations.

**Comment by YuCao16** [comment]
> > I think the reason many users actually use neovim is also because they need to work on very old machines. I can't use cursor at the moment either, because the server I'm using doesn't meet the minimum requirements for cursor either.
> 
> @YuCao16 Thank you for the feedback. We were not aware of this before, and it is indeed very important. We will pay special attention to this aspect in our future iterations.

Thanks @yetone , feel free to contact me if you need to run some test on old server Lol

**Comment by yetone** [comment]
The glibc version of the release assets for avante prebuild is now 2.17.

**Comment by yetone** [comment]
@YuCao16 It looks like this issue can be closed. If there are any problems, you can provide feedback again.

**Comment by YuCao16** [comment]
> @YuCao16 It looks like this issue can be closed. If there are any problems, you can provide feedback again.

Yes, I just tried, and everything works as expected. Thanks!
