### ISSUE TITLE
feature: separate prompt for questions where no code generation is required

### ISSUE THREAD

**Issue by will-lynas** [yetone/avante.nvim#536]
### Feature request

Add a separate plugin prompt that does not ask LLM to generate any code.

Not sure how this would work. Different keybind to open a different type of sidebar? Multiple modes in the sidebar that can be toggled between?

### Motivation

Often I find myself asking questions about the codebase without wanting any changes. The plugin prompt tends to force the LLMs to generate code even when it makes no sense to do so.

**Comment by will-lynas** [comment]
e.g.
<img width="457" alt="image" src="https://github.com/user-attachments/assets/22460e7e-7e5d-42ca-ba64-53eb05db4aca">

**Comment by aarnphm** [comment]
there is a ask variable in the templates, https://github.com/yetone/avante.nvim/blob/8c021f36913048b9f1d00a8839ec44e9b3918033/lua/avante/templates/planning.avanterules#L10.

So we can pass in this option in AvanteAsk similar to position=right or position=left

**Comment by aarnphm** [comment]
https://github.com/yetone/avante.nvim/blob/8c021f36913048b9f1d00a8839ec44e9b3918033/lua/avante/llm.lua#L63

**Comment by will-lynas** [comment]
So its set up for it, but not used at the moment?

I quite like the toggling idea, so I'll have a go at that.

Wheres a good place to display the current mode / hint to change the mode? In a floating window like the submit hint?

**Comment by aarnphm** [comment]
See https://github.com/yetone/avante.nvim/blob/8c021f36913048b9f1d00a8839ec44e9b3918033/lua/avante/init.lua#L40 for example.

**Comment by aarnphm** [comment]
#541 now support with 

`AvanteAsk ask=false`. I will probably add a quick command `AvanteChat` which is an alias for this.

**Comment by aarnphm** [comment]
#542 add AvanteChat.
