### ISSUE TITLE
AvanteAsk  no working

### ISSUE THREAD

**Issue by diazmanne** [yetone/avante.nvim#545]
When running testing  
<img width="545" alt="Screenshot 2024-09-05 at 18 01 33" src="https://github.com/user-attachments/assets/829c60e9-6ef6-4e67-b7f6-367c0cfdd951">

<img width="1440" alt="Screenshot 2024-09-05 at 17 56 35" src="https://github.com/user-attachments/assets/322b64de-c76f-421e-8879-190bd64b93c2">

**Comment by aarnphm** [comment]
do you have credits?

**Comment by theesfeld** [comment]
make sure your cursor is in the right window for the action you are trying to perform

**Comment by diazmanne** [comment]
@aarnphm , Im using Claude , and Im using the free model, I was expecting to setup first and then buy credits.
@theesfeld it is on the right, but it seems when i run a lazyVim :checkhealt i have this :

Could you give me a hand to get setup, please 

<img width="1414" alt="Screenshot 2024-09-07 at 14 39 51" src="https://github.com/user-attachments/assets/62e8909e-52a1-4827-ab63-fe829476a6b8">

**Comment by theesfeld** [comment]
install luarocks 
what OS are you using

**Comment by aarnphm** [comment]
Hi please don't ping the maintainers https://github.com/yetone/avante.nvim/issues/459

**Comment by aarnphm** [comment]
can you share the reproducible here?
