### ISSUE TITLE
bug: Error when sending ask

### ISSUE THREAD

**Issue by tokisakiyuu** [yetone/avante.nvim#547]
### Describe the bug

<img width="1440" alt="2024-09-06 13 56 43" src="https://github.com/user-attachments/assets/c2dca75c-d593-431f-b4bf-e729121f28ce">

### Error
```
E5108: Error executing lua: ...ng/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:60: Make sure to build avante (missing avante_templates)
stack traceback:
	[C]: in function 'error'
	...g/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:75: in function 'get'
	...ng/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:60: in function 'stream'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1273: in function 'handle_submit'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1327: in function <...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1317>

```

### Environment

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202

**Comment by jmoudrik** [comment]
do you install via lazy or plug or ?

if plug, you need `require('avante_lib').load() `

also, you can check that the `~/.local/share/nvim/..../avante.nvim/build` has 2 .so objects (on linux), or similarly that the dir where avante plugin is installed on windows has 2 dlls. if not, run make in the plugin dir (and check that you install the plugin correctly as per readme, because all this should happen automatically).

**Comment by jmoudrik** [comment]
for lazy, see https://github.com/yetone/avante.nvim/issues/544

**Comment by tokisakiyuu** [comment]
> for lazy, see #544

Thanks for your help.

Now I'm over that error and got a new error:

```
Error executing luv callback:
...g/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:19: E5560: nvim_buf_get_name must not be called in a lua loop callback
stack traceback:
	[C]: in function 'nvim_buf_get_name'
	...g/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:19: in function 'filename'
	...g/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:36: in function 'get'
	...g/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:53: in function 'save'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1270: in function 'on_complete'
	...ng/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:150: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:241: in function '_shutdown'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:48: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:39>

```

**Comment by CrustyCode** [comment]
I'm using plugged, and this fixed it for me:
```
cd ~/.config/nvim/plugged/avante.nvim
make
```
> if plug, you need `require('avante_lib').load() `

**Comment by aarnphm** [comment]
you shouldn't use `lazy=True` here. Otherwise you have to gated through `cmd` or `keys` lazy.

Check the readme for latest build
