### ISSUE TITLE
Copilot: Regarding Your Copilot Access

### ISSUE THREAD

**Issue by leCoq42** [yetone/avante.nvim#557]
Hi,

Since I started using avante.nvim with copilot as a back-end I got the following message twice from github:

"On behalf of the GitHub Security team, I want to first extend our gratitude for your continued use of GitHub and for being a valued member of the GitHub community.

Recent activity on your account caught the attention of our abuse-detection systems. This activity included use of Copilot that was indicative of scripted interactions or of an otherwise deliberately unusual or strenuous nature. While we have not yet restricted Copilot access for your account, further anomalous activity could result in a temporary suspension of your Copilot access.

While I’m unable to share specifics on rate limits, we prohibit all use of our servers for any form of excessive automated bulk activity, as well as any activity that places undue burden on our servers through automated means. Please refer to our Acceptable Use Policies on this topic: https://docs.github.com/site-policy/acceptable-use-policies/github-acceptable-use-policies#4-spam-and-inauthentic-activity-on-github.

Please also refer to our Terms for Additional Products and Features for GitHub Copilot for specific terms: https://docs.github.com/site-policy/github-terms/github-terms-for-additional-products-and-features#github-copilot.

Sincerely,
GitHub Security"

Did anyone else receive this? I have been using copilotchat.nvim without a problem for the past months. So I'm suprised that I get this message since I've started using avante.

**Comment by aarnphm** [comment]
are you using with suggestion on? YOu should disable suggestion for now.

**Comment by leCoq42** [comment]
I use the default config only with copilot specified as the provider in opts.

**Comment by jsongerber** [comment]
I just got this email too. I used suggestion 5min and disabled it because the debounce timeout was too high and not configurable.
I will comment back if I ever get a follow up (or ban) from GitHub with suggestion disabled

**Comment by aarnphm** [comment]
Hmm this is strange, since I have also been using copilot and yet to see this form github

**Comment by turnabout** [comment]
I also got this. I just installed this plugin yesterday and played around with it for maybe 5 minutes, then got the same email today. I've been using Copilot for a year+ and never had this issue before. I used the default config as well.

**Comment by aarnphm** [comment]
Can you disable suggestion for now?

**Comment by jsongerber** [comment]
> I just got this email too. I used suggestion 5min and disabled it because the debounce timeout was too high and not configurable.
> I will comment back if I ever get a follow up (or ban) from GitHub with suggestion disabled

Confirming that I disabled suggestions two weeks ago and I didn't get any emails or ban from GitHub Copilot

**Comment by pedrorosa-dev** [comment]
I activated the suggestion feature and used it for 1 minute. Could this be the reason I received this notice in my email? Can someone confirm this, as I would like to continue using Avante.

**Comment by aarnphm** [comment]
yes, suggestion is currenlty debounce every 100 ms, which might trigger the error.

For now please turn off suggestion, we are working on a fix.

**Comment by ALX99** [comment]
Probably same issue as https://github.com/zbirenbaum/copilot-cmp/issues/117

**Comment by benjah13** [comment]
@aarnphm  what part of the configuration are you disabling to turn off the suggestions ? auto_suggestions default value is already false and i did received that email

**Comment by jsongerber** [comment]
> @jsongerber @aarnphm what part of the configuration are you disabling to turn off the suggestions ? auto_suggestions default value is already false and i did received that email

Yes I had to enable it, it's disabled by default. I asked to the GitHub support why I got this email and they would not tell me, only that I should use copilot.vim as this is the only supported client for vim/neovim. I'm still using the avante chat and copilot.lua suggestions and did not receive others emails.

**Comment by greyHairChooseLife** [comment]
I got the same email from the github. It has been less than 24 hrs with this plugin.

Something weird is that I didn't touch any default config but only `auto_suggestions_provider to copilot`. 

I thought it would be okay with the default config below:

```lua
    auto_suggestions = false, -- Experimental stage
```

But I was wrong.

**Comment by benjah13** [comment]
@greyHairChooseLife  hey ! I saw your change switching suggestions to Claude. I did the exact same change in my config... Resulting in a second email from Github a few hours later.... So far i will have to stop using avante until it's fixed..

**Comment by aarnphm** [comment]
I only get this email when I used copilot.lua

idk if this is related to avante.nvim at all

when I use supermaven, everything seems fine

**Comment by benjah13** [comment]
FYI, i contacted the Github support regarding this issue, and received the following response 

```
Hi benjah13,
 
Thanks for contacting GitHub Support and for providing us with more info regarding your Copilot usage!
 
There seems to be an error on the automated notification regarding Copilot access and usage which should be fixed by now.
 
You should receive another notification correcting the initial notification you have received. If this isn't the case, please let me know.
 
Feel free to reach out if there's anything else I can help you with. :)
 
Cheers,
Nix
GitHub Support Engineer
 
```
Let's see if we receive that correction email 👍

**Comment by aarnphm** [comment]
Thanks for reaching out to them ben

**Comment by benjah13** [comment]
i just received a correction email from them 😭 

```
Hi benjah13,
 
Hope all is well! I just wanted to follow-up with you.
 
I've discussed this internally with our team and they've confirmed that the warning notification you received is legitimate.
 
Based on investigation, token retrieval by the third party plugin avante.nvim is placing excessive burden on Copilot infrastructure.
 
Continued usage of the plugin comes at the risk of flagging by GitHub abuse detection tooling
 
Hope this helps clear things out. Feel free to reach out if there's anything else I can help you with!
```

**Comment by aarnphm** [comment]
sg, let me investigate this

**Comment by aarnphm** [comment]
I suspect https://github.com/yetone/avante.nvim/blob/3f947f8deb31af42bc3a7280c3d0d57763565222/lua/avante/providers/copilot.lua#L127

with `parse_curl_args` calling `refresh_tokens` too many times if users send consecutive messages

**Comment by leCoq42** [comment]
> I suspect
> 
> https://github.com/yetone/avante.nvim/blob/3f947f8deb31af42bc3a7280c3d0d57763565222/lua/avante/providers/copilot.lua#L127
> 
> with `parse_curl_args` calling `refresh_tokens` too many times if users send consecutive messages

The problem seems to be in copilot-cmp, see: https://github.com/yetone/avante.nvim/issues/557#issuecomment-2408934454

But the maintainer of that project doesn't seem to be very responsive unfortunately.. so hopefully your fix, stops people from receiving warmings/ getting banned.
