### ISSUE TITLE
bug: can't seem change the highlight group of the "submit" hint

### ISSUE THREAD

**Issue by qdbp** [yetone/avante.nvim#563]
### Describe the bug

I am working on a light color scheme and it looks like the "submit" hint (black in screenshot) in the avante edit window simply cannot be themed.

![image](https://github.com/user-attachments/assets/d50a3d30-953c-4ca7-9ef7-43fac5e2a1b5)

The code implies it's `NormalFloat`, but for me that is set correctly.

I am also unable to find this exact dark-grey-on-black highlight group anywhere in the highlights dump, suggesting this is something hardcoded

### To reproduce

Try changing any relevant highlight groups such as NormalFloat. Look for any highlight groups that match what is seen there (the black hint) and find nothing.

### Expected behavior

Can change the black hint to the surrounding background.

```
### Environment

NVIM v0.10.1

{
  "Colorizer": { "branch": "master", "commit": "7db0e0dd8adfccab35655f5b6db805caa0fef49a" },
  "Comment.nvim": { "branch": "master", "commit": "e30b7f2008e52442154b66f7c519bfd2f1e32acb" },
  "LuaSnip": { "branch": "master", "commit": "03c8e67eb7293c404845b3982db895d59c0d1538" },
  "avante.nvim": { "branch": "main", "commit": "7532e590d28c6fffe88aa17ba6689c4ec8fec8ba" },
  "cmp-buffer": { "branch": "main", "commit": "3022dbc9166796b644a841a02de8dd1cc1d311fa" },
  "cmp-nvim-lsp": { "branch": "main", "commit": "39e2eda76828d88b773cc27a3f61d2ad782c922d" },
  "cmp-path": { "branch": "main", "commit": "91ff86cd9c29299a64f968ebb45846c485725f23" },
  "cmp_luasnip": { "branch": "master", "commit": "05a9ab28b53f71d1aece421ef32fee2cb857a843" },
  "copilot.lua": { "branch": "master", "commit": "f9e2c140643bd4519a4517a78a51f6ae8b8b2a95" },
  "dressing.nvim": { "branch": "master", "commit": "c5775a888adbc50652cb370073fcfec963eca93e" },
  "img-clip.nvim": { "branch": "main", "commit": "28a32d811d69042f4fa5c3d5fa35571df2bc1623" },
  "lazy.nvim": { "branch": "main", "commit": "48b52b5cfcf8f88ed0aff8fde573a5cc20b1306d" },
  "mason-lspconfig.nvim": { "branch": "main", "commit": "25c11854aa25558ee6c03432edfa0df0217324be" },
  "mason.nvim": { "branch": "main", "commit": "e2f7f9044ec30067bc11800a9e266664b88cda22" },
  "nui.nvim": { "branch": "main", "commit": "61574ce6e60c815b0a0c4b5655b8486ba58089a1" },
  "nvim-cmp": { "branch": "main", "commit": "ae644feb7b67bf1ce4260c231d1d4300b19c6f30" },
  "nvim-lspconfig": { "branch": "master", "commit": "056f569f71e4b726323b799b9cfacc53653bceb3" },
  "nvim-tree.lua": { "branch": "master", "commit": "d41b4ca013ed89e41b9c0ecbdae5f1633e42f7fa" },
  "nvim-treesitter": { "branch": "master", "commit": "6a3c6a42a6e24414bdf337b05a84a0ea013dd155" },
  "nvim-web-devicons": { "branch": "master", "commit": "9793801f974bba70e4ac5d7eae6c4f5659993d8e" },
  "plenary.nvim": { "branch": "master", "commit": "ec289423a1693aeae6cd0d503bac2856af74edaa" },
  "render-markdown.nvim": { "branch": "main", "commit": "a5e2d0b1215814c3d033be1fd8eccf59ce366399" },
  "telescope-fzf-native.nvim": { "branch": "main", "commit": "cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b" },
  "telescope.nvim": { "branch": "master", "commit": "fe999db6e0c39c8984519ead75660e0e2d3245d3" },
  "tiny-devicons-auto-colors.nvim": { "branch": "main", "commit": "a39fa4c92268832f6034306793b8acbfec2a7549" },
  "trouble.nvim": { "branch": "main", "commit": "6efc446226679fda0547c0fd6a7892fd5f5b15d8" },
  "vim-gitgutter": { "branch": "main", "commit": "7b0b5098e3e57be86bb96cfbf2b8902381eef57c" },
  "vim-signature": { "branch": "master", "commit": "6bc3dd1294a22e897f0dcf8dd72b85f350e306bc" },
  "vim-surround": { "branch": "master", "commit": "3d188ed2113431cf8dac77be61b842acb64433d9" }
}
```

**Comment by qdbp** [comment]
looking at the code closer, I figured out that this:
```
local ah = require('avante.highlights')
if ah then
    vim.api.nvim_set_hl(ah.hint_ns, 'NormalFloat', { fg = c.fg_light, bg = c.bg_3 })
end
```
works, but this is quite clunky and shouldn't be necessary. It appears that whatever fallback is in the code there doesn't work. Note that you don't need this workaround for the similarly structured `input_ns`.

**Comment by aarnphm** [comment]
This is strange, since we link it to NormalFloat

**Comment by aarnphm** [comment]
Did you set the highlight before or after avante.nvim? Since we only setup the link once in setup (which will be invoked during startup time).

So if the normalfloat is changed afterwards then setup won't be called afaik

**Comment by qdbp** [comment]
yes, you're right -- in my current iteration I set the highlights after I run all the setup machinery. that would fix it.

imho this is unnecessarily limiting behavior and, on the face of, a reason to avoid namespaces (not knowing NS id in advance is precisely what introduces this ordering, if it was a named NS this wouldn't be a problem). my preference would be to remove this behavior and just use e.g. `AvanteFloatNormal` which seems more idiomatic

I can whip up a PR if you agree; if not, feel free to close

**Comment by aarnphm** [comment]
It seems like we should fix this; maybe we don't need to set up a namespace in general (since most of the HL groups, we prefixed it with Avante anw).

We should clean up ns if it is manageable

iirc using global namespace should fix this?

**Comment by qdbp** [comment]
yes. I should have some time in the few days to submit a PR to just use `Avante` prefixed groups using the default global namespace (0)

(imho the namespace design in neovim doesn't make sense. a dynamically generated ID is not a "namespace" in any meaningful way. it should really be a registration of a statically known name (e.g. "@avante") with "." separated highlight tags, just like LSP and treesitter... but I digress)

**Comment by aarnphm** [comment]
Yep, I agree. just let me know when the PR is up (no sweat at all as we are all busy :)) )
