### ISSUE TITLE
feature: Allow for new chat command

### ISSUE THREAD

**Issue by RicardoHS** [yetone/avante.nvim#572]
### Feature request

Sometimes file chat history get messed and Claude starts to gives incorrect hints due differences on what is on the file and what is on the chat. A command to start again would be great!

**Comment by luisiacc** [comment]
it already exists, it's called `/clear`

**Comment by RicardoHS** [comment]
ouh nice. is this documented?

**Comment by luisiacc** [comment]
not really, I just read the code to find it, the readme said they had slash commands so i pressed `/` on the AvanteAsk and they showed as autocomplete.

**Comment by RicardoHS** [comment]
And I also seeing now there is a AvanteClear command. Closing this request then. Thank you for the info.
