### ISSUE TITLE
bug: Not getting response back

### ISSUE THREAD

**Issue by o-glethorpe** [yetone/avante.nvim#574]
### Describe the bug

Getting stuck on generating response.
Seems almost everithing is working fine, since I'm getting charged for the requests, but results are not showing.

### To reproduce

Just trying the simple configuration provided as a sample.

### Environment

Just updated

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

**Comment by aarnphm** [comment]
Kay check for credits.

**Comment by o-glethorpe** [comment]
> Kay check for credits.

What?

**Comment by aarnphm** [comment]
do you have API credits lmao

**Comment by o-glethorpe** [comment]
Yes I have, lost a lot of credits because I tought it was not working, but the problem is only to display the results, the api requests are working fine.
I just copy and paste the sample code, there is noting special about it.
Im using a mac.

**Comment by o-glethorpe** [comment]
![Screenshot 2024-09-16 at 23 19 44](https://github.com/user-attachments/assets/106c1f98-330a-41dd-bd5f-4383ad38fa0c)
stuck here, as I said before, the request goes trough because I lost credits.
