### ISSUE TITLE
bug: visual mode selection + pressing key 'c' is slow, if pressed twice error shows up

### ISSUE THREAD

**Issue by av1155** [yetone/avante.nvim#580]
### Describe the bug

`**E492: Not an editor command: '<,'>AvanteConflictChooseCursor**`

Slow behavior:
1. Create a random test.txt file
2. Type anything into the file
3. Highlight a word, or anything in the buffer, in visual mode
4. Press the 'c' key to "change"
5. Notice it takes a long time for the word, or selection, to get deleted
6. Normal functionality resumes

Error shows up if:
1. Create a random test.txt file
2. Type anything into the file
3. Highlight a word, or anything in the buffer, in visual mode
4. Fast press the 'c' key to "change" more than 1 or 2 times, 
5. Error -> `E492: Not an editor command: '<,'>AvanteConflictChooseCursor`

### To reproduce

E492: Not an editor command: '<,'>AvanteConflictChooseCursor

Slow behavior:
1. Create a random test.txt file
2. Type anything into the file
3. Highlight a word, or anything in the buffer, in visual mode
4. Press the 'c' key to "change"
5. Notice it takes a long time for the word, or selection, to get deleted
6. Normal functionality resumes

Error shows up if:
1. Create a random test.txt file
2. Type anything into the file
3. Highlight a word, or anything in the buffer, in visual mode
4. Fast press the 'c' key to "change" more than 1 or 2 times, 
5. Error -> E492: Not an editor command: '<,'>AvanteConflictChooseCursor

### Expected behavior

No error when pressing 'c' key fast, and fast use of 'c' key in visual mode when Avante is installed.

### Environment

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info

**Comment by b0o** [comment]
Hi there, I can't reproduce this. Can you please share your config?

**Comment by b0o** [comment]
Also, can you test if a similar error appears when you quickly hit `ct` or `co`?

**Comment by will-lynas** [comment]
I have this too. `cc` is very slow.

**Comment by aarnphm** [comment]
Are you using which-key by any chance? I can't reproduce this?

**Comment by will-lynas** [comment]
I am

**Comment by av1155** [comment]
https://github.com/user-attachments/assets/c9161e56-b868-4dbf-92b7-34abb25da401

`cw` is instant, `vwc` is slow, `vwcc` produces error (pressing `c` more than once on a highlighted string). 
Visual string highlight can be either with key stroke or mouse double click.

Obviously pressing c more than once on a highlighted string has no use, but sometimes we like to press keys many times, idk y.

I am using AstroNvim but I have had this config for around 1 year and a half now, I moved away from all IDE's. So I can safely say I understand how Neovim configuration works.

My avante config is the one provided by astrocommunity (https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/completion/avante-nvim), the only reason for me to have that lazy config is in case i want to modify any defaults, which I only modified it so that the side panel uses 40% of screen instead of 30%.

**Comment by aarnphm** [comment]
Oh ok these commands don't exist anymore

```lua
AvanteConflictChooseAllTheirs",
    "AvanteConflictChooseBase",
    "AvanteConflictChooseBoth",
    "AvanteConflictChooseCursor",
    "AvanteConflictChooseNone",
    "AvanteConflictChooseOurs",
    "AvanteConflictChooseTheirs",
    "AvanteConflictListQf",
    "AvanteConflictNextConflict",
    "AvanteConflictPrevConflict",
```

We now replaced all of those with `<Plug>(Command)` instead. Probably should update upstream with astronvim

**Comment by aarnphm** [comment]
Ok the astronvim config aside, https://github.com/AstroNvim/astrocommunity/pull/1210

**Comment by av1155** [comment]
Thank you!
