### ISSUE TITLE
bug: issue with packer

### ISSUE THREAD

**Issue by harshvishu** [yetone/avante.nvim#581]
### Getting the following error

```
E5108: Error executing lua: ...im/site/pack/packer/start/avante.nvim/lua/avante/llm.lua:61: Make sure to build avante (missing avante
_templates)
stack traceback:
        [C]: in function 'error'
        ...m/site/pack/packer/start/avante.nvim/lua/avante/path.lua:75: in function 'get'
        ...im/site/pack/packer/start/avante.nvim/lua/avante/llm.lua:61: in function 'stream'
        ...ite/pack/packer/start/avante.nvim/lua/avante/sidebar.lua:1273: in function 'handle_submit'
        ...ite/pack/packer/start/avante.nvim/lua/avante/sidebar.lua:1327: in function <...ite/pack/packer/start/avante.nvim/lua/avant
e/sidebar.lua:1317>
```

### Packer.lua config

```
 -- Avante.nvim configuration
    use {
        'yetone/avante.nvim',
        build = "make",
        lazy = false,
        version = false,
        BUILD_FROM_SOURCE = true,
        requires = {
            'nvim-tree/nvim-web-devicons',
            'stevearc/dressing.nvim',
            'nvim-lua/plenary.nvim',
            'MunifTanjim/nui.nvim',
            {
                'MeanderingProgrammer/render-markdown.nvim',
                config = function()
                    require('render-markdown').setup({
                        file_types = { "markdown", "Avante" },
                    })
                end,
            },
        },
        config = function()
            require('avante.config')
        end,
        run = 'make', -- Optional, only if you want to use tiktoken_core to calculate tokens count
    }
```

### after/plugin/avante.lua

```
local avante = require('avante')

avante.setup({
  provider = "openai", -- Use the Llama 3.1 model
  openai = {
    endpoint = "http://localhost:11434/v1/", -- Local Ollama instance
    model = "llama-3.1", -- Llama 3.1 model
    temperature = 0,
    max_tokens = 4096,
  },
  behaviour = {
    auto_set_highlight_group = true,
    auto_apply_diff_after_generation = false,
  },
  mappings = {
    ask = "<leader>aa",
    refresh = "<leader>ar",
  },
  windows = {
    wrap = true,
    width = 40,
  },
})
```

### Nvim info

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

### Device Info

Darwin harshs-MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:12 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6020 arm64

**Comment by g3org3** [comment]
what it helped me was to upgrade my rust , remove and add again the plugin and build it manually

```
cd ...../avante.nvim
make BUILD_FROM_SOURCE=true
```

**Comment by harshvishu** [comment]
Still the same result. Have rustc 1.81.0 installed.

**Comment by iDash3** [comment]
Have the same error. Upgrading Rust didn't help.

**Comment by muhrizkiakbar** [comment]
i got this error too

**Comment by wu790616** [comment]
Got the same error too

**Comment by zatevakhin** [comment]
same same

**Comment by yetone** [comment]
‌‌‌You can try executing the following command:

```bash
cd  ~/.local/share/nvim/lazy/avante.nvim
make
```

**Comment by pargara** [comment]
@yetone didn't work. My path is 

`.local/share/nvim/site/pack/packer/start`

**Comment by harshvishu** [comment]
cd ~/.local/share/nvim/site/pack/packer/start/avante.nvim/
make
LUA_VERSION=luajit bash ./build.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 6645k    0 32759    0     0  13978      0  0:08:06  0:00:02  0:08:04 34702x avante_templates.dylib
100 6645k  100 6645k    0     0   711k      0  0:00:09  0:00:09 --:--:--  930k

-----
Followed for packer. Didn't work. 🛑

**Comment by yetone** [comment]
> cd ~/.local/share/nvim/site/pack/packer/start/avante.nvim/ make LUA_VERSION=luajit bash ./build.sh % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 6645k 0 32759 0 0 13978 0 0:08:06 0:00:02 0:08:04 34702x avante_templates.dylib 100 6645k 100 6645k 0 0 711k 0 0:00:09 0:00:09 --:--:-- 930k
> 
> Followed for packer. Didn't work. 🛑

Can you see the downloaded files?

```bash
ls ./build
```

The following two files are expected:

<img width="399" alt="image" src="https://github.com/user-attachments/assets/3ad8d00f-581e-4406-9b85-1a8dfe458470">

**Comment by Oleh-Rudko** [comment]
I have the same issue and can't find a solution.

It would be cool if there were an example with a `packer`, of course, I understand that everyone is moving to `lazy.nvim` now, but my problem is that some plugins are not supported by `lazy.nvim` and therefore I can't go there

**Comment by sabmirsad** [comment]
Have the same problem with packer... :disappointed:

**Comment by wczyz** [comment]
Managed to fix that by a small change renaming `avante_repo_map` to `avante.repo_map`. Not sure though if it's only a concidence, didn't examine further. #681 
Works on my machine 😆

**Comment by wczyz** [comment]
Managed to fix the issue.
Added 
```
require("avante_lib").load()
```
to my setup.
Whole packer entry:
```
use {
  "yetone/avante.nvim",
  build = "make BUILD_FROM_SOURCE=true",
  lazy = false,
  version = false,
  BUILD_FROM_SOURCE = true,
  config = function()
    require("avante_lib").load()
    require("avante").setup()
  end,
  requires = {
    "nvim-treesitter/nvim-treesitter",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    --- The below dependencies are optional,
    "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
    "HakonHarnes/img-clip.nvim",
  },
}
```

**Comment by harshvishu** [comment]
Confirmed working after following above changes. Thanks a ton 🙇🏼 
Also it is working with the local ollama instance which is great for low level tasks. 😃 
```
require("avante_lib").load()
require("avante").setup()
```

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/de199eed-2c6c-4696-a39e-2b0819dcf75b">

**Comment by bogdan-manole** [comment]
> Managed to fix the issue. Added
> 
> ```
> require("avante_lib").load()
> ```

God bless you, For those using `home-manager` for nvim, on Macos (aarch64) without this it doesn't work

this works now

```nix
{
      plugin = avante-nvim;
      type = "lua";
      config = ''
              require("avante_lib").load()
              require("avante").setup(
              {
                  --- ... existing configurations
              }

        )''; # or builtins.readFile ./plugins/avante.lua;
    }
```
