### ISSUE TITLE
feature: Dispatch auto suggestion to copilot itself

### ISSUE THREAD

**Issue by MrZLeo** [yetone/avante.nvim#606]
### Feature request

Hi, I am wondering whether we can use auto suggestion feature by `copilot.lua` itself rather than using API. It seems like avant.nvim trigger so much API calls that Github even sent a email to warn me about that. :lol

### Motivation

Reduce API calls when have a access to copilot directly.

**Comment by yetone** [comment]
There's no need to go around in circles; it's better to directly disable avante's auto_suggestions and then use copilot.lua.
