### ISSUE TITLE
E492: Not an editor command: AvanteAsk

### ISSUE THREAD

**Issue by sansyrox** [yetone/avante.nvim#624]
Hey Everyone 👋 

I am trying to install avante using VimPlug but I am getting the following error.

```
E492: Not an editor command: AvanteAsk
```

https://github.com/sansyrox/macsimus/pull/22 , I have created a draft PR to show how I am adding it but essentially,

I am sourcing config like this

```
luafile $HOME/.config/nvim/lua/avante-config.lua
```

and  installing the plugin like

```
    Plug 'yetone/avante.nvim', { 'branch': 'main', 'do': { -> avante#build('source=true') } }
    set laststatus=3

    call plug#end()
autocmd! User avante.nvim lua require('avante_lib').load()

```

Do let me know what can I do differently or what more information is needed from my end

**Comment by kanhirun** [comment]
I am running into the same issue here!

**Comment by henryaj** [comment]
And me

**Comment by rsetia** [comment]
Same, I tried `make BUILD_FROM_SOURCE=true` at `.local/share/nvim/plugged/avante.nvim` and it still doesn't work - getting `Not an editor command: AvanteAsk`

**Comment by aarnphm** [comment]
try to use `make` instead.
