### ISSUE TITLE
bug: Setting auto_apply_diff_after_generation = false does not show diff view, replaces code directly

### ISSUE THREAD

**Issue by l3itisys** [yetone/avante.nvim#626]
### Description

When I set auto_apply_diff_after_generation = false in my avante.nvim configuration, I expect the plugin to display a diff view after generating code, allowing me to compare the original and new code before applying changes. However, the plugin is directly replacing the original code without showing a diff view.

### To reproduce

1.Set up avante.nvim with the following configuration:
-- Load Avante library
require("avante_lib").load()

-- Configure Avante
require("avante").setup({
  provider = "claude",
  auto_suggestions_provider = "claude",
  claude = {
    endpoint = "https://api.anthropic.com",
    model = "claude-3-5-sonnet-20240620",
    temperature = 0,
    max_tokens = 4096,
  },
  behaviour = {
    auto_suggestions = false,
    auto_set_highlight_group = true,
    auto_set_keymaps = true,
    auto_apply_diff_after_generation = false,
    support_paste_from_clipboard = false,
  },
  -- Other configurations as needed
})

2. Open Neovim and a code file (e.g., example.py).

3. Select a block of code using visual mode.

4. Invoke the Avante edit command using <leader>ae.

5. Provide a prompt for code modification.

6. After submission, observe that the original code is replaced directly without showing a diff view.

### Expected behavior

A diff view should appear after the AI generates code, allowing me to compare the original and new code before deciding whether to accept or reject the changes.

### Actual Behavior

The plugin replaces the original code directly without showing a diff view.

### Environment

NVIM v0.11.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

### Additional Information

I have tried adding the diff section to my configuration, setting autojump = false, but the issue persists.

Other relevant plugins installed:

List any plugins that might be relevant.
I have updated avante.nvim to the latest version and ensured that all dependencies are installed.

I have checked the documentation and issue tracker but did not find a solution.

### Logs and Error Messages

There are no error messages displayed.

I enabled debugging in avante.nvim but did not observe any relevant output.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

**Comment by aarnphm** [comment]
do you mean by `auto_apply_diff_after_generation = true`?

`false` only show diff if you navigate to the codeblock and press `a` to apply the codeblock suggestion.

**Comment by KendrickChou** [comment]
same problem here in MacOS
my config is following:
```
	opts = {
		-- add any opts here
		provider = 'openai',
		auto_suggestion_provider = 'openai',
		openai = {
			endpoint = 'http://xxx/v1',
			-- model = "gpt-4o",
			model = 'claude-3-5',
			timeout = 30000, -- Timeout in milliseconds
			temperature = 0,
			max_tokens = 4096,
			['local'] = false,
		},
		behaviour = {
			auto_suggestions = false, -- Experimental stage
			auto_set_highlight_group = true,
			auto_set_keymaps = true,
			auto_apply_diff_after_generation = false,
			support_paste_from_clipboard = false,
		},
	},
