### ISSUE TITLE
bug: the chat history will be cleared after toggle the chat window

### ISSUE THREAD

**Issue by RomaLzhih** [yetone/avante.nvim#627]
### Describe the bug

As the title suggests. I have tried both the default `<leader>aa` and `:AvanteAsk`.
Is there any options to control this issue?

### Expected behavior

The previous chat history should stay in the chat panel unless there is an explicit setting or clear operation.

### Environment

0.11.0

```

**Comment by aarnphm** [comment]
are you sure you didn't clear the chat before this?

Chat history should be persistent

**Comment by RomaLzhih** [comment]
Yes, I am sure. Below is my configuration. And I use default keymaps. Thanks.
```
	-- NOTE: avante
	{
		"yetone/avante.nvim",
		event = "VeryLazy",
		lazy = false,
		build = "make BUILD_FROM_SOURCE=true",
		opts = {
			provider = "gemini",
			auto_suggestions_provider = "copilot",
			hints = { enabled = false },
			windows = {
				position = "bottom", -- the position of the sidebar
				width = 100, -- default % based on available width
				height = 50,
			},
		},
		dependencies = {
			"stevearc/dressing.nvim",
			"nvim-lua/plenary.nvim",
			"MunifTanjim/nui.nvim",
			"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
			"zbirenbaum/copilot.lua", -- for providers='copilot'
		},
	},
```

**Comment by sadkodev** [comment]
In my case, all chat history is also deleted every time I close my "Avante". My configurations are default.

**Comment by matsal007** [comment]
> In my case, all chat history is also deleted every time I close my "Avante". My configurations are default.

Same case with me

**Comment by Console-buche** [comment]
Same here

**Comment by hanpham32** [comment]
Same here. Chat history is not persistent after closing of Avante. Would be nice to have a drop down of past chats.
