### ISSUE TITLE
[bug] leader aa on a new vim tab has issue

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#63]
how to reproduce

1. open avante sidebar on one tab, don't close it
2. open a new vim tab
3. leader aa
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/f00bd18c-d9db-461e-8033-b7c5122df125">

**Comment by aarnphm** [comment]
hmm seems like sidebar is not initialized correctly on TabOpen. Should be fixed in #65 cc @yetone
