### ISSUE TITLE
bug: error after updating the plugin 

### ISSUE THREAD

**Issue by raaymax** [yetone/avante.nvim#665]
### Describe the bug

After updating avante this error started to show up on nvim startup
```
Error executing vim.schedule lua callback: ...te/pack/packer/start/avante.nvim/lua/avante/repo_map.lua:19: Failed to load avante_repo_map
stack traceback:
        [C]: in function 'error'
        ...te/pack/packer/start/avante.nvim/lua/avante/repo_map.lua:19: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Expected behavior

No error

### Environment

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491

**Comment by yetone** [comment]
What operating system are you?

**Comment by itsdaiego** [comment]
I'm also experiencing this, as described here: https://github.com/yetone/avante.nvim/issues/612#issuecomment-2378113141

I'm using MacOS (m1 chip) 🤔

**Comment by lsantos7654** [comment]
Followed those same steps still running into the same issues.

I'm on fedora 40 on a M2.

**Comment by DJPoland** [comment]
Same issue here. M3 Max.

**Comment by raaymax** [comment]
macOS 15 - M3 Pro chip

**Comment by DJPoland** [comment]
Yup, that fixed the issue. ```avante_repo_map.dylib``` was missing it seems.

**Comment by nicolimo86** [comment]
I'm experiencing the same on top of an AWS EC2 running Ubuntu 22.04.3 LTS.

**Comment by lsantos7654** [comment]
Updating that I was able to fix the issue by navigating to avante.nvim
```
cd ~/.local/share/nvim/lazy/avante.nvim
```

and running this instead
```
make BUILD_FROM_SOURCE=true
```

Seems like my issue was that I didn't have rust/cargo installed.

**Comment by nicolimo86** [comment]
> I'm experiencing the same on top of an AWS EC2 running Ubuntu 22.04.3 LTS.

I managed to fix it by doing the following:

1. Install Rust
2. Installing those missing packages: `sudo apt install pkg-config libssl-dev`
3. Compiling the plugin manually:
```
cd ~/.local/share/nvim/lazy/avante.nvim
make BUILD_FROM_SOURCE=true
```

Note: those steps fixed the installation of the avante plugin on top of the EC2 running Ubuntu. On my laptop running Ubuntu everything was working out of the box.

**Comment by TheStutterNerd** [comment]
Same issue here using arch. Building it from source fixed it.

**Comment by beiyouwuyanzu** [comment]
I met the same issue, I use window10, it remind me to use make, but the document shows in windows it shoud use 
```  
build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false", -- for windows
```

instead of `make`, right?

the error detail is below(it occur when I submited prompt to llm):
![image](https://github.com/user-attachments/assets/11133700-f820-4169-ba36-7dabb8054be0)

**Comment by dsuttonpreece** [comment]
I'm running ubuntu in parallels on macos m1

Works great on mac, but getting the op "repo_map" error when using `build = make`, and same "missing avante_templates" as @beiyouwuyanzu when I build from source.

Any ideas? Seems to be working out of the box for other linux users.

**Comment by GAlcaraz** [comment]
On Fedora 40, this solved the issue for me

> Can you follow these steps?
> 
> [#612 (comment)](https://github.com/yetone/avante.nvim/issues/612#issuecomment-2375729928)

**Comment by aarnphm** [comment]
Seems like a build issue. I can't seem to reproduce it.

you can try delete `vim.fn.stdpath("data") .. "/lazy/avante/"` then install again
