### ISSUE TITLE
Is it possible to support GitHub Copilot Chat?

### ISSUE THREAD

**Issue by pidgeon777** [yetone/avante.nvim#68]
As the titles says.

References:

https://docs.github.com/en/copilot/quickstart

https://github.com/CopilotC-Nvim/CopilotChat.nvim

**Comment by yetone** [comment]
‌‌I haven't used this plugin yet, let me study it first.

**Comment by aarnphm** [comment]
are you asking about copilot as a potential provider?

**Comment by pidgeon777** [comment]
What I mean is that with the following plugin:

[CopilotChat.nvim](https://github.com/CopilotC-Nvim/CopilotChat.nvim)

it is possible to ask questions to Copilot Chat using the Copilot subscription and with access to the GPT-4o (not mini) model. All of this can be done without the need to use any OpenAI API key and with no limits.

Given that the aforementioned plugin already supports some kind of "insert diff" feature similar to the one of `Cursor.ai` (though very basic), it would be great, in my opinion, for `avante.nvim` to add support for the Copilot Chat provider as done in the other plugin. However, this should be implemented in a more "powerful" way, emulating most of the `Cursor.ai` features.

**Comment by pidgeon777** [comment]
Here is another interesting read, accompanied by a video:

[How to Use Copilot Chat with Neovim](https://blog.productsway.com/how-to-use-copilot-chat-with-neovim)
