### ISSUE TITLE
feature: Config to turn off virtual text showing keybindings for ask and edit

### ISSUE THREAD

**Issue by srgsanky** [yetone/avante.nvim#682]
### Feature request

Add config to turn off virtual text in visual mode that shows the keybindings to search with avante.

```
some_text  [<leader>aa: ask, <leader>ae: edit]
```

I couldn't find a relevant configuration that can do this today https://github.com/yetone/avante.nvim/blob/main/lua/avante/config.lua

The logic that shows the virtual text https://github.com/yetone/avante.nvim/blob/0705234991d03170a72582085dc508600a03a779/lua/avante/selection.lua#L505-L516

### Motivation

Virtual text at the end of selected line is useful only at the beginning when the keybindings are not familiar. Later on, it becomes a distraction and I want to turn it off.

**Comment by romac** [comment]
Setting `hints = { enabled = false }` worked for me, maybe give it a try?

**Comment by srgsanky** [comment]
As of https://github.com/yetone/avante.nvim/commit/fed6902c9a9a3c4473238e924cddc1ba19f3195b, you will need the following to disable the hints

```lua
selection = {
    enabled = false,
},
```
