### ISSUE TITLE
feature: Add a new floating window

### ISSUE THREAD

**Issue by Bourbxn** [yetone/avante.nvim#708]
### Feature request

An example would be something like telescope.nvim

<img width="1612" alt="image" src="https://github.com/user-attachments/assets/ad07e03f-1c21-42d9-b6cd-e1ab073dc69a">
<br><br>
I think the configuration should be something like this.
<br><br>

```
windows = {
    ---@type "right" | "left" | "top" | "bottom"| "float"
    position = "float", 
    ...
}
```

**Comment by aarnphm** [comment]
Sorry, we won't support floating windows.

**Comment by estubmo** [comment]
Would love it if you reconsidered. https://github.com/CopilotC-Nvim/CopilotChat.nvim has a nice implementation.
Thank you for your hard work :+1:

**Comment by aarnphm** [comment]
we support floating windows in the past, and it has too much code.

Unless we can simplify our windows management, which is pretty much on our backlog for now, we won't have bandwidth to support floating windows.
