### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [yetone/avante.nvim#718]
### Describe the bug

```
Error detected while processing InsertEnter Autocommands for "<buffer=11>":
Error executing lua callback: ...yNeovimPackages/start/avante.nvim/lua/avante/sidebar.lua:1365: attempt to index field 'input' (a nil value)
stack traceback:
	...yNeovimPackages/start/avante.nvim/lua/avante/sidebar.lua:1365: in function <...yNeovimPackages/start/avante.nvim/lua/avante/sidebar.lua:1359>

1 line less; before #70  0 seconds ago

```

### To reproduce

Not sure how I triggered it. Will update the issue if I figure it out

### Expected behavior

It should not crash

### Environment

❯ nvim -v && uname -a
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
Linux Monday 6.6.54 #1-NixOS SMP PREEMPT_DYNAMIC Fri Oct  4 14:30:05 UTC 2024 x86_64 GNU/Linux

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

**Comment by yetone** [comment]
‌‌It seems that you are not using the latest version; you can try updating to the newest version.

**Comment by gytis-ivaskevicius** [comment]
Might be the case, will reopen this if I encounter it again
