### ISSUE TITLE
feature: ability to use ollama for auto-suggestions

### ISSUE THREAD

**Issue by famiu** [yetone/avante.nvim#723]
### Feature request

Ability to use local Ollama models with FIM support for auto-suggestion. Currently I don't think it's possible to use Ollama models for auto-suggestion since the plugin doesn't support FIM (correct me if I'm wrong).

There are already plugins that implement code completion through Ollama like https://github.com/huggingface/llm.nvim and https://github.com/meeehdi-dev/bropilot.nvim, those could be used as reference implementations

### Motivation

Ollama models are already supported for chat, so it would be great if they were supported for completion as well.

**Comment by aarnphm** [comment]
you can use custom providers for this, and auto_suggestion_provider should already support custom providers.

See wiki for how to setup ollama

**Comment by famiu** [comment]
> you can use custom providers for this, and auto_suggestion_provider should already support custom providers.
> 
> See wiki for how to setup ollama

I did, it doesn't work. Could not get it to work with Codegemma, Codellama, Qwen2.5-Coder or anything I tried because avante.nvim doesn't have FIM support.

@aarnphm Kindly do not close the issue without understanding what the problem is first
