### ISSUE TITLE
feature: Don't repeat existing code

### ISSUE THREAD

**Issue by eyalk11** [yetone/avante.nvim#753]
### Feature request

Repeating existing code (unchanged) by llm in chat,  is prone for mistakes ,slow and also makes it harder for the user to work out the changes by eye.

### Motivation

It is the way in cursours TBH .

**Comment by b0o** [comment]
Related: #582 #583

**Comment by yetone** [comment]
‌‌‌‌‌‌‌The latest version already supports minimal diff.
