### ISSUE TITLE
feature: check if copilot is authorised before trying to initialize

### ISSUE THREAD

**Issue by quantum-booty** [yetone/avante.nvim#763]
### Feature request

I only have copilot on some machines, so it would be good to check if copilot is available and print a small warning, instead of producing this intrusive message.
![image](https://github.com/user-attachments/assets/fa18251f-acfe-408b-b38e-34b297669cd1)

**Comment by aarnphm** [comment]
not sure what is intrusive about this, we have stated in the README.md for copilot backend to either have copilot.vim or copilot.lua setup for auth.

Therefore, I don't think there is anything wrong with raising an error here
