### ISSUE TITLE
feature: different claude model for auto suggestions

### ISSUE THREAD

**Issue by trevorwhitney** [yetone/avante.nvim#774]
### Feature request

I want to use claude sonnet for chat, but claude haiku for auto suggestions.

### Motivation

Haiku is faster and cheaper, but sonnet is better and more accurate. So, I'd like to give the small/quick tasks to haiku, while still chatting with sonnet.

I currently use the copliot plugin for auto-suggestions, but they seem to keep adding new Copilot features to VS Code while abandoning the vim plugin, so I'm looking for other options with more flexibility.

### Other

I can take a stab at a PR if you have a vision for how this should be implemented, ie can claude have multiple modes, and one must specify `claude-sonnet` or `claude-haiku` to specify which mode they'd like to use?

**Comment by JonatasAmaral** [comment]
Hey, seen it could be done with [custom providers](https://github.com/yetone/avante.nvim/wiki#custom-providers), so you copy the official claude one, setting only the model to haiku

```lua
vendors = {
      claude-haiku = {
            ...
      }
}
```

and in you config

```lua
    provider = "claude", -- Recommend using Claude
    auto_suggestions_provider = "claude-haiku",
```

**Comment by aarnphm** [comment]
hmm we can add claude-haiku and claude-opus to default vendors, given that it makes sense

for copilot it would be a catch up game for sure.
