### ISSUE TITLE
bug: claude generating no response

### ISSUE THREAD

**Issue by sayandipdutta** [yetone/avante.nvim#775]
### Describe the bug

When I press `<leader>aa` or `:AvanteAsk` and after submitting the message in the chat area, it instantly shows `Generating response...` and `Generation complete! Please review the code suggestion above.`. I have checked that I have enough credit in my account.

![image](https://github.com/user-attachments/assets/cbde3cc0-d4aa-409e-9364-718a86a50ce7)

### Installation method

Using lazy.nvim:
```lua
return {
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  opts = {
    provider = "claude",
  },
  build = "make",
  keys = {
    {
      "<leader>aa",
      function()
        require("avante.api").ask()
      end,
      desc = "avante: ask",
      mode = { "n", "v" },
    },
    {
      "<leader>ar",
      function()
        require("avante.api").refresh()
      end,
      desc = "avante: refresh",
    },
    {
      "<leader>ae",
      function()
        require("avante.api").edit()
      end,
      desc = "avante: edit",
      mode = "v",
    },
  },
  dependencies = {
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    --- The below dependencies are optional,
    "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
    {
      -- support for image pasting
      "HakonHarnes/img-clip.nvim",
      event = "VeryLazy",
      opts = {
        -- recommended settings
        default = {
          embed_image_as_base64 = false,
          prompt_for_file_name = false,
          drag_and_drop = {
            insert_mode = true,
          },
          -- required for Windows users
          use_absolute_path = true,
        },
      },
    },
    {
      -- Make sure to setup it properly if you have lazy=true
      "MeanderingProgrammer/render-markdown.nvim",
      opts = {
        file_types = { "markdown", "Avante" },
      },
      ft = { "markdown", "Avante" },
    },
  },
}
```

### Environment

neovim version: 0.10.2
platform: Ubuntu 24.04 On WSL2 on Windows 11

**Comment by parchinski** [comment]
I am also experiencing this issue on Arch WSL nothing seems to fix this error after multiple reinstalls, the same config works on macbookm1.

**Comment by sayandipdutta** [comment]
A month ago this same config worked for me too.

**Comment by parchinski** [comment]
Did you happen to find a solution?

I am wondering if it happens to be the model name we are calling for Claude, I am using the exact same one as you and having the exact same error. It also could have to do with WSL but I really don't think it would be that right?

I have played around putting different model names to work and can't get any to work. I have like at least 60 dollars in credits for the API so it can't be that.

Once again though this works on my macbook air perfectly, so I do not understand what could be happening in our situation but it's super unfortunate that there is no error code in either case.

**Comment by sayandipdutta** [comment]
Nope, WSL or model version is not a problem. I have the same setup on a different machine, it works. As a matter of fact `nvim` version is `0.10.0` in that machine, lower than the prescribed `0.10.1`. I can't figure out what's going wrong! I will try to take a closer look in the weekends.

**Comment by parchinski** [comment]
Im going to attempt to see if this works tonight it promises a fix but ill probably read the changes first to figure out whats going on. 

https://github.com/yuzhegan/avante.nvim

**Comment by sayandipdutta** [comment]
@parchinski found solution for my problem (see https://github.com/yetone/avante.nvim/issues/784#issuecomment-2453150197) . Let me know if your issue stems from the same cause, then I will close this in favor of #784

**Comment by sayandipdutta** [comment]
Also see #315 and the last line of [wiki](https://github.com/yetone/avante.nvim/wiki)

**Comment by parchinski** [comment]
Hey thought I responded earlier but I guess I didn't and this solution worked. So you can probably close the issue if it worked for both of us thank you for your help!

**Comment by sayandipdutta** [comment]
Closing in favor of #784 and #315
