### ISSUE TITLE
bug: "Failed to Load avante_repo_map"

### ISSUE THREAD

**Issue by av1155** [yetone/avante.nvim#792]
### Describe the bug

```
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:22: Failed to load avante_repo_map
stack traceback:
	[C]: in function 'error'
	...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:22: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

When an avante update becomes available, then this shows up `Not an editor command: AvanteBuild`:
```
    ● avante.nvim 15.32ms  VeryLazy
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:25: Error while parsing command line: E492: Not an editor command: AvanteBuild
```

It worked fine before, it stopped working out of nowhere.

I tried uninstalling and installing Avante again with no result, and then removing nvim from share and state, but it didn't fix it either.

### Expected behavior

Not get a warning.

### Installation method

Astronvim:
community.lua:
    { import = "astrocommunity.completion.avante-nvim" },
    {
        "yetone/avante.nvim",
        event = "VeryLazy",
        opts = {
            {
                windows = {
                    ---@type "right" | "left" | "top" | "bottom"
                    position = "right", -- the position of the sidebar
                    wrap = true, -- similar to vim.o.wrap
                    width = 40, -- default % based on available width
                    sidebar_header = {
                        align = "center", -- left, center, right for title
                        rounded = true,
                    },
                },
            },
        },
    },

### Environment

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
MacOS Sequoia

**Comment by b0o** [comment]
Hey @aarnphm it seems like the AvanteBuild command was removed in [`4c7ce2`](https://github.com/yetone/avante.nvim/pull/769/commits/4c7ce29c15c18c0a9a74350930e0fb840ce95e26#diff-f4b9a5a9604b1e5dfe0bf95609e99a080da9d446e28acb828eadf921fbecfa70L81), was that intentional?

**Comment by aarnphm** [comment]
Oops this is my bad. let me revert it

**Comment by aarnphm** [comment]
I revert the change

probably want to stream the logs from stdout somehow with `AvanteBuild`

**Comment by av1155** [comment]
Thank you!

**Comment by Ex-pi-rimental** [comment]
I am getting this error while using avante
