### ISSUE TITLE
[bug] Switch from sidebar to my code, it writes on my code.

### ISSUE THREAD

**Issue by atlas-comstock** [yetone/avante.nvim#80]

**Comment by yetone** [comment]
‌‌‌I couldn't reproduce it on my end. Could you provide the steps to reproduce it?

**Comment by atlas-comstock** [comment]
1. lead aa
2. ask it to fix code
3. while sidebar is echoing, switch to vim edit code window
4. the LLM reply is written to the code

**Comment by aarnphm** [comment]
This is probably a bug, we might need to do two cursor instead of sending the written buffer under the current cursor
