### ISSUE TITLE
feature: Split this plugin into 2 or support for CodeGPT features

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [yetone/avante.nvim#806]
### Feature request

I use avante and codegpt, i think it would be nice to either have 2 plugins where avante depends on codegpt for easier maintenance or at least have codegpt featureset

### Motivation

These plugins are very similar, most of the code is already there. I just think this is a right approach

**Comment by aarnphm** [comment]
What is CodeGPT lmao

**Comment by gytis-ivaskevicius** [comment]
https://github.com/dpayne/CodeGPT.nvim

**Comment by aarnphm** [comment]
I'm confused, this seems out of scope lol
