### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by makermotion** [yetone/avante.nvim#820]
### Feature request

I would like to have more comprehensive documentation. For example  there is a quite fascinating and useful feature looks like implemented `@codebase` but I could not figure out how to make it work. I was not able to use the feature to chat with all project codebase.

### Motivation

To be able to easily read and understand how to use different functionality of the project.

**Comment by moonc4ke** [comment]
Yeah, would love to know how to use @codebase in the Avante. I have tried this feature but for me it didn't work. I kept getting  "E5108: Error executing lua:".
