### ISSUE TITLE
How to clear chat history?

### ISSUE THREAD

**Issue by segersniels** [yetone/avante.nvim#822]
### Describe the bug

With the recent addition of keeping track of conversational context of previous question I am now in need of an option to clear the chat history manually. Each time I ask a question in the same file the previous context get sent and the cost per prompt keep increasing since the input tokens keep becoming bigger and bigger.

Not sure if I'm missing something?

### Installation method

Use lazy.nvim:
```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  version = false, -- set this if you want to always pull the latest change
  opts = {
    -- add any opts here
  },
  -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  build = "make",
  -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
  },
}
```

### Environment

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by kohane27** [comment]
Type and execute `/clear` in the chat window
