### ISSUE TITLE
feature: ability to specify a command to fetch api key from password manager

### ISSUE THREAD

**Issue by UtkarshVerma** [yetone/avante.nvim#833]
### Feature request

I, like many other people, use a password manager to store secrets on my machine. I personally use `gopass` which allows me to get the API key I want through a simple command like:

```console
$ gopass show --password api-keys/anthropic_avante
```

In the Lua config, this could be as simple as adding a string option called `api_key_cmd` which would then be executed to fetch the key from the secrets manager. 

### Motivation

I do not prefer storing my secrets in my shell environment and I personally feel the password-cmd approach would be more scoped.

**Comment by brewinski** [comment]
There is a section in the wiki on secrets.

Does this help you set your environment variables via your password manager?

https://github.com/yetone/avante.nvim/wiki#secrets

**Comment by UtkarshVerma** [comment]
Thanks! It works as expected.

**Comment by brewinski** [comment]
Good to hear @UtkarshVerma :).
