### ISSUE TITLE
bug: Apply all sometimes does not work

### ISSUE THREAD

**Issue by StevenMatchett** [yetone/avante.nvim#837]
### Describe the bug

I have been running into 2 different issues with `ask`. When I go to apply the changes I will sometime after press `A` get `Cannot make changes, 'modifiable' is off`. Other times I will get the change applied in the current buffer and not the code. This will then break the buffer and will need to restart neovim

![Screenshot 2024-11-11 at 8 34 26 PM](https://github.com/user-attachments/assets/cce05750-9da7-4854-949d-7f500d58c6cf)

### Installation method

Use lazy.nvim:
```lua
	{
		"yetone/avante.nvim",
		event = "VeryLazy",
		lazy = false,

		dependencies = {
			"nvim-treesitter/nvim-treesitter",
			"stevearc/dressing.nvim",
			"nvim-lua/plenary.nvim",
			"MunifTanjim/nui.nvim",
			"nvim-tree/nvim-web-devicons",
			"zbirenbaum/copilot.lua", -- required for copilot provider
			{
				"MeanderingProgrammer/render-markdown.nvim",
				opts = { file_types = { "markdown", "Avante" } },
				ft = { "markdown", "Avante" },
			},
		},
		build = "make",
		config = function()
			require('avante_lib').load()
			require('avante').setup({
				provider = "copilot",
				auto_suggestions_provider = "copilot",
				behaviour = {
					auto_suggestions = true, -- Enable auto suggestions
				},
				mappings = {
					suggestion = {
						accept = "<Tab>", -- Changed to Tab
						next = "<C-;>", -- Changed to Control-semicolon
						prev = "<C-'>", -- Changed to Control-quote
						dismiss = "<C-]>",
					},
				},
				windows = {
					position = "right",
					width = 30,
				}
			})
		end,
	},
```

### Environment

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Comment by rcII** [comment]
@StevenMatchett can you explain what the fix was?

**Comment by StevenMatchett** [comment]
I never did I just started using copilot chat. I am waiting for this to mature more
