### ISSUE TITLE
bug:  msg_show.emsg E5108: Error executing lua: ...ck/lazy/opt/avante.nvim/lua/avante/providers/copilot.lua:88: internal initialization error

### ISSUE THREAD

**Issue by Pger-Y** [yetone/avante.nvim#861]
### Describe the bug

runtime：
LunarVim latest
neovim 0.10.2
Mac M2 15.1
Provider: copilot
Copilot is on and works find,but when i try to chat with it using avante, error happened
<img width="1773" alt="image" src="https://github.com/user-attachments/assets/59882227-4419-404d-9793-7c53497f01cc">

### Installation method

	{
		"yetone/avante.nvim", --cd ~/.local/share/lunarvim/site/pack/lazy/opt/avante.nvim && make
		event = "VeryLazy",
		lazy = false,
		version = false, -- set this if you want to always pull the latest change
		opts = {
			default = {
			},
			provider = "copilot", -- Recommend using Claude
			auto_suggestions_provider = "copilot",
			-- add any opts here
		},
		-- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
		build = "make",
		-- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
		dependencies = {
			"nvim-treesitter/nvim-treesitter",
			"stevearc/dressing.nvim",
			"nvim-lua/plenary.nvim",
			"MunifTanjim/nui.nvim",
			--- The below dependencies are optional,
			"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
			"zbirenbaum/copilot.lua",   -- for providers='copilot'
			{
				-- support for image pasting
				"HakonHarnes/img-clip.nvim",
				event = "VeryLazy",
				opts = {
					-- recommended settings
					default = {
						embed_image_as_base64 = false,
						prompt_for_file_name = false,
						drag_and_drop = {
							insert_mode = true,
						},
						-- required for Windows users
						use_absolute_path = true,
					},
				},
			},
			{
				-- Make sure to set this up properly if you have lazy=true
				'MeanderingProgrammer/render-markdown.nvim',
				opts = {
					file_types = { "markdown", "Avante" },
				},
				ft = { "markdown", "Avante" },
			},
		},
	}

### Environment

runtime：
LunarVim latest
neovim 0.10.2
Mac M2 15.1
Provider: copilot

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

**Comment by ethanh20009** [comment]
I have the same error

**Comment by varocode** [comment]
I have the same error

**Comment by fedeya** [comment]
With version 0.0.9 it is working fine.

```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  -- enabled = false,
  version = "0.0.9", -- set this if you want to always pull the latest change
  opts = {
    provider = "copilot",
    copilot = {
      model = "claude-3.5-sonnet",
    },
  },
  -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  build = "make",
  dependencies = {
    "MunifTanjim/nui.nvim",
    --- The below dependencies are optional,
    "zbirenbaum/copilot.lua", -- for providers='copilot'
    {
      -- support for image pasting
      "HakonHarnes/img-clip.nvim",
      event = "VeryLazy",
      opts = {
        -- recommended settings
        default = {
          embed_image_as_base64 = false,
          prompt_for_file_name = false,
          drag_and_drop = {
            insert_mode = true,
          },
          -- required for Windows users
          use_absolute_path = true,
        },
      },
    },
  },
}
```

**Comment by fedeya** [comment]
Commit: 9891b0365607373553b5dab74494a5e81b01e3c2 is working fine also

but the next one 3051bfdf244f9b76130b184915ecbbe0a55fa898 (the new dual boost feature is failing)

**Comment by varocode** [comment]
Thank you so much for providing the solution! With version 0.0.9 and the updated configuration, everything is working perfectly now. I really appreciate your help! 🙌
