### ISSUE TITLE
bug: Error: Internal initialization error in copilot.lua:88

### ISSUE THREAD

**Issue by varocode** [yetone/avante.nvim#866]
### Describe the bug

Description
I’m encountering an error when trying to use the Copilot provider with avante.nvim. Below is the complete error message:

Error executing lua callback: ...e/nvim/lazy/avante.nvim/lua/avante/providers/copilot.lua:88: internal initialization error
stack traceback:
	[C]: in function 'error'
	...e/nvim/lazy/avante.nvim/lua/avante/providers/copilot.lua:88: in function 'refresh_token'
	...e/nvim/lazy/avante.nvim/lua/avante/providers/copilot.lua:141: in function 'parse_curl_args'
	...ev/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:113: in function '_stream'
	...ev/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:354: in function 'stream'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1444: in function 'handle_submit'
	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1664: in function <...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1663>
	[C]: in function 'nvim_exec_autocmds'
	...ev/.local/share/nvim/lazy/avante.nvim/lua/avante/api.lua:119: in function 'ask'
	...ev/.local/share/nvim/lazy/avante.nvim/lua/avante/api.lua:125: in function 'submit_callback'
	.../share/nvim/lazy/avante.nvim/lua/avante/prompt_input.lua:150: in function 'submit'
	.../share/nvim/lazy/avante.nvim/lua/avante/prompt_input.lua:245: in function <.../share/nvim/lazy/avante.nvim/lua/avante/prompt_input.lua:245>

### To reproduce

Configured avante.nvim with the Copilot provider:
opts = {
    provider = "copilot",
    -- other configurations
}

Installed all required dependencies as listed in the documentation.
Successfully authenticated with Copilot using :Copilot auth.
Attempted to use the AvanteAsk or auto-suggestions functionality.
Encountered the error mentioned above.

### Expected behavior

The plugin should connect with the Copilot provider and allow interactions without throwing any errors.

### Installation method

Use lazy.nvim:
```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  version = false, -- set this if you want to always pull the latest change
  opts = {
    -- add any opts here
  },
  -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  build = "make",
  -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
  },
}
```

### Environment

Archlinux

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

**Comment by errnoh** [comment]
@varocode what ended up being the issue here? (I'm getting the same error while trying to use current main branch)

**Comment by rgodha24** [comment]
also getting the same error. what did you do to fix this?

**Comment by errnoh** [comment]
For anyone reading, the issue is https://github.com/yetone/avante.nvim/issues/861
