### ISSUE TITLE
bug: repo_map

### ISSUE THREAD

**Issue by HEBEI77** [yetone/avante.nvim#879]
### Describe the bug

Happend directly after i installed avante

### To reproduce

Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:23: Failed to load avante_repo_map
stack traceback:
        [C]: in function 'error'
        ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:23: in function 'fn'
        vim/_editor.lua:599: in function 'fn'
        vim/_editor.lua:351: in function <vim/_editor.lua:350>

### Expected behavior

Should work with no errors

### Installation method

Use lazy.nvim:
```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  version = false, -- set this if you want to always pull the latest change
  opts = {
    -- add any opts here
  },
  build = "make",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
  },
}
```

### Environment

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1731601260

Linux localhost 4.14.190-perf-gc61d39ef577d-dirty #2 SMP PREEMPT Fri Jun 17 20:06:54 WIB 2022 aarch64 Android

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

**Comment by HEBEI77** [comment]
To anyone saying check #comment612 i tried that already didnt work (im using termux btw)

**Comment by b9Joker108** [comment]
@HEBEI77 I have the same error and I am wondering how you resolved it?
