### ISSUE TITLE
feature: chat without any context

### ISSUE THREAD

**Issue by 2nthony** [yetone/avante.nvim#88]
The current chat opens with the context of the current file(buffer). I believe there should be an option to chat without any context.

---

Here are two ideas I've imagined:

- Chat about coding without any context. `<leader>aA`
- Chat within the context of the current file(buffer), which is the `avante` current behaviour, similar to the Cursor. `<leader>aa`

**Comment by aarnphm** [comment]
I think this is a bit out of scope for avante.nvim. There are other chat plugins to just chat with LLM in a neovim buffer.

I prefer not to include this.

**Comment by 2nthony** [comment]
Sure,  thanks

**Comment by 2nthony** [comment]
<img width="646" alt="image" src="https://github.com/user-attachments/assets/70f6050b-fb69-4d8f-8b69-d36e33480cbd">

hi, just found out that Cursor has an option to chat without context.

so I am reopened this issue, sure feel free to close this again if still think it is out of scope :)

**Comment by yetone** [comment]
Thank you for the suggestion. I need to experience Cursor's simple chat mode to understand why it offers this feature.

**Comment by 2nthony** [comment]
I consider this feature unnecessary as I have been using the cursor for days.

**Comment by Tarquinen** [comment]
Big fan of this feature in Cursor, I like being able to just go to one place for all my LLM prompting. If we could have a secondary keybind to prompt without context similar to Cursor that would be awesome.

**Comment by ntrp** [comment]
I would also like to have a simple mode, the use case is asking simple questions without a huge context and without planning. For example simply asking a question about neovim that is unrelated to the project instead of opening the browser and using another prompt
