### ISSUE TITLE
Do not set stream to true by default

### ISSUE THREAD

**Issue by yuchanns** [yetone/avante.nvim#90]
Hi, I am writing a vendor [plugin](https://github.com/yuchanns/avante_vendor_bedrock) of AWS Bedrock for avante using custom provider.

However, AWS api is strict with its params. When you set stream=true in the body, you will get an error: Malformed input request: #: extraneous key [stream] is not permitted. Instead, bedrock use route /invoke-with-response-stream to enable streaming.

I have checked that there is a default behavior of avante that will set stream if you provider haven't.

https://github.com/yetone/avante.nvim/blob/6ba2143fed2efeb83dcaa3be277bdf56b61cc90e/lua/avante/llm.lua#L545

cc @aarnphm

**Comment by aarnphm** [comment]
yep we should remove it then

**Comment by jcd13d** [comment]
@yuchanns interested to know if you got it working with AWS Bedrock and how!

**Comment by yuchanns** [comment]
@jcd13d Hi! Thanks for your interest. I have made a demo showing how to utilize AWS Bedrock as a provider.

Feel free to go: https://github.com/yuchanns/avante_bedrock.nvim.

It doesn't work properly yet, as it can not mark the stream response end correctly. (Refer to the README)

**Comment by aarnphm** [comment]
@yuchanns you should also link this to the wiki :)

**Comment by aarnphm** [comment]
fwiw we can also support aws, since a lot of the model provider are also supported there (anthropic, cohere) (kinda similar story that we support azure)

**Comment by yuchanns** [comment]
> The issue is that when using bedrock in plenary.nvim, part of the data arrives through on_stdout and the last small portion arrives through callback.
> 
> We are not able to mark the end of the response data with ("avante.llm").on_complete function in callback as it will rise an error nvim_buf_get_name must not be called in a lua loop callback.

@aarnphm I have no idea how to solve the problem. What do you think? IMO, It's great to see the AWS provider being internalized.

**Comment by aarnphm** [comment]
let me setup bedrock to test it out lmao

**Comment by retarpt** [comment]
Hi, just curious if there are any updates here? Thank you.
