### ISSUE TITLE
Feature Request: Adding Mistral llms to the supported services 

### ISSUE THREAD

**Issue by bassamsdata** [yetone/avante.nvim#92]
Hello, thank you for this plugin.

Would it be possible to add support for Mistral LLMs, especially Codestral? 
I've been using Codestral lately and it's very performant.

Thank you.
Edited typo

**Comment by aarnphm** [comment]
You can add it with custom providers

**Comment by bassamsdata** [comment]
oh thank you. I'll try it out

**Comment by DanielAndreasen** [comment]
@bassamsdata did you succeed with this? I would love to see your config if that is the case.

**Comment by bassamsdata** [comment]
Hey @DanielAndreasen, I’ve actually moved my workflow over to the [codecompanion](https://github.com/olimorris/codecompanion.nvim) plugin and no longer use Avante. you can check this [discussion](https://github.com/olimorris/codecompanion.nvim/discussions/282) if you want to use mistral with it.

**Comment by DanielAndreasen** [comment]
Thanks for the reply
