### ISSUE TITLE
How to update the hunk highlight color?

### ISSUE THREAD

**Issue by ivanlee1999** [yetone/avante.nvim#93]
May I ask how I can update the hunk highlight color?
![CleanShot 2024-08-19 at 10 41 14@2x](https://github.com/user-attachments/assets/40dbfb6d-bc82-4271-b7c7-551cc8551f08)

**Comment by yetone** [comment]
<img width="382" alt="image" src="https://github.com/user-attachments/assets/ce3773bb-26cb-49d9-9752-8c957bf77a1c">
