### ISSUE TITLE
bug: AvanteShowRepoMap command exec error

### ISSUE THREAD

**Issue by SuzanneHuang** [yetone/avante.nvim#937]
### Describe the bug

When I execute this command, I get the error message below, I wan't to know how to solve this problem.

:AvanteShowRepoMap
Error executing Lua callback: bad argument #2: error converting Lua string to String (invalid utf-8 sequence of 1 bytes from index 921)
stack traceback:
        [C]: in function 'stringify_definitions'
        ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:62: in function 'f'
        ...t/.soft/nvim-linux64/share/nvim/runtime/lua/vim/iter.lua:366: in function 'each'
        ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:54: in function '_build_repo_map'
        ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:96: in function 'build_and_save'
        ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:104: in function '_get_repo_map'
        ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:77: in function 'get_repo_map'
        ...ocal/share/nvim/lazy/avante.nvim/lua/avante/repo_map.lua:179: in function 'show'
        /root/.local/share/nvim/lazy/avante.nvim/plugin/avante.lua:119: in function </root/.local/share/nvim/lazy/avante.nvim/plugin/avante.lua:119>

### Installation method

Use lazy.nvim:
```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  version = false, -- set this if you want to always pull the latest change
  opts = {
    -- add any opts here
    provider = "gemini",
  },
  -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  build = "make",
  -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  dependencies = {
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    --- The below dependencies are optional,
    "hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
    "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
    "zbirenbaum/copilot.lua", -- for providers='copilot'
    {
      -- support for image pasting
      "HakonHarnes/img-clip.nvim",
      event = "VeryLazy",
      opts = {
        -- recommended settings
        default = {
          embed_image_as_base64 = false,
          prompt_for_file_name = false,
          drag_and_drop = {
            insert_mode = true,
          },
          -- required for Windows users
          use_absolute_path = true,
        },
      },
    },
    {
      -- Make sure to set this up properly if you have lazy=true
      'MeanderingProgrammer/render-markdown.nvim',
      opts = {
        file_types = { "markdown", "Avante" },
      },
      ft = { "markdown", "Avante" },
    },
  },
}
```

### Environment

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068

Linux 62be52025941 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

**Comment by SuzanneHuang** [comment]
find root cause

**Comment by hanpham32** [comment]
> find root cause

What was the error?
