### ISSUE TITLE
bug: prompting on [No Name] buffer in nvim yields Lua error

### ISSUE THREAD

**Issue by paotsaq** [yetone/avante.nvim#951]
### Describe the bug

When I open a `nvim` instance without any filename (ie. just running `nvim` on terminal instead of `nvim test`, for example), doing any prompting (`AvanteAsk`, `AvanteChat`, etc.) will yield `E5108: error executing Lua`. Avante's interface will still show the `**Generating response ...**` panel, but it will not resolve. 

### To reproduce

Open a bare `nvim` instance; try to prompt *anything*. Notice a runtime Lua error.

### Expected behavior

I would expect the model to reply.

### Installation method

Use lazy.nvim:
```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  version = false, -- set this if you want to always pull the latest change
  opts = {
    -- add any opts here
  },
  -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  build = "make",
  -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
  },
}
```

### Environment

```
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info

---

Linux --- 5.15.167-1-MANJARO #1 SMP PREEMPT Thu Sep 12 11:38:41 UTC 2024 x86_64 GNU/Linux
```

**Comment by adylanrff** [comment]
I can reproduce the issue above. What I did as a turnaround is by running it using `nvim .`.

**Comment by paotsaq** [comment]
I think this is just a problem for inexperienced users, and it is probably an edge case on the overall implementation. 

I can try and fix this myself and submit a PR, but would prefer to have some input from maintainers on this.

**Comment by adylanrff** [comment]
@paotsaq would you mind elaborating on why this is a problem for inexperienced users? 

The pattern I am seeing here is when running **without** any file path, the **selected files** path somehow include "." as one of the files
<img width="445" alt="image" src="https://github.com/user-attachments/assets/bb3e4801-ed9a-4a88-a9f1-0e2f3e84354b" />

Compare it to when we are running using `nvim .` (which will not produce the lua error) 
<img width="452" alt="image" src="https://github.com/user-attachments/assets/f285a2c3-2824-4205-9bc1-9678e6ca7d22" />

I have no experience in any neovim plugin development. But I hope this can help the maintainer to identify the issue we are seeing now

**Comment by paotsaq** [comment]
I can confirm is adds `.` as a file. Can you try running a query on the model? Does it not yield a Lua error?

**Comment by adylanrff** [comment]
> I can confirm is adds `.` as a file. Can you try running a query on the model? Does it not yield a Lua error?

Running nvim without a path yielded an error. Running it with `.` didn't. 

In fact, if you: 
1. Run `nvim` without any filepath (selected files will include `.`)
2. Add any file to the "Selected Files" (using @) 
3. Remove `.` from "Selected Files" 

The model would work. So I am pretty sure it is related to the selected files.

**Comment by paotsaq** [comment]
Hmm. Running nvim without a path, I see `.` in the `Selected files`. Prompting yields a Lua error. So this issue in particular is about that error — now I know I cannot test prompting on `nvim` alone — I need at least an argument — but this might not be clear to everyone.

**Comment by paotsaq** [comment]
on line 1500 at sidebar.lua, 

```lua
    local filetype = api.nvim_get_option_value("filetype", { buf = self.code.bufnr })
```

I think the problem might stem from here. On an empty buffer (eg. `nvim` instead of `nvim test`) this will be an empty value (nil? I'm not sure — never did Lua before). 

I'm on a train and working on this is hard 😄 but maybe later I can pursue this further.

**Comment by brewinski** [comment]
Apologies, I didn't see this issue but I've put up a bugifx that might help somewhat with this issue.

https://github.com/yetone/avante.nvim/pull/953

**Comment by brewinski** [comment]
@paotsaq this has been merged.

**Comment by paotsaq** [comment]
Thank you! I think this will be helpful.
