### ISSUE TITLE
UI doesn't work well with Neovide

### ISSUE THREAD

**Issue by bassamsdata** [yetone/avante.nvim#97]
Hello,

There's an issue with this plugin's UI when using Neovide—it doesn't work properly as it shifts the whole UI down, making it difficult to see what I'm typing in the input text.

<img width="1134" alt="Screenshot 2024-08-19 at 2 01 56 PM" src="https://github.com/user-attachments/assets/5894eee7-692e-4f26-b259-a9fe5db7f134">

<img width="371" alt="Screenshot 2024-08-19 at 2 02 39 PM" src="https://github.com/user-attachments/assets/bc0d1d84-347b-4c7c-bdcc-520cc14b9445">

I came across a [comment](https://github.com/neovide/neovide/issues/2502#issuecomment-2083173795) that might be related to the issue, so I'm not sure if this is the cause. However, if it is, adding a simple `if` statement to check `vim.g.neovide` and adjusting the rows of the UI would be highly appreciated.

Another question: Is there a way to maximize the height of the input area, either with a mapping or by pressing Enter while typing, so the area gets bigger?

Thank you

**Comment by pidgeon777** [comment]
I'm also using `Neovide` and having the same issue. I have no issue when using `nvim` with no GUI.

**Comment by aarnphm** [comment]
can you check with the latest version?

**Comment by bassamsdata** [comment]
Thank you, I appreciate the efforts.

It's working normally in normal mode now, but once I select even one line in visual mode, the issue happens again. The input mode gets pushed down to the command line area, so nothing can be seen there.

<img width="471" alt="Screenshot 2024-08-21 at 7 34 19 PM" src="https://github.com/user-attachments/assets/b3cb0b4d-8c7f-4eb9-80a3-a5247c083471">

**Comment by yetone** [comment]
> @aarnphm thank you for solving the issue, but it appears the "Chat with Selected Code" feature have similar issue in both normal Neovim and Neovide:
> 
> 1. In normal Neovim running in the terminal, it pushes the input area too far down, covering the status line.
> 2. In Neovide, the input area goes even deeper, down to the behind command line, making it impossible to see what I'm typing.
> 
> Thank you
> 
> screenshots for both: neovim: <img alt="Screenshot 2024-08-23 at 11 22 26 AM" width="1663" src="https://private-user-images.githubusercontent.com/105807570/360980617-6d244e34-e89f-4d4d-a37f-92b993835229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0Mjg2MzgsIm5iZiI6MTcyNDQyODMzOCwicGF0aCI6Ii8xMDU4MDc1NzAvMzYwOTgwNjE3LTZkMjQ0ZTM0LWU4OWYtNGQ0ZC1hMzdmLTkyYjk5MzgzNTIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDQ1Y2ZjM2NhOTliMjhiZDRmNTEyYjdjZGJjM2MxM2Q0YWYxNmRjYTA4NjkxNTRjYzdkZWVmNTM2ZWUwMDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9pgz-zogaclGEANQYwNB_tiMdheaeKIVPztL8I4-Mrg">
> 
> neovide: <img alt="Screenshot 2024-08-23 at 11 23 23 AM" width="1279" src="https://private-user-images.githubusercontent.com/105807570/360980659-62fbe048-a3e6-4f7d-ba8f-eb896390d148.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0Mjg2MzgsIm5iZiI6MTcyNDQyODMzOCwicGF0aCI6Ii8xMDU4MDc1NzAvMzYwOTgwNjU5LTYyZmJlMDQ4LWEzZTYtNGY3ZC1iYThmLWViODk2MzkwZDE0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNTUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTI2MDAwMTZhYTZiMjhkNTIyYTZlY2VkZTE3ZjEwYjZiMzFlMWY3ZmJmMTUzZjM5YTIzZGE3OWU5NjVhNzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9qfcxJPSgQVfWgnAx6m-NHP0TlcFrg_KVtfNL8hrgCg">

This issue has been fixed in the latest version.

**Comment by bassamsdata** [comment]
thank you, it's been solved indeed.
