### ISSUE TITLE
feature: create files/directories (with structure) when they don't exist

### ISSUE THREAD

**Issue by makermotion** [yetone/avante.nvim#989]
### Feature request

I would like the avante to create files with suggested code when files do not exist

### Motivation

to create projects with suggested directory structures from models.

**Comment by sanjeethboddi** [comment]
Hi Any updates on this?

**Comment by brewinski** [comment]
This PR has been merged. https://github.com/yetone/avante.nvim/pull/991

I'm not sure if this covers the feature request 100% though?

**Comment by makermotion** [comment]
yes you are right. it creates files now if they don't exist. we can close this. but one extra comment; even though not related to this issue directly, I feel like (can't quantify sorry) repomap is not enough for inter-file information awareness.
